# Quantization-Aware Training on Different Architectures

In [29]:
# Import necessary libraries for file handling, data manipulation, and visualization
import os
import random
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Import libraries for working with images and transformations
from PIL import Image
import cv2 as cv

# Import PyTorch modules for model building, data handling, and evaluation
import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torch.nn.functional as F
import torchvision.models as models
import torch.quantization as qt
from torch.quantization import QuantStub, DeQuantStub
from torch.utils.checkpoint import checkpoint
from torch.utils.data import Dataset, DataLoader, Subset
from timm import create_model

from torchinfo import summary

# Import libraries for machine learning metrics and model evaluation
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, r2_score, confusion_matrix
# import torchmetric
from tqdm import tqdm
from datetime import datetime
import json
import csv

import warnings
warnings.filterwarnings('ignore')
import gc

# Set the seed.
seed = 42
torch.manual_seed(seed)

In [30]:
data_dir="/home/sebastian-cruz6/cp-anemia-detection/data/cp-anemia/"
weights_dir="/home/sebastian-cruz6/cp-anemia-detection/notebooks/weights/"
metrics_dir="/home/sebastian-cruz6/cp-anemia-detection/notebooks/metrics/"

# data_dir = "/content/drive/MyDrive/CAWT_Sebastian_202425/CP-AnemiC/"
# weights_dir = "/content/drive/MyDrive/CAWT_Sebastian_202425/Weights/"
anemic_dir=data_dir+"/Anemic/"
non_anemic_dir=data_dir+"/Non-anemic/"
signature = "QUANTIZATION"

In [31]:
data_sheet_path = data_dir+"Anemia_Data_Collection_Sheet.csv"
data_sheet = pd.read_csv(data_sheet_path)
display(data_sheet)

,IMAGE_ID,HB_LEVEL,Severity,Age(Months),GENDER,REMARK,HOSPITAL,CITY/TOWN,MUNICIPALITY/DISTRICT,REGION,COUNTRY
0,Image_001,9.80,Moderate,6,Female,Anemic,Nkawie-Toase Government Hospital,Nkawie-Toase,Atwima Nwabiagya South,Ashanti,Ghana
1,Image_002,9.90,Moderate,24,Male,Anemic,Ejusu Government Hospital,Ejusu,Ejusu Municipality,Ashanti,Ghana
2,Image_003,11.10,Non-Anemic,24,Female,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
3,Image_004,12.50,Non-Anemic,12,Male,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
4,Image_005,9.90,Moderate,24,Male,Anemic,Sunyani Municipal Hospital,Sunyani,Sunyani Municipality,Bono,Ghana
...,...,...,...,...,...,...,...,...,...,...,...
705,Image_706,12.80,Non-Anemic,48,Male,Non-anemic,Bolgatanga Regional Hospital,Bolgatanga,Bolgatanga Municipality,Upper East,Ghana
706,Image_707,11.47,Non-Anemic,48,Female,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
707,Image_708,11.60,Non-Anemic,60,Male,Non-anemic,Komfo Anokye Teaching Hospital,Kumasi,Kumasi Metropolitan,Ashanti,Ghana
708,Image_709,12.10,Non-Anemic,48,Male,Non-anemic,Bolgatanga Regional Hospital,Bolgatanga,Bolgatanga Municipality,Upper East,Ghana
709,Image_710,11.70,Non-Anemic,24,Male,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana

In [32]:
# Mapping diagnosis to severity
severity_mapping = {
    "Non-Anemic": 0,
    "Mild": 1,
    "Moderate": 2,
    "Severe": 3,
}

data_sheet['Severity'] = data_sheet['Severity'].map(severity_mapping)
display(data_sheet)

,IMAGE_ID,HB_LEVEL,Severity,Age(Months),GENDER,REMARK,HOSPITAL,CITY/TOWN,MUNICIPALITY/DISTRICT,REGION,COUNTRY
0,Image_001,9.80,2,6,Female,Anemic,Nkawie-Toase Government Hospital,Nkawie-Toase,Atwima Nwabiagya South,Ashanti,Ghana
1,Image_002,9.90,2,24,Male,Anemic,Ejusu Government Hospital,Ejusu,Ejusu Municipality,Ashanti,Ghana
2,Image_003,11.10,0,24,Female,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
3,Image_004,12.50,0,12,Male,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
4,Image_005,9.90,2,24,Male,Anemic,Sunyani Municipal Hospital,Sunyani,Sunyani Municipality,Bono,Ghana
...,...,...,...,...,...,...,...,...,...,...,...
705,Image_706,12.80,0,48,Male,Non-anemic,Bolgatanga Regional Hospital,Bolgatanga,Bolgatanga Municipality,Upper East,Ghana
706,Image_707,11.47,0,48,Female,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana
707,Image_708,11.60,0,60,Male,Non-anemic,Komfo Anokye Teaching Hospital,Kumasi,Kumasi Metropolitan,Ashanti,Ghana
708,Image_709,12.10,0,48,Male,Non-anemic,Bolgatanga Regional Hospital,Bolgatanga,Bolgatanga Municipality,Upper East,Ghana
709,Image_710,11.70,0,24,Male,Non-anemic,Ahmadiyya Muslim Hospital,Tachiman,Techiman Municipality,Bono-East,Ghana

In [33]:
# Define data augmentations or transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=np.random.rand()),
    transforms.RandomVerticalFlip(p=np.random.rand()),
    transforms.RandomRotation(degrees=np.random.randint(0, 360)),
    transforms.RandomAffine(degrees=np.random.randint(0, 360)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Custom dataset class
class CPAnemiCDataset(Dataset):
    def __init__(self, dir, df, transform=None):
        self.dir = dir
        self.df = df
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_id = row['IMAGE_ID']
        img_folder = row['REMARK']
        img_path = os.path.join(self.dir, img_folder, img_id + ".png")
        img = Image.open(img_path).convert('RGB')

        if self.transform:
            img = self.transform(img)

        multiclass_label = torch.tensor(row['Severity'])
        hb_level = torch.tensor(row['HB_LEVEL'])

        return img, multiclass_label, hb_level

    # Load the dataset
image_dataset = CPAnemiCDataset(data_dir, data_sheet, transform=transform)
train_dataset, test_dataset = train_test_split(image_dataset, test_size=0.20, shuffle=True)

print(f"Image Dataset Size (All): {len(image_dataset)}, \
        Train Size: {len(train_dataset)}, \
        Test Size: {len(test_dataset)}")

BATCH_SIZE = 32
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, pin_memory=True)

Image Dataset Size (All): 710,         Train Size: 568,         Test Size: 142

In [34]:
# Default device
device = torch.device('cpu')

# Check for CUDA availability
if torch.cuda.is_available():
    device = torch.device("cuda:1")
else:
    print("CUDA is not available, using CPU.")

print(f"Selected device: {device}")

Selected device: cuda:1

In [35]:
!nvidia-smi

Fri Mar 14 17:58:45 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:41:00.0 Off |                  Off |
| 30%   42C    P2            145W /  480W |    4405MiB /  24564MiB |     32%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:82:00.0 Off |                  Off |
|  0%   43C    P2             84W /  480W |     857MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2155      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A     79601      C   ...cp-anemia-detection/cawt/bin/python       1292MiB |
|    0   N/A  N/A     81682      C   ...cp-anemia-detection/cawt/bin/python       2704MiB |
|    0   N/A  N/A     86678      C   ...cp-anemia-detection/cawt/bin/python        384MiB |
|    1   N/A  N/A      2155      G   /usr/lib/xorg/Xorg                              9MiB |
|    1   N/A  N/A      2269      G   /usr/bin/gnome-shell                           10MiB |
|    1   N/A  N/A     86678      C   ...cp-anemia-detection/cawt/bin/python        820MiB |
+-----------------------------------------------------------------------------------------+

In [ ]:
def get_model_size(model, model_type="pytorch", model_path="model.onnx"):
    """Returns model size in MB"""
    if model_type == "pytorch":
        torch.save(model.state_dict(), "tmp.pt")
        model_size = os.path.getsize("tmp.pt") / 1e6  # Convert bytes to MB
        os.remove("tmp.pt")
    elif model_type == "onnx":
        model_size = os.path.getsize(model_path) / 1e6
    return f"Model Size: {model_size:.2f} MB"

# Function to measure inference time & memory
def timed_forward(model, img, mode="pytorch", precision="fp32", ort_session=None, trt_context=None):
    """Measures inference time and memory usage for PyTorch, ONNX, and TensorRT."""
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)

    # Clear cache
    torch.cuda.empty_cache()
    gc.collect()

    # Record memory usage before inference
    torch.cuda.reset_peak_memory_stats()
    mem_before = torch.cuda.memory_allocated()
    max_mem_before = torch.cuda.max_memory_allocated()

    # Apply precision setting
    if precision == "fp16":
        model.half()
        img = img.half()

    # Start measuring latency
    start_event.record()

    if mode == "pytorch":
        class_pred, reg_pred = model(img)
    elif mode == "onnx":
        ort_inputs = {ort_session.get_inputs()[0].name: img.cpu().numpy()}
        output = ort_session.run(None, ort_inputs)
        class_pred, reg_pred = torch.tensor(output[0]), torch.tensor(output[1])

    elif mode == "trt":
        trt_context.execute_v2([img.contiguous().data_ptr()])
        class_pred, reg_pred = None, None  # Modify if using TensorRT output

    end_event.record()
    torch.cuda.synchronize()  # Ensure accurate timing
    latency = start_event.elapsed_time(end_event)  # Time in ms

    # Record memory usage after inference
    mem_after = torch.cuda.memory_allocated()
    max_mem_after = torch.cuda.max_memory_allocated()

    # Store stats
    stats = {
        "latency": latency,
        "malloc_before": mem_before,
        "malloc_after": mem_after,
        "max_malloc": max_mem_after,
    }

    return class_pred, reg_pred, stats

# Static Weighting Function. Set eta_class to desired importance (Classification > .5, Regression < .5, Equal == .5)
def sw_loss(loss_class, loss_reg, eta_class=0.5):
    eta_reg = 1 - eta_class
    total_loss = (eta_class * loss_class) + (eta_reg * loss_reg)
    return total_loss

In [37]:
class MultiModel(nn.Module):
    MODEL_MAPPING = {
        "mobilenetv2": lambda: models.mobilenet_v2(pretrained=False),
        "resnet18": lambda: models.resnet18(pretrained=False),
        "densenet121": lambda: models.densenet121(pretrained=False),
        "vgg16": lambda: models.vgg16(pretrained=False),
        "vit-tiny": lambda: create_model("vit_tiny_patch16_224", pretrained=False),
        "convnext-tiny": lambda: models.convnext_tiny(pretrained=False),
        "efficientnet-b0": lambda: models.efficientnet_b0(pretrained=False),
        "shufflenetv2-0.5x": lambda: models.shufflenet_v2_x0_5(pretrained=False),
        "regnety-400mf": lambda: models.regnet_y_400mf(pretrained=False),
        "mnasnet0_5": lambda: models.mnasnet0_5(pretrained=False),
        "ghostnetv2": lambda: create_model('ghostnetv2_100.in1k', pretrained=False),
        "tinynet-a": lambda: create_model("tinynet_a.in1k", pretrained=False)
    }

    FEATURE_LAYER_MAPPING = {
        "fc": ["resnet", "shufflenet", "regnet"],
        "classifier": ["densenet", "vgg", "mobilenet", "efficientnet",
                       "mnasnet","convnext", "ghostnet", "tinynet"],
        "head": ["vit"]
    }

    def __init__(self, model_name):
        super().__init__()

        self.quant = QuantStub() # Start quantization
        
        self.model_name = model_name.lower()

        if self.model_name not in self.MODEL_MAPPING:
            raise ValueError(f"Model {model_name} not supported")

        self.model = self.MODEL_MAPPING[self.model_name]()
        num_ftrs = self._get_feature_size()

        print(f"Initial Backbone {get_model_size(self.model)}")

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(p=0.2),
            nn.Linear(num_ftrs, 128),
            nn.ReLU(),
            nn.Linear(128, 5)
        )


        self._assign_classifier()
        self.dequant = DeQuantStub() # Convert back to fp32
        print(f"Modified Backbone {get_model_size(self.model)}\n")

    def _get_feature_size(self):
        """Retrieve the number of input features for the last layer."""
        # Special case for VGG16 since its features need flattening
        if "vgg" in self.model_name:
            return 25088  # VGG16 outputs (batch, 512, 7, 7) -> flattened to 25088

        feature_layers = {
            "fc": getattr(self.model, "fc", None),
            "classifier": getattr(self.model, "classifier", None),
            "head": getattr(self.model, "head", None)
        }

        for key, layer in feature_layers.items():
            if layer:
                return layer[-1].in_features if isinstance(layer, nn.Sequential) else layer.in_features

        return getattr(self.model, "num_features", None)

    def _assign_classifier(self):
        """Assigns the appropriate classifier to the model based on its architecture."""
        if "vgg" in self.model_name:
            self.model.classifier = self.classifier
        else:
          for attr, models in self.FEATURE_LAYER_MAPPING.items():
            if any(m in self.model_name for m in models):
                setattr(self.model, attr, self.classifier)
                return

    def forward(self, x):
        output = self.model(x)
        return output[:, :4], output[:, 4]  # Class probabilities and Hb level estimate

In [38]:
models_list = ["mobilenetv2", "resnet18", "densenet121", "vgg16", "vit-tiny",
               "efficientnet-b0", "shufflenetv2-0.5x", "regnety-400mf",
               "mnasnet0_5", "convnext-tiny", "ghostnetv2", "tinynet-a"
               ]
for arch in models_list:
    print(f"Loading model: {arch}")
    model = MultiModel(arch).to(device)
    print(summary(model))
    # print(model)

Loading model: mobilenetv2
Initial Backbone Model Size: 14.24 MB
Modified Backbone Model Size: 9.78 MB

================================================================================
Layer (type:depth-idx)                                  Param #
================================================================================
MultiModel                                              --
├─QuantStub: 1-1                                        --
├─MobileNetV2: 1-2                                      --
│    └─Sequential: 2-1                                  --
│    │    └─Conv2dNormActivation: 3-1                   928
│    │    └─InvertedResidual: 3-2                       896
│    │    └─InvertedResidual: 3-3                       5,136
│    │    └─InvertedResidual: 3-4                       8,832
│    │    └─InvertedResidual: 3-5                       10,000
│    │    └─InvertedResidual: 3-6                       14,848
│    │    └─InvertedResidual: 3-7                       14,848
│    │    └─InvertedResidual: 3-8                       21,056
│    │    └─InvertedResidual: 3-9                       54,272
│    │    └─InvertedResidual: 3-10                      54,272
│    │    └─InvertedResidual: 3-11                      54,272
│    │    └─InvertedResidual: 3-12                      66,624
│    │    └─InvertedResidual: 3-13                      118,272
│    │    └─InvertedResidual: 3-14                      118,272
│    │    └─InvertedResidual: 3-15                      155,264
│    │    └─InvertedResidual: 3-16                      320,000
│    │    └─InvertedResidual: 3-17                      320,000
│    │    └─InvertedResidual: 3-18                      473,920
│    │    └─Conv2dNormActivation: 3-19                  412,160
│    └─Sequential: 2-2                                  --
│    │    └─Flatten: 3-20                               --
│    │    └─Dropout: 3-21                               --
│    │    └─Linear: 3-22                                163,968
│    │    └─ReLU: 3-23                                  --
│    │    └─Linear: 3-24                                645
├─Sequential: 1-3                                       (recursive)
│    └─Flatten: 2-3                                     --
│    └─Dropout: 2-4                                     --
│    └─Linear: 2-5                                      (recursive)
│    └─ReLU: 2-6                                        --
│    └─Linear: 2-7                                      (recursive)
├─DeQuantStub: 1-4                                      --
================================================================================
Total params: 2,388,485
Trainable params: 2,388,485
Non-trainable params: 0
================================================================================
Loading model: resnet18
Initial Backbone Model Size: 46.83 MB
Modified Backbone Model Size: 45.04 MB

======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
MultiModel                                    --
├─QuantStub: 1-1                              --
├─ResNet: 1-2                                 --
│    └─Conv2d: 2-1                            9,408
│    └─BatchNorm2d: 2-2                       128
│    └─ReLU: 2-3                              --
│    └─MaxPool2d: 2-4                         --
│    └─Sequential: 2-5                        --
│    │    └─BasicBlock: 3-1                   73,984
│    │    └─BasicBlock: 3-2                   73,984
│    └─Sequential: 2-6                        --
│    │    └─BasicBlock: 3-3                   230,144
│    │    └─BasicBlock: 3-4                   295,424
│    └─Sequential: 2-7                        --
│    │    └─BasicBlock: 3-5                   919,040
│    │    └─BasicBlock: 3-6                   1,180,672
│    └─Sequential: 2-8                        --
│    │    └─BasicBlock: 3-7                   3,673,088
│    │    └─BasicBlock: 3-8                   4,720,640
│    └─AdaptiveAvgPool2d: 2-9                 --
│    └─Sequential: 2-10                       --
│    │    └─Flatten: 3-9                      --
│    │    └─Dropout: 3-10                     --
│    │    └─Linear: 3-11                      65,664
│    │    └─ReLU: 3-12                        --
│    │    └─Linear: 3-13                      645
├─Sequential: 1-3                             (recursive)
│    └─Flatten: 2-11                          --
│    └─Dropout: 2-12                          --
│    └─Linear: 2-13                           (recursive)
│    └─ReLU: 2-14                             --
│    └─Linear: 2-15                           (recursive)
├─DeQuantStub: 1-4                            --
======================================================================
Total params: 11,242,821
Trainable params: 11,242,821
Non-trainable params: 0
======================================================================
Loading model: densenet121
Initial Backbone Model Size: 32.47 MB
Modified Backbone Model Size: 28.90 MB

======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
MultiModel                                    --
├─QuantStub: 1-1                              --
├─DenseNet: 1-2                               --
│    └─Sequential: 2-1                        --
│    │    └─Conv2d: 3-1                       9,408
│    │    └─BatchNorm2d: 3-2                  128
│    │    └─ReLU: 3-3                         --
│    │    └─MaxPool2d: 3-4                    --
│    │    └─_DenseBlock: 3-5                  335,040
│    │    └─_Transition: 3-6                  33,280
│    │    └─_DenseBlock: 3-7                  919,680
│    │    └─_Transition: 3-8                  132,096
│    │    └─_DenseBlock: 3-9                  2,837,760
│    │    └─_Transition: 3-10                 526,336
│    │    └─_DenseBlock: 3-11                 2,158,080
│    │    └─BatchNorm2d: 3-12                 2,048
│    └─Sequential: 2-2                        --
│    │    └─Flatten: 3-13                     --
│    │    └─Dropout: 3-14                     --
│    │    └─Linear: 3-15                      131,200
│    │    └─ReLU: 3-16                        --
│    │    └─Linear: 3-17                      645
├─Sequential: 1-3                             (recursive)
│    └─Flatten: 2-3                           --
│    └─Dropout: 2-4                           --
│    └─Linear: 2-5                            (recursive)
│    └─ReLU: 2-6                              --
│    └─Linear: 2-7                            (recursive)
├─DeQuantStub: 1-4                            --
======================================================================
Total params: 7,085,701
Trainable params: 7,085,701
Non-trainable params: 0
======================================================================
Loading model: vgg16
Initial Backbone Model Size: 553.44 MB
Modified Backbone Model Size: 71.72 MB

=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
MultiModel                               --
├─QuantStub: 1-1                         --
├─VGG: 1-2                               --
│    └─Sequential: 2-1                   --
│    │    └─Conv2d: 3-1                  1,792
│    │    └─ReLU: 3-2                    --
│    │    └─Conv2d: 3-3                  36,928
│    │    └─ReLU: 3-4                    --
│    │    └─MaxPool2d: 3-5               --
│    │    └─Conv2d: 3-6                  73,856
│    │    └─ReLU: 3-7                    --
│    │    └─Conv2d: 3-8                  147,584
│    │    └─ReLU: 3-9                    --
│    │    └─MaxPool2d: 3-10              --
│    │    └─Conv2d: 3-11                 295,168
│    │    └─ReLU: 3-12                   --
│    │    └─Conv2d: 3-13                 590,080
│    │    └─ReLU: 3-14                   --
│    │    └─Conv2d: 3-15                 590,080
│    │    └─ReLU: 3-16                   --
│    │    └─MaxPool2d: 3-17              --
│    │    └─Conv2d: 3-18                 1,180,160
│    │    └─ReLU: 3-19                   --
│    │    └─Conv2d: 3-20                 2,359,808
│    │    └─ReLU: 3-21                   --
│    │    └─Conv2d: 3-22                 2,359,808
│    │    └─ReLU: 3-23                   --
│    │    └─MaxPool2d: 3-24              --
│    │    └─Conv2d: 3-25                 2,359,808
│    │    └─ReLU: 3-26                   --
│    │    └─Conv2d: 3-27                 2,359,808
│    │    └─ReLU: 3-28                   --
│    │    └─Conv2d: 3-29                 2,359,808
│    │    └─ReLU: 3-30                   --
│    │    └─MaxPool2d: 3-31              --
│    └─AdaptiveAvgPool2d: 2-2            --
│    └─Sequential: 2-3                   --
│    │    └─Flatten: 3-32                --
│    │    └─Dropout: 3-33                --
│    │    └─Linear: 3-34                 3,211,392
│    │    └─ReLU: 3-35                   --
│    │    └─Linear: 3-36                 645
├─Sequential: 1-3                        (recursive)
│    └─Flatten: 2-4                      --
│    └─Dropout: 2-5                      --
│    └─Linear: 2-6                       (recursive)
│    └─ReLU: 2-7                         --
│    └─Linear: 2-8                       (recursive)
├─DeQuantStub: 1-4                       --
=================================================================
Total params: 17,926,725
Trainable params: 17,926,725
Non-trainable params: 0
=================================================================
Loading model: vit-tiny
Initial Backbone Model Size: 22.92 MB
Modified Backbone Model Size: 22.25 MB

======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
MultiModel                                    --
├─QuantStub: 1-1                              --
├─VisionTransformer: 1-2                      38,016
│    └─PatchEmbed: 2-1                        --
│    │    └─Conv2d: 3-1                       147,648
│    │    └─Identity: 3-2                     --
│    └─Dropout: 2-2                           --
│    └─Identity: 2-3                          --
│    └─Identity: 2-4                          --
│    └─Sequential: 2-5                        --
│    │    └─Block: 3-3                        444,864
│    │    └─Block: 3-4                        444,864
│    │    └─Block: 3-5                        444,864
│    │    └─Block: 3-6                        444,864
│    │    └─Block: 3-7                        444,864
│    │    └─Block: 3-8                        444,864
│    │    └─Block: 3-9                        444,864
│    │    └─Block: 3-10                       444,864
│    │    └─Block: 3-11                       444,864
│    │    └─Block: 3-12                       444,864
│    │    └─Block: 3-13                       444,864
│    │    └─Block: 3-14                       444,864
│    └─LayerNorm: 2-6                         384
│    └─Identity: 2-7                          --
│    └─Dropout: 2-8                           --
│    └─Sequential: 2-9                        --
│    │    └─Flatten: 3-15                     --
│    │    └─Dropout: 3-16                     --
│    │    └─Linear: 3-17                      24,704
│    │    └─ReLU: 3-18                        --
│    │    └─Linear: 3-19                      645
├─Sequential: 1-3                             (recursive)
│    └─Flatten: 2-10                          --
│    └─Dropout: 2-11                          --
│    └─Linear: 2-12                           (recursive)
│    └─ReLU: 2-13                             --
│    └─Linear: 2-14                           (recursive)
├─DeQuantStub: 1-4                            --
======================================================================
Total params: 5,549,765
Trainable params: 5,549,765
Non-trainable params: 0
======================================================================
Loading model: efficientnet-b0
Initial Backbone Model Size: 21.43 MB
Modified Backbone Model Size: 16.96 MB

=====================================================================================
Layer (type:depth-idx)                                       Param #
=====================================================================================
MultiModel                                                   --
├─QuantStub: 1-1                                             --
├─EfficientNet: 1-2                                          --
│    └─Sequential: 2-1                                       --
│    │    └─Conv2dNormActivation: 3-1                        928
│    │    └─Sequential: 3-2                                  1,448
│    │    └─Sequential: 3-3                                  16,714
│    │    └─Sequential: 3-4                                  46,640
│    │    └─Sequential: 3-5                                  242,930
│    │    └─Sequential: 3-6                                  543,148
│    │    └─Sequential: 3-7                                  2,026,348
│    │    └─Sequential: 3-8                                  717,232
│    │    └─Conv2dNormActivation: 3-9                        412,160
│    └─AdaptiveAvgPool2d: 2-2                                --
│    └─Sequential: 2-3                                       --
│    │    └─Flatten: 3-10                                    --
│    │    └─Dropout: 3-11                                    --
│    │    └─Linear: 3-12                                     163,968
│    │    └─ReLU: 3-13                                       --
│    │    └─Linear: 3-14                                     645
├─Sequential: 1-3                                            (recursive)
│    └─Flatten: 2-4                                          --
│    └─Dropout: 2-5                                          --
│    └─Linear: 2-6                                           (recursive)
│    └─ReLU: 2-7                                             --
│    └─Linear: 2-8                                           (recursive)
├─DeQuantStub: 1-4                                           --
=====================================================================================
Total params: 4,172,161
Trainable params: 4,172,161
Non-trainable params: 0
=====================================================================================
Loading model: shufflenetv2-0.5x
Initial Backbone Model Size: 5.59 MB
Modified Backbone Model Size: 2.02 MB

======================================================================
Layer (type:depth-idx)                        Param #
======================================================================
MultiModel                                    --
├─QuantStub: 1-1                              --
├─ShuffleNetV2: 1-2                           --
│    └─Sequential: 2-1                        --
│    │    └─Conv2d: 3-1                       648
│    │    └─BatchNorm2d: 3-2                  48
│    │    └─ReLU: 3-3                         --
│    └─MaxPool2d: 2-2                         --
│    └─Sequential: 2-3                        --
│    │    └─InvertedResidual: 3-4             2,400
│    │    └─InvertedResidual: 3-5             1,512
│    │    └─InvertedResidual: 3-6             1,512
│    │    └─InvertedResidual: 3-7             1,512
│    └─Sequential: 2-4                        --
│    │    └─InvertedResidual: 3-8             8,256
│    │    └─InvertedResidual: 3-9             5,328
│    │    └─InvertedResidual: 3-10            5,328
│    │    └─InvertedResidual: 3-11            5,328
│    │    └─InvertedResidual: 3-12            5,328
│    │    └─InvertedResidual: 3-13            5,328
│    │    └─InvertedResidual: 3-14            5,328
│    │    └─InvertedResidual: 3-15            5,328
│    └─Sequential: 2-5                        --
│    │    └─InvertedResidual: 3-16            30,336
│    │    └─InvertedResidual: 3-17            19,872
│    │    └─InvertedResidual: 3-18            19,872
│    │    └─InvertedResidual: 3-19            19,872
│    └─Sequential: 2-6                        --
│    │    └─Conv2d: 3-20                      196,608
│    │    └─BatchNorm2d: 3-21                 2,048
│    │    └─ReLU: 3-22                        --
│    └─Sequential: 2-7                        --
│    │    └─Flatten: 3-23                     --
│    │    └─Dropout: 3-24                     --
│    │    └─Linear: 3-25                      131,200
│    │    └─ReLU: 3-26                        --
│    │    └─Linear: 3-27                      645
├─Sequential: 1-3                             (recursive)
│    └─Flatten: 2-8                           --
│    └─Dropout: 2-9                           --
│    └─Linear: 2-10                           (recursive)
│    └─ReLU: 2-11                             --
│    └─Linear: 2-12                           (recursive)
├─DeQuantStub: 1-4                            --
======================================================================
Total params: 473,637
Trainable params: 473,637
Non-trainable params: 0
======================================================================
Loading model: regnety-400mf
Initial Backbone Model Size: 17.61 MB
Modified Backbone Model Size: 16.07 MB

=====================================================================================
Layer (type:depth-idx)                                       Param #
=====================================================================================
MultiModel                                                   --
├─QuantStub: 1-1                                             --
├─RegNet: 1-2                                                --
│    └─SimpleStemIN: 2-1                                     --
│    │    └─Conv2d: 3-1                                      864
│    │    └─BatchNorm2d: 3-2                                 64
│    │    └─ReLU: 3-3                                        --
│    └─Sequential: 2-2                                       --
│    │    └─AnyStage: 3-4                                    10,040
│    │    └─AnyStage: 3-5                                    102,296
│    │    └─AnyStage: 3-6                                    737,438
│    │    └─AnyStage: 3-7                                    3,052,442
│    └─AdaptiveAvgPool2d: 2-3                                --
│    └─Sequential: 2-4                                       --
│    │    └─Flatten: 3-8                                     --
│    │    └─Dropout: 3-9                                     --
│    │    └─Linear: 3-10                                     56,448
│    │    └─ReLU: 3-11                                       --
│    │    └─Linear: 3-12                                     645
├─Sequential: 1-3                                            (recursive)
│    └─Flatten: 2-5                                          --
│    └─Dropout: 2-6                                          --
│    └─Linear: 2-7                                           (recursive)
│    └─ReLU: 2-8                                             --
│    └─Linear: 2-9                                           (recursive)
├─DeQuantStub: 1-4                                           --
=====================================================================================
Total params: 3,960,237
Trainable params: 3,960,237
Non-trainable params: 0
=====================================================================================
Loading model: mnasnet0_5
Initial Backbone Model Size: 9.04 MB
Modified Backbone Model Size: 4.58 MB

===========================================================================
Layer (type:depth-idx)                             Param #

In [39]:
def train(dataloader, model, class_loss, reg1_loss, reg2_loss, optimizer):
    """Trains the model and logs additional metrics."""
    model.train()
    model.qconfig = torch.quantization.get_default_qat_qconfig('fbgemm')  # Choose backend. FBGEMM is Best for CPUs (like Intel, ARM).
    model = torch.quantization.prepare_qat(model)

    total_loss = 0
    total_ce_loss = 0
    total_mse_loss = 0
    total_mae_loss = 0
    correct = 0
    total_samples = 0

    all_preds = []
    all_targets = []
    all_probs = []
    all_hb_targets = []
    all_hb_preds = []

    for _, (img, multiclass, hb_level) in enumerate(dataloader):
        img = img.to(device)
        multiclass = multiclass.to(device).long()
        hb_level = hb_level.to(device).unsqueeze(1).float()

        optimizer.zero_grad()

        # Forward pass
        class_pred, reg_pred = model(img)

        # Compute losses
        ce_loss = class_loss(class_pred, multiclass)
        mse_loss = reg1_loss(reg_pred, hb_level)
        mae_loss = reg2_loss(reg_pred, hb_level)
        loss = sw_loss(ce_loss, mse_loss, 0.7)  # Weighted loss

        # Backpropagation
        loss.backward()
        optimizer.step()

        # Track total losses
        total_loss += loss.item()
        total_ce_loss += ce_loss.item()
        total_mse_loss += mse_loss.item()
        total_mae_loss += mae_loss.item()

        # Compute classification accuracy
        class_probs = F.softmax(class_pred, dim=1)
        highest_prob_class = torch.argmax(class_probs, dim=1)

        correct += (highest_prob_class == multiclass).sum().item()
        total_samples += multiclass.size(0)

        # Collect data for additional metrics
        all_preds.extend(highest_prob_class.detach().cpu().numpy())
        all_targets.extend(multiclass.detach().cpu().numpy())
        all_probs.extend(class_probs.detach().cpu().numpy())
        all_hb_targets.extend(hb_level.detach().cpu().numpy())
        all_hb_preds.extend(reg_pred.squeeze().cpu().detach().numpy())

    # Compute additional metrics
    precision = precision_score(all_targets, all_preds, average="weighted")
    recall = recall_score(all_targets, all_preds, average="weighted")
    f1 = f1_score(all_targets, all_preds, average="weighted")
    auc = roc_auc_score(all_targets, all_probs, multi_class="ovr")
    r2 = r2_score(all_hb_targets, all_hb_preds)

    # Compute final statistics
    avg_loss = total_loss / len(dataloader)
    avg_ce_loss = total_ce_loss / len(dataloader)
    avg_mse_loss = total_mse_loss / len(dataloader)
    avg_mae_loss = total_mae_loss / len(dataloader)
    accuracy = correct / total_samples

    # Store metrics
    final_metrics = [avg_loss, avg_ce_loss, accuracy, precision, recall, f1, auc, r2, avg_mae_loss, avg_mse_loss]

    return final_metrics

In [40]:
def eval(dataloader, model, class_loss, reg1_loss, reg2_loss, mode="pytorch", precision="fp32", ort_session=None, trt_context=None):
    """Evaluates the model with additional metrics: Precision, Recall, AUC, F1, R², Memory Usage, and Latency."""
    model.eval()
    if precision == "int8":
        model = torch.quantization.convert(model).to(device)
    
    mean_stats = []
    total_loss = 0
    total_ce_loss = 0
    total_mse_loss = 0
    total_mae_loss = 0
    correct = 0
    total_samples = 0

    all_preds = []
    all_targets = []
    all_probs = []
    all_hb_targets = []
    all_hb_preds = []

    torch.cuda.empty_cache()
    gc.collect()

    with torch.no_grad():
        for _, (img, multiclass, hb_level) in enumerate(dataloader):
            img = img.to(device)
            multiclass = multiclass.to(device).long()
            hb_level = hb_level.to(device).unsqueeze(1).float()

            # Forward pass with latency & memory tracking
            class_pred, reg_pred, stats = timed_forward(model, img, mode, ort_session, trt_context)
            mean_stats.append(stats)

            # Compute losses
            ce_loss = class_loss(class_pred, multiclass)
            mse_loss = reg1_loss(reg_pred, hb_level)
            mae_loss = reg2_loss(reg_pred, hb_level)
            loss = sw_loss(ce_loss, mse_loss, 0.7)

            # Track total losses
            total_loss += loss.item()
            total_ce_loss += ce_loss.item()
            total_mse_loss += mse_loss.item()
            total_mae_loss += mae_loss.item()

            # Compute classification accuracy
            class_probs = F.softmax(class_pred, dim=1)
            highest_prob_class = torch.argmax(class_probs, dim=1)

            correct += (highest_prob_class == multiclass).sum().item()
            total_samples += multiclass.size(0)

            # Collect data for additional metrics
            all_preds.extend(highest_prob_class.detach().cpu().numpy())
            all_targets.extend(multiclass.detach().cpu().numpy())
            all_probs.extend(class_probs.detach().cpu().numpy())
            all_hb_targets.extend(hb_level.detach().cpu().numpy())
            all_hb_preds.extend(reg_pred.squeeze().detach().cpu().numpy())

    # Compute mean statistics
    mean_latency = np.mean([s["latency"] for s in mean_stats])
    mean_mem_before = np.mean([s["malloc_before"] for s in mean_stats]) / 1_048_576  # Convert bytes to MB
    mean_mem_after = np.mean([s["malloc_after"] for s in mean_stats]) / 1_048_576  # Convert bytes to MB
    mean_max_mem = np.mean([s["max_malloc"] for s in mean_stats]) / 1_048_576  # Convert bytes to MB

    # Store final mean statistics
    final_mean_stats = [mean_latency, mean_mem_before, mean_mem_after, mean_max_mem]

    # Compute additional evaluation metrics
    precision = precision_score(all_targets, all_preds, average="weighted")
    recall = recall_score(all_targets, all_preds, average="weighted")
    f1 = f1_score(all_targets, all_preds, average="weighted")
    auc = roc_auc_score(all_targets, all_probs, multi_class="ovr")
    r2 = r2_score(all_hb_targets, all_hb_preds)

    # Compute confusion matrix
    # cm = confusion_matrix(all_targets, all_preds)

    # Compute final average losses
    avg_loss = total_loss / len(dataloader)
    avg_ce_loss = total_ce_loss / len(dataloader)
    avg_mse_loss = total_mse_loss / len(dataloader)
    avg_mae_loss = total_mae_loss / len(dataloader)
    accuracy = correct / total_samples

    # Store metrics
    final_metrics = [avg_loss, avg_ce_loss, accuracy, precision, recall, f1, auc, r2, avg_mae_loss, avg_mse_loss]

    return final_metrics, final_mean_stats

In [41]:
def main(ARCH, BATCH_SIZE=32, EPOCHS=150, FOLDS=5):

    # Define loss functions
    cross_entropy_loss = torch.nn.CrossEntropyLoss()  # Multi-class classification loss
    mse_loss = torch.nn.MSELoss()  # Regression loss
    mae_loss = torch.nn.L1Loss()  # Regression loss

    # Set up 5-Fold Cross Validation
    kf = KFold(n_splits=FOLDS, shuffle=True, random_state=42)

    print("=" * 100)
    print(f"Training Model: {ARCH}")

    # === INITIALIZE MODEL ===
    model = MultiModel(ARCH).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

    best_val_acc = -float("inf")  # Track best validation accuracy
    train_metrics_list = []
    val_metrics_list = []

    # === TRAINING LOOP ===
    for epoch in range(EPOCHS):
        print(f"\nEpoch {epoch+1}/{EPOCHS}")
        fold = 1

        for train_idx, val_idx in kf.split(range(len(image_dataset))):
            train_subset = Subset(image_dataset, train_idx)
            val_subset = Subset(image_dataset, val_idx)

            train_loader = DataLoader(train_subset, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True)
            val_loader = DataLoader(val_subset, batch_size=BATCH_SIZE, shuffle=False, pin_memory=True)

            if fold == FOLDS:
                # === VALIDATION PHASE ===
                val_metrics, val_stats = eval(val_loader, model, cross_entropy_loss, mse_loss, mae_loss)
                print(
                    f"Validation: Fold {fold} - Total Loss: {val_metrics[0]:.4f}, Cross Entropy: {val_metrics[1]:4f}, Accuracy: {val_metrics[2]:.4f}, "
                    f"Precision: {val_metrics[3]:.4f}, Recall: {val_metrics[4]:.4f}, F1 Score: {val_metrics[5]:.4f}, AUC: {val_metrics[6]:.4f}, "
                    f"R2 Score: {val_metrics[7]:4f}, MAE: {val_metrics[8]:.4f}, MSE: {val_metrics[9]:.4f}"
                )
                print(
                    f"Avg Latency (ms): {val_stats[0]:.2f}, Avg Memory Before (MB): {val_stats[1]:.2f}, "
                    f"Avg Memory After (MB): {val_stats[2]:.2f}, Avg Max Memory (MB): {val_stats[3]:.2f}"
                )

                # Save best model based on validation accuracy
                if val_metrics[2] > best_val_acc:
                    best_val_acc = val_metrics[2]
                    torch.save(
                        model.state_dict(),
                        f"{weights_dir}/pytorch/model_best_accuracy_{ARCH}_{signature}.pth",
                    )
                    print(f"Best model saved with Accuracy: {best_val_acc:.4f}")

                # Store validation metrics
                val_metrics_list.append(
                    {
                        "epoch": epoch + 1,
                        "fold": fold,
                        "total_loss": val_metrics[0],
                        "cross_entropy_loss": val_metrics[1],
                        "accuracy": val_metrics[2],
                        "precision": val_metrics[3],
                        "recall": val_metrics[4],
                        "f1_score": val_metrics[5],
                        "auc": val_metrics[6],
                        "r2_score": val_metrics[7],
                        "mae_loss": val_metrics[8],
                        "mse_loss": val_metrics[9],
                        "latency": val_stats[0],
                        "malloc_before": val_stats[1],
                        "malloc_after": val_stats[2],
                        "max_malloc": val_stats[3],
                    }
                )

            else:
                # === TRAINING PHASE ===
                train_metrics = train(train_loader, model, cross_entropy_loss, mse_loss, mae_loss, optimizer)
                print(
                    f"Training: Fold {fold} - Total Loss: {train_metrics[0]:.4f}, Cross Entropy: {train_metrics[1]:4f}, Accuracy: {train_metrics[2]:.4f}, "
                    f"Precision: {train_metrics[3]:.4f}, Recall: {train_metrics[4]:.4f}, F1 Score: {train_metrics[5]:.4f}, AUC: {train_metrics[6]:.4f}, "
                    f"R2 Score: {train_metrics[7]:4f}, MAE: {train_metrics[8]:.4f}, MSE: {train_metrics[9]:.4f}"
                )

                # Store training metrics
                train_metrics_list.append(
                    {
                        "epoch": epoch + 1,
                        "fold": fold,
                        "total_loss": train_metrics[0],
                        "cross_entropy_loss": train_metrics[1],
                        "accuracy": train_metrics[2],
                        "precision": train_metrics[3],
                        "recall": train_metrics[4],
                        "f1_score": train_metrics[5],
                        "auc": train_metrics[6],
                        "r2_score": train_metrics[7],
                        "mae_loss": train_metrics[8],
                        "mse_loss": train_metrics[9],
                    }
                )

            fold += 1  # Move to next fold
        
        keys = train_metrics_list[0].keys()
        with open(f"{metrics_dir}/pytorch/training_metrics_{ARCH}_{signature}.csv", 'w', newline='') as output_file:
            dict_writer = csv.DictWriter(output_file, keys)
            dict_writer.writeheader()
            dict_writer.writerows(train_metrics_list)

        keys = val_metrics_list[0].keys()
        with open(f"{metrics_dir}/pytorch/validation_metrics_{ARCH}_{signature}.csv", 'w', newline='') as output_file:
            dict_writer = csv.DictWriter(output_file, keys)
            dict_writer.writeheader()
            dict_writer.writerows(val_metrics_list)

    print(f"\nFine-tuned {get_model_size(model)}")
    print("=" * 100)

In [ ]:
import onnxruntime as ort

def infer(arch, path, mode="pytorch"):
  
    # Define loss functions
    cross_entropy_loss = torch.nn.CrossEntropyLoss()  # Multi-class classification loss
    mse_loss = torch.nn.MSELoss()  # Regression loss
    mae_loss = torch.nn.L1Loss()  # Regression loss

    test_metrics_list = []
    print("="*100)
    print(f"{arch}")

    model = MultiModel(arch).to(device)
    model.load_state_dict(torch.load(f"{weights_dir}pytorch/model_best_accuracy_{arch}_{path}.pth"))
    print(f"Testing {arch} in {mode} mode")
    
    for precision in ["fp32", "fp16", "int8"]:
        print(f"Running inference for {precision}")

        ort_session = None

        if mode == "onnx":
            dummy_input = torch.randn(1, 3, 224, 224).to(device)
            onnx_path = f"{weights_dir}onnx/model_best_accuracy_{arch}_{path}.onnx"
            
            try:
                # Export ONNX Model
                torch.onnx.export(model, dummy_input, onnx_path, opset_version=11)
                print(f"Successfully exported ONNX model: {onnx_path}")

                # Load ONNX Model
                ort_session = ort.InferenceSession(onnx_path, providers=["CUDAExecutionProvider"])
            except Exception as e:
                print(f"ONNX Export/Loading Failed: {e}")
                ort_session = None  # Avoid passing None session to eval()

        # === Testing PHASE ===
        test_metrics, test_stats = eval(test_loader, model, cross_entropy_loss, mse_loss, mae_loss, mode, precision, ort_session)
        print(
            f"Testing: Total Loss: {test_metrics[0]:.4f}, Cross Entropy: {test_metrics[1]:4f}, Accuracy: {test_metrics[2]:.4f}, "
            f"Precision: {test_metrics[3]:.4f}, Recall: {test_metrics[4]:.4f}, F1 Score: {test_metrics[5]:.4f}, AUC: {test_metrics[6]:.4f}, "
            f"R2 Score: {test_metrics[7]:4f}, MAE: {test_metrics[8]:.4f}, MSE: {test_metrics[9]:.4f}"
        )
        print(
            f"Avg Latency (ms): {test_stats[0]:.2f}, Avg Memory Before (MB): {test_stats[1]:.2f}, "
            f"Avg Memory After (MB): {test_stats[2]:.2f}, Avg Max Memory (MB): {test_stats[3]:.2f}"
        )

        # Store validation metrics
        test_metrics_list.append(
            {
                "total_loss": test_metrics[0],
                "cross_entropy_loss": test_metrics[1],
                "accuracy": test_metrics[2],
                "precision": test_metrics[3],
                "recall": test_metrics[4],
                "f1_score": test_metrics[5],
                "auc": test_metrics[6],
                "r2_score": test_metrics[7],
                "mae_loss": test_metrics[8],
                "mse_loss": test_metrics[9],
                "latency": test_stats[0],
                "malloc_before": test_stats[1],
                "malloc_after": test_stats[2],
                "max_malloc": test_stats[3],
            }
        )

        keys = test_metrics_list[0].keys()
        with open(f"{metrics_dir}/pytorch/testing_metrics_{arch}_{signature}.csv", 'w', newline='') as output_file:
            dict_writer = csv.DictWriter(output_file, keys)
            dict_writer.writeheader()
            dict_writer.writerows(test_metrics_list)

In [103]:
main("mobilenetv2", EPOCHS=10)

====================================================================================================
Training Model: mobilenetv2
Initial Backbone Model Size: 14.24 MB
Modified Backbone Model Size: 9.78 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.3929, Cross Entropy: 1.333070, Accuracy: 0.4085, Precision: 0.2772, Recall: 0.4085, F1 Score: 0.2496, AUC: 0.4883, R2 Score: -20.373997, MAE: 10.3092, MSE: 111.5324
Training: Fold 2 - Total Loss: 34.4830, Cross Entropy: 1.335900, Accuracy: 0.3926, Precision: 0.2224, Recall: 0.3926, F1 Score: 0.2369, AUC: 0.4995, R2 Score: -21.559852, MAE: 10.3385, MSE: 111.8261
Training: Fold 3 - Total Loss: 34.3036, Cross Entropy: 1.342106, Accuracy: 0.3732, Precision: 0.2532, Recall: 0.3732, F1 Score: 0.2204, AUC: 0.4973, R2 Score: -21.912936, MAE: 10.3106, MSE: 111.2136
Training: Fold 4 - Total Loss: 34.8987, Cross Entropy: 1.334172, Accuracy: 0.4225, Precision: 0.3818, Recall: 0.4225, F1 Score: 0.2601, AUC: 0.5112, R2 Score: -20.368900, MAE: 10.3848, MSE: 113.2160
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 2.65, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3873

Epoch 2/10
Training: Fold 1 - Total Loss: 34.4102, Cross Entropy: 1.337870, Accuracy: 0.4032, Precision: 0.2578, Recall: 0.4032, F1 Score: 0.2501, AUC: 0.4671, R2 Score: -20.374691, MAE: 10.3133, MSE: 111.5789
Training: Fold 2 - Total Loss: 34.4720, Cross Entropy: 1.335992, Accuracy: 0.3944, Precision: 0.2119, Recall: 0.3944, F1 Score: 0.2349, AUC: 0.4943, R2 Score: -21.556755, MAE: 10.3360, MSE: 111.7893
Training: Fold 3 - Total Loss: 34.3148, Cross Entropy: 1.341382, Accuracy: 0.3768, Precision: 0.2681, Recall: 0.3768, F1 Score: 0.2248, AUC: 0.4881, R2 Score: -21.914226, MAE: 10.3150, MSE: 111.2527
Training: Fold 4 - Total Loss: 34.9953, Cross Entropy: 1.333024, Accuracy: 0.4155, Precision: 0.2661, Recall: 0.4155, F1 Score: 0.2607, AUC: 0.5153, R2 Score: -20.392709, MAE: 10.4033, MSE: 113.5405
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 2.41, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 34.5353, Cross Entropy: 1.338120, Accuracy: 0.3891, Precision: 0.2222, Recall: 0.3891, F1 Score: 0.2405, AUC: 0.4624, R2 Score: -20.378105, MAE: 10.3338, MSE: 111.9955
Training: Fold 2 - Total Loss: 34.4834, Cross Entropy: 1.334800, Accuracy: 0.4120, Precision: 0.3616, Recall: 0.4120, F1 Score: 0.2613, AUC: 0.5089, R2 Score: -21.558385, MAE: 10.3391, MSE: 111.8300
Training: Fold 3 - Total Loss: 34.2495, Cross Entropy: 1.345410, Accuracy: 0.3838, Precision: 0.3032, Recall: 0.3838, F1 Score: 0.2384, AUC: 0.4656, R2 Score: -21.915532, MAE: 10.3031, MSE: 111.0257
Training: Fold 4 - Total Loss: 34.9238, Cross Entropy: 1.336177, Accuracy: 0.4085, Precision: 0.2281, Recall: 0.4085, F1 Score: 0.2521, AUC: 0.4953, R2 Score: -20.380720, MAE: 10.3919, MSE: 113.2951
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 2.81, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.5056, Cross Entropy: 1.333486, Accuracy: 0.4049, Precision: 0.2761, Recall: 0.4049, F1 Score: 0.2533, AUC: 0.5046, R2 Score: -20.377642, MAE: 10.3290, MSE: 111.9073
Training: Fold 2 - Total Loss: 34.4205, Cross Entropy: 1.336170, Accuracy: 0.3996, Precision: 0.2034, Recall: 0.3996, F1 Score: 0.2391, AUC: 0.4992, R2 Score: -21.553800, MAE: 10.3270, MSE: 111.6173
Training: Fold 3 - Total Loss: 34.2847, Cross Entropy: 1.342391, Accuracy: 0.3785, Precision: 0.2593, Recall: 0.3785, F1 Score: 0.2364, AUC: 0.4960, R2 Score: -21.923938, MAE: 10.3101, MSE: 111.1501
Training: Fold 4 - Total Loss: 34.8702, Cross Entropy: 1.334360, Accuracy: 0.4102, Precision: 0.2554, Recall: 0.4102, F1 Score: 0.2549, AUC: 0.5247, R2 Score: -20.372440, MAE: 10.3824, MSE: 113.1205
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 2.52, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.4561, Cross Entropy: 1.331630, Accuracy: 0.4067, Precision: 0.2816, Recall: 0.4067, F1 Score: 0.2595, AUC: 0.5251, R2 Score: -20.368559, MAE: 10.3213, MSE: 111.7464
Training: Fold 2 - Total Loss: 34.4778, Cross Entropy: 1.335462, Accuracy: 0.3979, Precision: 0.2585, Recall: 0.3979, F1 Score: 0.2446, AUC: 0.5042, R2 Score: -21.558125, MAE: 10.3377, MSE: 111.8098
Training: Fold 3 - Total Loss: 34.3285, Cross Entropy: 1.342394, Accuracy: 0.3785, Precision: 0.3092, Recall: 0.3785, F1 Score: 0.2303, AUC: 0.5163, R2 Score: -21.905703, MAE: 10.3169, MSE: 111.2961
Training: Fold 4 - Total Loss: 34.9175, Cross Entropy: 1.335965, Accuracy: 0.4085, Precision: 0.2312, Recall: 0.4085, F1 Score: 0.2519, AUC: 0.4988, R2 Score: -20.376395, MAE: 10.3903, MSE: 113.2743
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 2.60, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.4349, Cross Entropy: 1.334155, Accuracy: 0.4102, Precision: 0.2994, Recall: 0.4102, F1 Score: 0.2611, AUC: 0.4982, R2 Score: -20.371145, MAE: 10.3164, MSE: 111.6700
Training: Fold 2 - Total Loss: 34.4942, Cross Entropy: 1.333589, Accuracy: 0.3944, Precision: 0.2057, Recall: 0.3944, F1 Score: 0.2354, AUC: 0.5158, R2 Score: -21.565192, MAE: 10.3393, MSE: 111.8689
Training: Fold 3 - Total Loss: 34.3590, Cross Entropy: 1.342228, Accuracy: 0.3768, Precision: 0.2546, Recall: 0.3768, F1 Score: 0.2223, AUC: 0.5136, R2 Score: -21.913794, MAE: 10.3218, MSE: 111.3980
Training: Fold 4 - Total Loss: 34.9889, Cross Entropy: 1.332751, Accuracy: 0.4085, Precision: 0.2539, Recall: 0.4085, F1 Score: 0.2599, AUC: 0.5224, R2 Score: -20.369268, MAE: 10.4013, MSE: 113.5200
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 3.19, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.5068, Cross Entropy: 1.334977, Accuracy: 0.4049, Precision: 0.2494, Recall: 0.4049, F1 Score: 0.2456, AUC: 0.4899, R2 Score: -20.378576, MAE: 10.3285, MSE: 111.9076
Training: Fold 2 - Total Loss: 34.4809, Cross Entropy: 1.334999, Accuracy: 0.4032, Precision: 0.3032, Recall: 0.4032, F1 Score: 0.2571, AUC: 0.4998, R2 Score: -21.560535, MAE: 10.3373, MSE: 111.8215
Training: Fold 3 - Total Loss: 34.2941, Cross Entropy: 1.342288, Accuracy: 0.3680, Precision: 0.2005, Recall: 0.3680, F1 Score: 0.2133, AUC: 0.5135, R2 Score: -21.917671, MAE: 10.3110, MSE: 111.1816
Training: Fold 4 - Total Loss: 34.8885, Cross Entropy: 1.335885, Accuracy: 0.4137, Precision: 0.2728, Recall: 0.4137, F1 Score: 0.2649, AUC: 0.5028, R2 Score: -20.373894, MAE: 10.3847, MSE: 113.1780
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 2.32, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.4493, Cross Entropy: 1.332334, Accuracy: 0.3979, Precision: 0.2345, Recall: 0.3979, F1 Score: 0.2450, AUC: 0.4930, R2 Score: -20.384490, MAE: 10.3181, MSE: 111.7224
Training: Fold 2 - Total Loss: 34.4135, Cross Entropy: 1.335851, Accuracy: 0.3979, Precision: 0.2821, Recall: 0.3979, F1 Score: 0.2494, AUC: 0.5036, R2 Score: -21.554930, MAE: 10.3263, MSE: 111.5946
Training: Fold 3 - Total Loss: 34.3136, Cross Entropy: 1.342592, Accuracy: 0.3680, Precision: 0.2056, Recall: 0.3680, F1 Score: 0.2163, AUC: 0.5048, R2 Score: -21.913657, MAE: 10.3147, MSE: 111.2460
Training: Fold 4 - Total Loss: 35.0023, Cross Entropy: 1.334412, Accuracy: 0.4137, Precision: 0.2768, Recall: 0.4137, F1 Score: 0.2592, AUC: 0.4969, R2 Score: -20.376825, MAE: 10.4059, MSE: 113.5608
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 3.37, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.4714, Cross Entropy: 1.333860, Accuracy: 0.4085, Precision: 0.3015, Recall: 0.4085, F1 Score: 0.2625, AUC: 0.5055, R2 Score: -20.386672, MAE: 10.3235, MSE: 111.7923
Training: Fold 2 - Total Loss: 34.5482, Cross Entropy: 1.337484, Accuracy: 0.3979, Precision: 0.2626, Recall: 0.3979, F1 Score: 0.2415, AUC: 0.4894, R2 Score: -21.572143, MAE: 10.3469, MSE: 112.0399
Training: Fold 3 - Total Loss: 34.3181, Cross Entropy: 1.342968, Accuracy: 0.3662, Precision: 0.1629, Recall: 0.3662, F1 Score: 0.2076, AUC: 0.5035, R2 Score: -21.914418, MAE: 10.3162, MSE: 111.2601
Training: Fold 4 - Total Loss: 35.0023, Cross Entropy: 1.335044, Accuracy: 0.3944, Precision: 0.2111, Recall: 0.3944, F1 Score: 0.2449, AUC: 0.5194, R2 Score: -20.373609, MAE: 10.4033, MSE: 113.5591
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 2.99, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.4080, Cross Entropy: 1.333299, Accuracy: 0.4155, Precision: 0.3414, Recall: 0.4155, F1 Score: 0.2684, AUC: 0.5092, R2 Score: -20.366227, MAE: 10.3121, MSE: 111.5824
Training: Fold 2 - Total Loss: 34.4294, Cross Entropy: 1.334084, Accuracy: 0.4032, Precision: 0.2607, Recall: 0.4032, F1 Score: 0.2477, AUC: 0.5180, R2 Score: -21.556919, MAE: 10.3290, MSE: 111.6517
Training: Fold 3 - Total Loss: 34.3053, Cross Entropy: 1.342348, Accuracy: 0.3785, Precision: 0.2426, Recall: 0.3785, F1 Score: 0.2237, AUC: 0.5209, R2 Score: -21.922973, MAE: 10.3137, MSE: 111.2188
Training: Fold 4 - Total Loss: 35.0339, Cross Entropy: 1.337230, Accuracy: 0.4120, Precision: 0.2562, Recall: 0.4120, F1 Score: 0.2559, AUC: 0.4759, R2 Score: -20.375549, MAE: 10.4092, MSE: 113.6595
Validation: Fold 5 - Total Loss: 35.1876, Cross Entropy: 1.362463, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -21.085575, MAE: 10.4348, MSE: 114.1128
Avg Latency (ms): 3.03, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 9.79 MB
====================================================================================================

In [104]:
main("resnet18", EPOCHS=10)

====================================================================================================
Training Model: resnet18
Initial Backbone Model Size: 46.83 MB
Modified Backbone Model Size: 45.04 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 33.4075, Cross Entropy: 1.370543, Accuracy: 0.3944, Precision: 0.1781, Recall: 0.3944, F1 Score: 0.2438, AUC: 0.5408, R2 Score: -19.678282, MAE: 10.1466, MSE: 108.1605
Training: Fold 2 - Total Loss: 33.3319, Cross Entropy: 1.383091, Accuracy: 0.3732, Precision: 0.1663, Recall: 0.3732, F1 Score: 0.2296, AUC: 0.4952, R2 Score: -20.818493, MAE: 10.1445, MSE: 107.8791
Training: Fold 3 - Total Loss: 33.2922, Cross Entropy: 1.386819, Accuracy: 0.3504, Precision: 0.1490, Recall: 0.3504, F1 Score: 0.2083, AUC: 0.5152, R2 Score: -21.177077, MAE: 10.1432, MSE: 107.7379
Training: Fold 4 - Total Loss: 33.9469, Cross Entropy: 1.371180, Accuracy: 0.3944, Precision: 0.5892, Recall: 0.3944, F1 Score: 0.2520, AUC: 0.5293, R2 Score: -19.678488, MAE: 10.2297, MSE: 109.9570
Validation: Fold 5 - Total Loss: 34.4076, Cross Entropy: 1.340247, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5788, R2 Score: -20.587716, MAE: 10.3123, MSE: 111.5648
Avg Latency (ms): 3.33, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3873

Epoch 2/10
Training: Fold 1 - Total Loss: 33.4355, Cross Entropy: 1.377254, Accuracy: 0.3750, Precision: 0.1697, Recall: 0.3750, F1 Score: 0.2331, AUC: 0.4916, R2 Score: -19.680350, MAE: 10.1493, MSE: 108.2380
Training: Fold 2 - Total Loss: 33.4719, Cross Entropy: 1.379733, Accuracy: 0.3803, Precision: 0.1692, Recall: 0.3803, F1 Score: 0.2335, AUC: 0.5245, R2 Score: -20.854872, MAE: 10.1689, MSE: 108.3537
Training: Fold 3 - Total Loss: 33.3004, Cross Entropy: 1.388346, Accuracy: 0.3468, Precision: 0.1449, Recall: 0.3468, F1 Score: 0.2042, AUC: 0.5067, R2 Score: -21.171445, MAE: 10.1454, MSE: 107.7619
Training: Fold 4 - Total Loss: 33.9310, Cross Entropy: 1.374174, Accuracy: 0.3838, Precision: 0.1775, Recall: 0.3838, F1 Score: 0.2427, AUC: 0.4958, R2 Score: -19.691353, MAE: 10.2251, MSE: 109.8971
Validation: Fold 5 - Total Loss: 34.3966, Cross Entropy: 1.340678, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5376, R2 Score: -20.581592, MAE: 10.3106, MSE: 111.5272
Avg Latency (ms): 1.78, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 33.3351, Cross Entropy: 1.373351, Accuracy: 0.3785, Precision: 0.2992, Recall: 0.3785, F1 Score: 0.2404, AUC: 0.5389, R2 Score: -19.667675, MAE: 10.1337, MSE: 107.9125
Training: Fold 2 - Total Loss: 33.4153, Cross Entropy: 1.375350, Accuracy: 0.3715, Precision: 0.1647, Recall: 0.3715, F1 Score: 0.2278, AUC: 0.5185, R2 Score: -20.821638, MAE: 10.1590, MSE: 108.1751
Training: Fold 3 - Total Loss: 33.2894, Cross Entropy: 1.390890, Accuracy: 0.3521, Precision: 0.1502, Recall: 0.3521, F1 Score: 0.2101, AUC: 0.5031, R2 Score: -21.179521, MAE: 10.1421, MSE: 107.7192
Training: Fold 4 - Total Loss: 33.8879, Cross Entropy: 1.371266, Accuracy: 0.3961, Precision: 0.1804, Recall: 0.3961, F1 Score: 0.2474, AUC: 0.5133, R2 Score: -19.685796, MAE: 10.2192, MSE: 109.7600
Validation: Fold 5 - Total Loss: 34.4024, Cross Entropy: 1.342159, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4809, R2 Score: -20.583965, MAE: 10.3113, MSE: 111.5431
Avg Latency (ms): 1.81, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 33.4675, Cross Entropy: 1.376094, Accuracy: 0.3732, Precision: 0.2668, Recall: 0.3732, F1 Score: 0.2361, AUC: 0.5227, R2 Score: -19.705095, MAE: 10.1543, MSE: 108.3475
Training: Fold 2 - Total Loss: 33.4198, Cross Entropy: 1.373384, Accuracy: 0.3820, Precision: 0.1694, Recall: 0.3820, F1 Score: 0.2343, AUC: 0.5471, R2 Score: -20.812743, MAE: 10.1598, MSE: 108.1949
Training: Fold 3 - Total Loss: 33.2991, Cross Entropy: 1.386082, Accuracy: 0.3521, Precision: 0.1496, Recall: 0.3521, F1 Score: 0.2093, AUC: 0.5098, R2 Score: -21.198630, MAE: 10.1450, MSE: 107.7628
Training: Fold 4 - Total Loss: 33.9464, Cross Entropy: 1.370339, Accuracy: 0.3926, Precision: 0.1839, Recall: 0.3926, F1 Score: 0.2500, AUC: 0.5213, R2 Score: -19.670953, MAE: 10.2303, MSE: 109.9571
Validation: Fold 5 - Total Loss: 34.3895, Cross Entropy: 1.341780, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5345, R2 Score: -20.575238, MAE: 10.3092, MSE: 111.5007
Avg Latency (ms): 1.10, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 33.3952, Cross Entropy: 1.371920, Accuracy: 0.3856, Precision: 0.3953, Recall: 0.3856, F1 Score: 0.2473, AUC: 0.5258, R2 Score: -19.683757, MAE: 10.1438, MSE: 108.1163
Training: Fold 2 - Total Loss: 33.4234, Cross Entropy: 1.379817, Accuracy: 0.3768, Precision: 0.1706, Recall: 0.3768, F1 Score: 0.2344, AUC: 0.5325, R2 Score: -20.830694, MAE: 10.1599, MSE: 108.1917
Training: Fold 3 - Total Loss: 33.2760, Cross Entropy: 1.388565, Accuracy: 0.3486, Precision: 0.3164, Recall: 0.3486, F1 Score: 0.2118, AUC: 0.5122, R2 Score: -21.195403, MAE: 10.1409, MSE: 107.6801
Training: Fold 4 - Total Loss: 33.8600, Cross Entropy: 1.366926, Accuracy: 0.3944, Precision: 0.1843, Recall: 0.3944, F1 Score: 0.2505, AUC: 0.5410, R2 Score: -19.691290, MAE: 10.2148, MSE: 109.6772
Validation: Fold 5 - Total Loss: 34.3983, Cross Entropy: 1.342099, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5133, R2 Score: -20.580884, MAE: 10.3105, MSE: 111.5295
Avg Latency (ms): 0.95, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 33.4558, Cross Entropy: 1.375648, Accuracy: 0.3908, Precision: 0.1778, Recall: 0.3908, F1 Score: 0.2436, AUC: 0.5094, R2 Score: -19.692775, MAE: 10.1526, MSE: 108.3096
Training: Fold 2 - Total Loss: 33.4798, Cross Entropy: 1.379429, Accuracy: 0.3732, Precision: 0.1669, Recall: 0.3732, F1 Score: 0.2303, AUC: 0.5247, R2 Score: -20.875833, MAE: 10.1703, MSE: 108.3808
Training: Fold 3 - Total Loss: 33.2618, Cross Entropy: 1.387787, Accuracy: 0.3345, Precision: 0.3616, Recall: 0.3345, F1 Score: 0.2052, AUC: 0.5261, R2 Score: -21.175610, MAE: 10.1371, MSE: 107.6344
Training: Fold 4 - Total Loss: 33.9052, Cross Entropy: 1.368627, Accuracy: 0.3838, Precision: 0.1792, Recall: 0.3838, F1 Score: 0.2439, AUC: 0.5332, R2 Score: -19.678073, MAE: 10.2226, MSE: 109.8239
Validation: Fold 5 - Total Loss: 34.4065, Cross Entropy: 1.341680, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5430, R2 Score: -20.586404, MAE: 10.3119, MSE: 111.5577
Avg Latency (ms): 1.09, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 33.4827, Cross Entropy: 1.376615, Accuracy: 0.3715, Precision: 0.1701, Recall: 0.3715, F1 Score: 0.2331, AUC: 0.5146, R2 Score: -19.690107, MAE: 10.1559, MSE: 108.3970
Training: Fold 2 - Total Loss: 33.4437, Cross Entropy: 1.380616, Accuracy: 0.3715, Precision: 0.1654, Recall: 0.3715, F1 Score: 0.2284, AUC: 0.5145, R2 Score: -20.860883, MAE: 10.1642, MSE: 108.2574
Training: Fold 3 - Total Loss: 33.2971, Cross Entropy: 1.383003, Accuracy: 0.3486, Precision: 0.1457, Recall: 0.3486, F1 Score: 0.2052, AUC: 0.5456, R2 Score: -21.173558, MAE: 10.1454, MSE: 107.7633
Training: Fold 4 - Total Loss: 33.9289, Cross Entropy: 1.376155, Accuracy: 0.3732, Precision: 0.1724, Recall: 0.3732, F1 Score: 0.2357, AUC: 0.4977, R2 Score: -19.687193, MAE: 10.2263, MSE: 109.8852
Validation: Fold 5 - Total Loss: 34.3967, Cross Entropy: 1.340987, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5471, R2 Score: -20.582219, MAE: 10.3106, MSE: 111.5266
Avg Latency (ms): 1.02, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 33.3572, Cross Entropy: 1.368400, Accuracy: 0.3891, Precision: 0.1724, Recall: 0.3891, F1 Score: 0.2382, AUC: 0.5361, R2 Score: -19.678224, MAE: 10.1369, MSE: 107.9976
Training: Fold 2 - Total Loss: 33.5288, Cross Entropy: 1.383310, Accuracy: 0.3820, Precision: 0.4976, Recall: 0.3820, F1 Score: 0.2367, AUC: 0.4883, R2 Score: -20.842157, MAE: 10.1767, MSE: 108.5350
Training: Fold 3 - Total Loss: 33.2303, Cross Entropy: 1.381307, Accuracy: 0.3451, Precision: 0.1469, Recall: 0.3451, F1 Score: 0.2059, AUC: 0.5332, R2 Score: -21.195718, MAE: 10.1316, MSE: 107.5447
Training: Fold 4 - Total Loss: 33.8889, Cross Entropy: 1.376446, Accuracy: 0.3926, Precision: 0.1796, Recall: 0.3926, F1 Score: 0.2456, AUC: 0.5075, R2 Score: -19.700061, MAE: 10.2204, MSE: 109.7511
Validation: Fold 5 - Total Loss: 34.3933, Cross Entropy: 1.340180, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5465, R2 Score: -20.580684, MAE: 10.3103, MSE: 111.5171
Avg Latency (ms): 0.86, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 33.4150, Cross Entropy: 1.370931, Accuracy: 0.3592, Precision: 0.1659, Recall: 0.3592, F1 Score: 0.2268, AUC: 0.5467, R2 Score: -19.673118, MAE: 10.1444, MSE: 108.1845
Training: Fold 2 - Total Loss: 33.3855, Cross Entropy: 1.383879, Accuracy: 0.3697, Precision: 0.1638, Recall: 0.3697, F1 Score: 0.2267, AUC: 0.4846, R2 Score: -20.800452, MAE: 10.1549, MSE: 108.0558
Training: Fold 3 - Total Loss: 33.3175, Cross Entropy: 1.385507, Accuracy: 0.3363, Precision: 0.1442, Recall: 0.3363, F1 Score: 0.2017, AUC: 0.5158, R2 Score: -21.176145, MAE: 10.1479, MSE: 107.8254
Training: Fold 4 - Total Loss: 33.9476, Cross Entropy: 1.361161, Accuracy: 0.3961, Precision: 0.3366, Recall: 0.3961, F1 Score: 0.2509, AUC: 0.5566, R2 Score: -19.701614, MAE: 10.2311, MSE: 109.9826
Validation: Fold 5 - Total Loss: 34.4006, Cross Entropy: 1.340593, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5622, R2 Score: -20.583749, MAE: 10.3111, MSE: 111.5405
Avg Latency (ms): 0.84, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 33.4892, Cross Entropy: 1.375454, Accuracy: 0.3856, Precision: 0.1774, Recall: 0.3856, F1 Score: 0.2426, AUC: 0.5207, R2 Score: -19.712639, MAE: 10.1548, MSE: 108.4212
Training: Fold 2 - Total Loss: 33.4044, Cross Entropy: 1.381444, Accuracy: 0.3644, Precision: 0.4924, Recall: 0.3644, F1 Score: 0.2316, AUC: 0.4959, R2 Score: -20.830736, MAE: 10.1563, MSE: 108.1247
Training: Fold 3 - Total Loss: 33.2977, Cross Entropy: 1.385870, Accuracy: 0.3539, Precision: 0.1508, Recall: 0.3539, F1 Score: 0.2111, AUC: 0.5350, R2 Score: -21.178188, MAE: 10.1433, MSE: 107.7586
Training: Fold 4 - Total Loss: 33.9186, Cross Entropy: 1.368284, Accuracy: 0.3908, Precision: 0.2816, Recall: 0.3908, F1 Score: 0.2503, AUC: 0.5410, R2 Score: -19.695141, MAE: 10.2263, MSE: 109.8692
Validation: Fold 5 - Total Loss: 34.3965, Cross Entropy: 1.340963, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5264, R2 Score: -20.580822, MAE: 10.3106, MSE: 111.5262
Avg Latency (ms): 1.10, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 45.05 MB
====================================================================================================

In [105]:
main("densenet121", EPOCHS=10)

====================================================================================================
Training Model: densenet121
Initial Backbone Model Size: 32.47 MB
Modified Backbone Model Size: 28.90 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 33.2751, Cross Entropy: 1.397721, Accuracy: 0.2306, Precision: 0.2947, Recall: 0.2306, F1 Score: 0.2353, AUC: 0.4715, R2 Score: -19.553164, MAE: 10.1214, MSE: 107.6557
Training: Fold 2 - Total Loss: 33.2779, Cross Entropy: 1.397159, Accuracy: 0.1989, Precision: 0.2664, Recall: 0.1989, F1 Score: 0.2059, AUC: 0.4909, R2 Score: -20.709124, MAE: 10.1342, MSE: 107.6662
Training: Fold 3 - Total Loss: 33.1490, Cross Entropy: 1.393777, Accuracy: 0.2271, Precision: 0.2949, Recall: 0.2271, F1 Score: 0.2376, AUC: 0.4923, R2 Score: -21.030192, MAE: 10.1202, MSE: 107.2446
Training: Fold 4 - Total Loss: 33.7163, Cross Entropy: 1.395832, Accuracy: 0.2148, Precision: 0.2715, Recall: 0.2148, F1 Score: 0.2236, AUC: 0.4766, R2 Score: -19.565458, MAE: 10.1899, MSE: 109.1306
Validation: Fold 5 - Total Loss: 35.0686, Cross Entropy: 1.474448, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4962, R2 Score: -20.956926, MAE: 10.4036, MSE: 113.4549
Avg Latency (ms): 13.10, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.2324

Epoch 2/10
Training: Fold 1 - Total Loss: 33.2838, Cross Entropy: 1.396076, Accuracy: 0.2218, Precision: 0.2994, Recall: 0.2218, F1 Score: 0.2360, AUC: 0.4862, R2 Score: -19.586789, MAE: 10.1220, MSE: 107.6886
Training: Fold 2 - Total Loss: 33.2168, Cross Entropy: 1.397037, Accuracy: 0.2236, Precision: 0.2704, Recall: 0.2236, F1 Score: 0.2242, AUC: 0.4907, R2 Score: -20.702716, MAE: 10.1254, MSE: 107.4629
Training: Fold 3 - Total Loss: 33.1600, Cross Entropy: 1.396093, Accuracy: 0.2113, Precision: 0.2775, Recall: 0.2113, F1 Score: 0.2237, AUC: 0.4898, R2 Score: -21.034923, MAE: 10.1206, MSE: 107.2758
Training: Fold 4 - Total Loss: 33.6887, Cross Entropy: 1.396168, Accuracy: 0.2077, Precision: 0.2843, Recall: 0.2077, F1 Score: 0.2169, AUC: 0.4718, R2 Score: -19.568028, MAE: 10.1832, MSE: 109.0381
Validation: Fold 5 - Total Loss: 35.0678, Cross Entropy: 1.474288, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4857, R2 Score: -20.955362, MAE: 10.4034, MSE: 113.4526
Avg Latency (ms): 6.55, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 33.2633, Cross Entropy: 1.395940, Accuracy: 0.2042, Precision: 0.2589, Recall: 0.2042, F1 Score: 0.2135, AUC: 0.4835, R2 Score: -19.559701, MAE: 10.1203, MSE: 107.6203
Training: Fold 2 - Total Loss: 33.3119, Cross Entropy: 1.395954, Accuracy: 0.2165, Precision: 0.2698, Recall: 0.2165, F1 Score: 0.2191, AUC: 0.4943, R2 Score: -20.708057, MAE: 10.1408, MSE: 107.7824
Training: Fold 3 - Total Loss: 33.1255, Cross Entropy: 1.396363, Accuracy: 0.2306, Precision: 0.3105, Recall: 0.2306, F1 Score: 0.2381, AUC: 0.5021, R2 Score: -21.047656, MAE: 10.1139, MSE: 107.1602
Training: Fold 4 - Total Loss: 33.7366, Cross Entropy: 1.394110, Accuracy: 0.2342, Precision: 0.3239, Recall: 0.2342, F1 Score: 0.2498, AUC: 0.4897, R2 Score: -19.560175, MAE: 10.1929, MSE: 109.2023
Validation: Fold 5 - Total Loss: 35.0698, Cross Entropy: 1.474462, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4912, R2 Score: -20.956923, MAE: 10.4039, MSE: 113.4589
Avg Latency (ms): 6.66, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 33.2373, Cross Entropy: 1.396349, Accuracy: 0.2130, Precision: 0.2763, Recall: 0.2130, F1 Score: 0.2186, AUC: 0.4811, R2 Score: -19.565894, MAE: 10.1165, MSE: 107.5327
Training: Fold 2 - Total Loss: 33.2923, Cross Entropy: 1.392827, Accuracy: 0.2377, Precision: 0.3114, Recall: 0.2377, F1 Score: 0.2478, AUC: 0.5171, R2 Score: -20.704299, MAE: 10.1375, MSE: 107.7243
Training: Fold 3 - Total Loss: 33.0999, Cross Entropy: 1.394986, Accuracy: 0.2254, Precision: 0.2822, Recall: 0.2254, F1 Score: 0.2242, AUC: 0.5106, R2 Score: -21.029197, MAE: 10.1104, MSE: 107.0779
Training: Fold 4 - Total Loss: 33.7630, Cross Entropy: 1.396060, Accuracy: 0.2165, Precision: 0.2762, Recall: 0.2165, F1 Score: 0.2273, AUC: 0.4813, R2 Score: -19.573060, MAE: 10.1974, MSE: 109.2857
Validation: Fold 5 - Total Loss: 35.0657, Cross Entropy: 1.473855, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.5063, R2 Score: -20.954382, MAE: 10.4033, MSE: 113.4467
Avg Latency (ms): 6.46, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 33.2229, Cross Entropy: 1.397895, Accuracy: 0.2148, Precision: 0.2745, Recall: 0.2148, F1 Score: 0.2223, AUC: 0.4608, R2 Score: -19.559948, MAE: 10.1132, MSE: 107.4811
Training: Fold 2 - Total Loss: 33.2405, Cross Entropy: 1.397579, Accuracy: 0.2306, Precision: 0.2698, Recall: 0.2306, F1 Score: 0.2321, AUC: 0.4795, R2 Score: -20.716581, MAE: 10.1279, MSE: 107.5405
Training: Fold 3 - Total Loss: 33.0753, Cross Entropy: 1.397866, Accuracy: 0.2130, Precision: 0.2694, Recall: 0.2130, F1 Score: 0.2179, AUC: 0.4686, R2 Score: -21.046333, MAE: 10.1069, MSE: 106.9892
Training: Fold 4 - Total Loss: 33.7507, Cross Entropy: 1.394985, Accuracy: 0.2518, Precision: 0.3388, Recall: 0.2518, F1 Score: 0.2598, AUC: 0.4927, R2 Score: -19.575379, MAE: 10.1954, MSE: 109.2475
Validation: Fold 5 - Total Loss: 35.0723, Cross Entropy: 1.473972, Accuracy: 0.2324, Precision: 0.0544, Recall: 0.2324, F1 Score: 0.0881, AUC: 0.4849, R2 Score: -20.957861, MAE: 10.4042, MSE: 113.4682
Avg Latency (ms): 6.47, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 33.2193, Cross Entropy: 1.395680, Accuracy: 0.2306, Precision: 0.2860, Recall: 0.2306, F1 Score: 0.2355, AUC: 0.4908, R2 Score: -19.561493, MAE: 10.1123, MSE: 107.4744
Training: Fold 2 - Total Loss: 33.3044, Cross Entropy: 1.395365, Accuracy: 0.2306, Precision: 0.3015, Recall: 0.2306, F1 Score: 0.2435, AUC: 0.4804, R2 Score: -20.699879, MAE: 10.1380, MSE: 107.7587
Training: Fold 3 - Total Loss: 33.1000, Cross Entropy: 1.394606, Accuracy: 0.2130, Precision: 0.2813, Recall: 0.2130, F1 Score: 0.2263, AUC: 0.4806, R2 Score: -21.033037, MAE: 10.1112, MSE: 107.0792
Training: Fold 4 - Total Loss: 33.7693, Cross Entropy: 1.393103, Accuracy: 0.2130, Precision: 0.2688, Recall: 0.2130, F1 Score: 0.2200, AUC: 0.4943, R2 Score: -19.564345, MAE: 10.1994, MSE: 109.3138
Validation: Fold 5 - Total Loss: 35.0705, Cross Entropy: 1.474052, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4887, R2 Score: -20.957487, MAE: 10.4040, MSE: 113.4623
Avg Latency (ms): 6.71, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 33.2309, Cross Entropy: 1.396150, Accuracy: 0.2165, Precision: 0.2882, Recall: 0.2165, F1 Score: 0.2306, AUC: 0.4879, R2 Score: -19.554303, MAE: 10.1150, MSE: 107.5119
Training: Fold 2 - Total Loss: 33.2728, Cross Entropy: 1.394260, Accuracy: 0.2535, Precision: 0.3306, Recall: 0.2535, F1 Score: 0.2619, AUC: 0.5158, R2 Score: -20.726263, MAE: 10.1344, MSE: 107.6560
Training: Fold 3 - Total Loss: 33.0275, Cross Entropy: 1.394582, Accuracy: 0.2289, Precision: 0.2968, Recall: 0.2289, F1 Score: 0.2358, AUC: 0.4935, R2 Score: -21.036693, MAE: 10.0970, MSE: 106.8377
Training: Fold 4 - Total Loss: 33.7753, Cross Entropy: 1.395252, Accuracy: 0.2201, Precision: 0.3048, Recall: 0.2201, F1 Score: 0.2354, AUC: 0.4748, R2 Score: -19.566339, MAE: 10.1990, MSE: 109.3287
Validation: Fold 5 - Total Loss: 35.0668, Cross Entropy: 1.473823, Accuracy: 0.2324, Precision: 0.0544, Recall: 0.2324, F1 Score: 0.0881, AUC: 0.5004, R2 Score: -20.955864, MAE: 10.4034, MSE: 113.4503
Avg Latency (ms): 6.25, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 33.2495, Cross Entropy: 1.398161, Accuracy: 0.1849, Precision: 0.2686, Recall: 0.1849, F1 Score: 0.1960, AUC: 0.4684, R2 Score: -19.558252, MAE: 10.1168, MSE: 107.5693
Training: Fold 2 - Total Loss: 33.2411, Cross Entropy: 1.394979, Accuracy: 0.2254, Precision: 0.2902, Recall: 0.2254, F1 Score: 0.2309, AUC: 0.4890, R2 Score: -20.699417, MAE: 10.1268, MSE: 107.5487
Training: Fold 3 - Total Loss: 33.0607, Cross Entropy: 1.396412, Accuracy: 0.2236, Precision: 0.3000, Recall: 0.2236, F1 Score: 0.2384, AUC: 0.4881, R2 Score: -21.032987, MAE: 10.1042, MSE: 106.9441
Training: Fold 4 - Total Loss: 33.8171, Cross Entropy: 1.397343, Accuracy: 0.2218, Precision: 0.2866, Recall: 0.2218, F1 Score: 0.2302, AUC: 0.4716, R2 Score: -19.571226, MAE: 10.2059, MSE: 109.4631
Validation: Fold 5 - Total Loss: 35.0699, Cross Entropy: 1.474103, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4865, R2 Score: -20.956674, MAE: 10.4039, MSE: 113.4602
Avg Latency (ms): 6.19, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 33.1685, Cross Entropy: 1.395765, Accuracy: 0.2289, Precision: 0.2716, Recall: 0.2289, F1 Score: 0.2297, AUC: 0.4962, R2 Score: -19.544020, MAE: 10.1026, MSE: 107.3050
Training: Fold 2 - Total Loss: 33.2629, Cross Entropy: 1.393246, Accuracy: 0.2095, Precision: 0.2894, Recall: 0.2095, F1 Score: 0.2231, AUC: 0.4998, R2 Score: -20.710556, MAE: 10.1339, MSE: 107.6253
Training: Fold 3 - Total Loss: 33.0670, Cross Entropy: 1.398615, Accuracy: 0.2130, Precision: 0.2894, Recall: 0.2130, F1 Score: 0.2244, AUC: 0.4628, R2 Score: -21.051925, MAE: 10.1036, MSE: 106.9599
Training: Fold 4 - Total Loss: 33.7053, Cross Entropy: 1.396088, Accuracy: 0.2201, Precision: 0.2731, Recall: 0.2201, F1 Score: 0.2252, AUC: 0.4730, R2 Score: -19.563617, MAE: 10.1872, MSE: 109.0934
Validation: Fold 5 - Total Loss: 35.0676, Cross Entropy: 1.474169, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4812, R2 Score: -20.955792, MAE: 10.4036, MSE: 113.4523
Avg Latency (ms): 6.69, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 33.2235, Cross Entropy: 1.396480, Accuracy: 0.2095, Precision: 0.2654, Recall: 0.2095, F1 Score: 0.2134, AUC: 0.4813, R2 Score: -19.553894, MAE: 10.1133, MSE: 107.4866
Training: Fold 2 - Total Loss: 33.2322, Cross Entropy: 1.398569, Accuracy: 0.2042, Precision: 0.2669, Recall: 0.2042, F1 Score: 0.2130, AUC: 0.4622, R2 Score: -20.702688, MAE: 10.1267, MSE: 107.5107
Training: Fold 3 - Total Loss: 33.0709, Cross Entropy: 1.396829, Accuracy: 0.2130, Precision: 0.2799, Recall: 0.2130, F1 Score: 0.2228, AUC: 0.4831, R2 Score: -21.055604, MAE: 10.1061, MSE: 106.9772
Training: Fold 4 - Total Loss: 33.7298, Cross Entropy: 1.396492, Accuracy: 0.2148, Precision: 0.3043, Recall: 0.2148, F1 Score: 0.2292, AUC: 0.4573, R2 Score: -19.554997, MAE: 10.1914, MSE: 109.1741
Validation: Fold 5 - Total Loss: 35.0683, Cross Entropy: 1.473690, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.5004, R2 Score: -20.955816, MAE: 10.4036, MSE: 113.4559
Avg Latency (ms): 6.63, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 28.91 MB
====================================================================================================

In [106]:
main("vgg16", EPOCHS=10)

====================================================================================================
Training Model: vgg16
Initial Backbone Model Size: 553.44 MB
Modified Backbone Model Size: 71.72 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.4692, Cross Entropy: 1.401370, Accuracy: 0.2077, Precision: 0.2247, Recall: 0.2077, F1 Score: 0.2001, AUC: 0.4952, R2 Score: -20.339274, MAE: 10.3127, MSE: 111.6275
Training: Fold 2 - Total Loss: 34.4082, Cross Entropy: 1.402654, Accuracy: 0.2183, Precision: 0.2269, Recall: 0.2183, F1 Score: 0.2020, AUC: 0.5112, R2 Score: -21.523038, MAE: 10.3179, MSE: 111.4211
Training: Fold 3 - Total Loss: 34.2718, Cross Entropy: 1.402558, Accuracy: 0.2042, Precision: 0.2309, Recall: 0.2042, F1 Score: 0.1991, AUC: 0.5129, R2 Score: -21.872463, MAE: 10.2998, MSE: 110.9666
Training: Fold 4 - Total Loss: 34.9818, Cross Entropy: 1.398391, Accuracy: 0.2007, Precision: 0.2349, Recall: 0.2007, F1 Score: 0.2021, AUC: 0.4966, R2 Score: -20.342561, MAE: 10.3932, MSE: 113.3430
Validation: Fold 5 - Total Loss: 35.6510, Cross Entropy: 1.396611, Accuracy: 0.1549, Precision: 0.1482, Recall: 0.1549, F1 Score: 0.1266, AUC: 0.5349, R2 Score: -21.372253, MAE: 10.5047, MSE: 115.5780
Avg Latency (ms): 1.94, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.1549

Epoch 2/10
Training: Fold 1 - Total Loss: 34.5075, Cross Entropy: 1.403000, Accuracy: 0.1954, Precision: 0.2066, Recall: 0.1954, F1 Score: 0.1782, AUC: 0.5057, R2 Score: -20.337123, MAE: 10.3220, MSE: 111.7513
Training: Fold 2 - Total Loss: 34.4988, Cross Entropy: 1.402495, Accuracy: 0.2007, Precision: 0.2174, Recall: 0.2007, F1 Score: 0.1900, AUC: 0.5056, R2 Score: -21.519776, MAE: 10.3345, MSE: 111.7237
Training: Fold 3 - Total Loss: 34.2771, Cross Entropy: 1.402917, Accuracy: 0.1761, Precision: 0.1775, Recall: 0.1761, F1 Score: 0.1624, AUC: 0.5057, R2 Score: -21.878009, MAE: 10.3013, MSE: 110.9834
Training: Fold 4 - Total Loss: 34.9648, Cross Entropy: 1.398278, Accuracy: 0.2007, Precision: 0.2321, Recall: 0.2007, F1 Score: 0.1975, AUC: 0.5129, R2 Score: -20.338022, MAE: 10.3919, MSE: 113.2865
Validation: Fold 5 - Total Loss: 35.6564, Cross Entropy: 1.397263, Accuracy: 0.1690, Precision: 0.4249, Recall: 0.1690, F1 Score: 0.1582, AUC: 0.4978, R2 Score: -21.379034, MAE: 10.5056, MSE: 115.5944
Avg Latency (ms): 0.96, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.1690

Epoch 3/10
Training: Fold 1 - Total Loss: 34.4085, Cross Entropy: 1.404774, Accuracy: 0.1690, Precision: 0.1898, Recall: 0.1690, F1 Score: 0.1643, AUC: 0.4669, R2 Score: -20.340000, MAE: 10.3051, MSE: 111.4172
Training: Fold 2 - Total Loss: 34.4269, Cross Entropy: 1.401874, Accuracy: 0.2130, Precision: 0.2154, Recall: 0.2130, F1 Score: 0.1958, AUC: 0.5132, R2 Score: -21.522951, MAE: 10.3195, MSE: 111.4854
Training: Fold 3 - Total Loss: 34.3276, Cross Entropy: 1.402582, Accuracy: 0.1972, Precision: 0.2000, Recall: 0.1972, F1 Score: 0.1781, AUC: 0.5243, R2 Score: -21.869560, MAE: 10.3109, MSE: 111.1527
Training: Fold 4 - Total Loss: 34.9687, Cross Entropy: 1.398585, Accuracy: 0.1901, Precision: 0.2148, Recall: 0.1901, F1 Score: 0.1870, AUC: 0.5024, R2 Score: -20.333274, MAE: 10.3922, MSE: 113.2989
Validation: Fold 5 - Total Loss: 35.6454, Cross Entropy: 1.397685, Accuracy: 0.1620, Precision: 0.3942, Recall: 0.1620, F1 Score: 0.1486, AUC: 0.5085, R2 Score: -21.370679, MAE: 10.5038, MSE: 115.5567
Avg Latency (ms): 0.97, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.4164, Cross Entropy: 1.402168, Accuracy: 0.1884, Precision: 0.2082, Recall: 0.1884, F1 Score: 0.1809, AUC: 0.5027, R2 Score: -20.337697, MAE: 10.3050, MSE: 111.4496
Training: Fold 2 - Total Loss: 34.4650, Cross Entropy: 1.402119, Accuracy: 0.1796, Precision: 0.2079, Recall: 0.1796, F1 Score: 0.1768, AUC: 0.5095, R2 Score: -21.512976, MAE: 10.3278, MSE: 111.6117
Training: Fold 3 - Total Loss: 34.3103, Cross Entropy: 1.405349, Accuracy: 0.1708, Precision: 0.1975, Recall: 0.1708, F1 Score: 0.1611, AUC: 0.4814, R2 Score: -21.865756, MAE: 10.3060, MSE: 111.0885
Training: Fold 4 - Total Loss: 34.9443, Cross Entropy: 1.399522, Accuracy: 0.1954, Precision: 0.2140, Recall: 0.1954, F1 Score: 0.1851, AUC: 0.5016, R2 Score: -20.343646, MAE: 10.3894, MSE: 113.2155
Validation: Fold 5 - Total Loss: 35.6551, Cross Entropy: 1.397132, Accuracy: 0.2042, Precision: 0.1754, Recall: 0.2042, F1 Score: 0.1688, AUC: 0.5250, R2 Score: -21.376119, MAE: 10.5054, MSE: 115.5905
Avg Latency (ms): 1.17, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.2042

Epoch 5/10
Training: Fold 1 - Total Loss: 34.4221, Cross Entropy: 1.400783, Accuracy: 0.2025, Precision: 0.2201, Recall: 0.2025, F1 Score: 0.1918, AUC: 0.5146, R2 Score: -20.336377, MAE: 10.3058, MSE: 111.4720
Training: Fold 2 - Total Loss: 34.5088, Cross Entropy: 1.401448, Accuracy: 0.1937, Precision: 0.2173, Recall: 0.1937, F1 Score: 0.1815, AUC: 0.5214, R2 Score: -21.520606, MAE: 10.3343, MSE: 111.7593
Training: Fold 3 - Total Loss: 34.2766, Cross Entropy: 1.403607, Accuracy: 0.1831, Precision: 0.1943, Recall: 0.1831, F1 Score: 0.1694, AUC: 0.4975, R2 Score: -21.866171, MAE: 10.3015, MSE: 110.9804
Training: Fold 4 - Total Loss: 34.9596, Cross Entropy: 1.399357, Accuracy: 0.1813, Precision: 0.1966, Recall: 0.1813, F1 Score: 0.1755, AUC: 0.4836, R2 Score: -20.336989, MAE: 10.3904, MSE: 113.2668
Validation: Fold 5 - Total Loss: 35.6562, Cross Entropy: 1.399265, Accuracy: 0.1338, Precision: 0.1338, Recall: 0.1338, F1 Score: 0.1107, AUC: 0.4274, R2 Score: -21.375485, MAE: 10.5053, MSE: 115.5891
Avg Latency (ms): 0.98, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.5058, Cross Entropy: 1.403500, Accuracy: 0.1673, Precision: 0.1817, Recall: 0.1673, F1 Score: 0.1530, AUC: 0.4785, R2 Score: -20.341855, MAE: 10.3216, MSE: 111.7446
Training: Fold 2 - Total Loss: 34.4782, Cross Entropy: 1.402015, Accuracy: 0.1972, Precision: 0.2263, Recall: 0.1972, F1 Score: 0.1973, AUC: 0.4876, R2 Score: -21.527461, MAE: 10.3284, MSE: 111.6560
Training: Fold 3 - Total Loss: 34.2728, Cross Entropy: 1.402346, Accuracy: 0.1866, Precision: 0.1982, Recall: 0.1866, F1 Score: 0.1737, AUC: 0.5097, R2 Score: -21.878060, MAE: 10.3008, MSE: 110.9707
Training: Fold 4 - Total Loss: 34.9306, Cross Entropy: 1.396786, Accuracy: 0.1989, Precision: 0.2107, Recall: 0.1989, F1 Score: 0.1848, AUC: 0.5414, R2 Score: -20.330319, MAE: 10.3861, MSE: 113.1761
Validation: Fold 5 - Total Loss: 35.6591, Cross Entropy: 1.397168, Accuracy: 0.1761, Precision: 0.1680, Recall: 0.1761, F1 Score: 0.1398, AUC: 0.5712, R2 Score: -21.380145, MAE: 10.5059, MSE: 115.6037
Avg Latency (ms): 0.96, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.4173, Cross Entropy: 1.401167, Accuracy: 0.2025, Precision: 0.2273, Recall: 0.2025, F1 Score: 0.1920, AUC: 0.5268, R2 Score: -20.337755, MAE: 10.3071, MSE: 111.4551
Training: Fold 2 - Total Loss: 34.4340, Cross Entropy: 1.402052, Accuracy: 0.1708, Precision: 0.1875, Recall: 0.1708, F1 Score: 0.1611, AUC: 0.5161, R2 Score: -21.532078, MAE: 10.3220, MSE: 111.5086
Training: Fold 3 - Total Loss: 34.3006, Cross Entropy: 1.403415, Accuracy: 0.1954, Precision: 0.2177, Recall: 0.1954, F1 Score: 0.1794, AUC: 0.5152, R2 Score: -21.868537, MAE: 10.3074, MSE: 111.0606
Training: Fold 4 - Total Loss: 34.9848, Cross Entropy: 1.398453, Accuracy: 0.2060, Precision: 0.2507, Recall: 0.2060, F1 Score: 0.2039, AUC: 0.5175, R2 Score: -20.333561, MAE: 10.3959, MSE: 113.3528
Validation: Fold 5 - Total Loss: 35.6646, Cross Entropy: 1.397848, Accuracy: 0.1408, Precision: 0.1310, Recall: 0.1408, F1 Score: 0.1108, AUC: 0.5098, R2 Score: -21.379856, MAE: 10.5067, MSE: 115.6203
Avg Latency (ms): 0.98, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.4250, Cross Entropy: 1.401834, Accuracy: 0.2077, Precision: 0.2194, Recall: 0.2077, F1 Score: 0.1943, AUC: 0.4977, R2 Score: -20.341795, MAE: 10.3079, MSE: 111.4790
Training: Fold 2 - Total Loss: 34.4586, Cross Entropy: 1.402838, Accuracy: 0.1761, Precision: 0.2050, Recall: 0.1761, F1 Score: 0.1761, AUC: 0.4850, R2 Score: -21.521042, MAE: 10.3256, MSE: 111.5887
Training: Fold 3 - Total Loss: 34.3223, Cross Entropy: 1.402283, Accuracy: 0.2042, Precision: 0.2266, Recall: 0.2042, F1 Score: 0.1951, AUC: 0.5140, R2 Score: -21.879217, MAE: 10.3084, MSE: 111.1356
Training: Fold 4 - Total Loss: 34.9019, Cross Entropy: 1.400041, Accuracy: 0.1866, Precision: 0.2225, Recall: 0.1866, F1 Score: 0.1851, AUC: 0.4857, R2 Score: -20.341562, MAE: 10.3812, MSE: 113.0728
Validation: Fold 5 - Total Loss: 35.6563, Cross Entropy: 1.397204, Accuracy: 0.1479, Precision: 0.1578, Recall: 0.1479, F1 Score: 0.1239, AUC: 0.5207, R2 Score: -21.378252, MAE: 10.5056, MSE: 115.5943
Avg Latency (ms): 1.00, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.4813, Cross Entropy: 1.402947, Accuracy: 0.1866, Precision: 0.2062, Recall: 0.1866, F1 Score: 0.1770, AUC: 0.4880, R2 Score: -20.344321, MAE: 10.3178, MSE: 111.6643
Training: Fold 2 - Total Loss: 34.3898, Cross Entropy: 1.402848, Accuracy: 0.1989, Precision: 0.2174, Recall: 0.1989, F1 Score: 0.1892, AUC: 0.5072, R2 Score: -21.527580, MAE: 10.3152, MSE: 111.3594
Training: Fold 3 - Total Loss: 34.2661, Cross Entropy: 1.402643, Accuracy: 0.1919, Precision: 0.2044, Recall: 0.1919, F1 Score: 0.1804, AUC: 0.5110, R2 Score: -21.862745, MAE: 10.2998, MSE: 110.9476
Training: Fold 4 - Total Loss: 34.9282, Cross Entropy: 1.398129, Accuracy: 0.2183, Precision: 0.2398, Recall: 0.2183, F1 Score: 0.2095, AUC: 0.5076, R2 Score: -20.337231, MAE: 10.3836, MSE: 113.1650
Validation: Fold 5 - Total Loss: 35.6537, Cross Entropy: 1.397007, Accuracy: 0.1690, Precision: 0.1533, Recall: 0.1690, F1 Score: 0.1382, AUC: 0.5422, R2 Score: -21.375226, MAE: 10.5052, MSE: 115.5860
Avg Latency (ms): 1.02, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.4808, Cross Entropy: 1.401586, Accuracy: 0.2077, Precision: 0.2169, Recall: 0.2077, F1 Score: 0.1915, AUC: 0.5031, R2 Score: -20.349533, MAE: 10.3162, MSE: 111.6656
Training: Fold 2 - Total Loss: 34.5078, Cross Entropy: 1.401739, Accuracy: 0.2095, Precision: 0.2447, Recall: 0.2095, F1 Score: 0.2065, AUC: 0.5136, R2 Score: -21.522305, MAE: 10.3340, MSE: 111.7551
Training: Fold 3 - Total Loss: 34.2576, Cross Entropy: 1.403067, Accuracy: 0.1919, Precision: 0.1988, Recall: 0.1919, F1 Score: 0.1765, AUC: 0.5040, R2 Score: -21.867230, MAE: 10.2999, MSE: 110.9182
Training: Fold 4 - Total Loss: 35.0157, Cross Entropy: 1.400410, Accuracy: 0.2130, Precision: 0.2411, Recall: 0.2130, F1 Score: 0.2048, AUC: 0.4867, R2 Score: -20.347562, MAE: 10.3994, MSE: 113.4513
Validation: Fold 5 - Total Loss: 35.6584, Cross Entropy: 1.397391, Accuracy: 0.1549, Precision: 0.3776, Recall: 0.1549, F1 Score: 0.1341, AUC: 0.4877, R2 Score: -21.378448, MAE: 10.5059, MSE: 115.6008
Avg Latency (ms): 1.03, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 71.72 MB
====================================================================================================

In [107]:
main("vit-tiny", EPOCHS=10)

====================================================================================================
Training Model: vit-tiny
Initial Backbone Model Size: 22.92 MB
Modified Backbone Model Size: 22.25 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.3157, Cross Entropy: 1.368458, Accuracy: 0.3592, Precision: 0.2631, Recall: 0.3592, F1 Score: 0.2427, AUC: 0.4893, R2 Score: -20.255673, MAE: 10.2915, MSE: 111.1927
Training: Fold 2 - Total Loss: 34.3270, Cross Entropy: 1.375246, Accuracy: 0.3468, Precision: 0.2986, Recall: 0.3468, F1 Score: 0.2524, AUC: 0.5020, R2 Score: -21.416105, MAE: 10.3077, MSE: 111.2144
Training: Fold 3 - Total Loss: 33.9957, Cross Entropy: 1.382014, Accuracy: 0.3151, Precision: 0.2077, Recall: 0.3151, F1 Score: 0.2090, AUC: 0.5167, R2 Score: -21.751221, MAE: 10.2566, MSE: 110.0943
Training: Fold 4 - Total Loss: 34.7689, Cross Entropy: 1.370891, Accuracy: 0.3592, Precision: 0.2298, Recall: 0.3592, F1 Score: 0.2440, AUC: 0.4852, R2 Score: -20.274567, MAE: 10.3618, MSE: 112.6976
Validation: Fold 5 - Total Loss: 35.5722, Cross Entropy: 1.376259, Accuracy: 0.3521, Precision: 0.1424, Recall: 0.3521, F1 Score: 0.2028, AUC: 0.4087, R2 Score: -21.327642, MAE: 10.4940, MSE: 115.3626
Avg Latency (ms): 2.70, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3521

Epoch 2/10
Training: Fold 1 - Total Loss: 34.3490, Cross Entropy: 1.371967, Accuracy: 0.3486, Precision: 0.2679, Recall: 0.3486, F1 Score: 0.2436, AUC: 0.4935, R2 Score: -20.283321, MAE: 10.2965, MSE: 111.2954
Training: Fold 2 - Total Loss: 34.2986, Cross Entropy: 1.377356, Accuracy: 0.3380, Precision: 0.3061, Recall: 0.3380, F1 Score: 0.2388, AUC: 0.4980, R2 Score: -21.410612, MAE: 10.3039, MSE: 111.1149
Training: Fold 3 - Total Loss: 34.1730, Cross Entropy: 1.392614, Accuracy: 0.3099, Precision: 0.2764, Recall: 0.3099, F1 Score: 0.2127, AUC: 0.4696, R2 Score: -21.757417, MAE: 10.2855, MSE: 110.6605
Training: Fold 4 - Total Loss: 34.7762, Cross Entropy: 1.374181, Accuracy: 0.3504, Precision: 0.2379, Recall: 0.3504, F1 Score: 0.2453, AUC: 0.4775, R2 Score: -20.218941, MAE: 10.3633, MSE: 112.7142
Validation: Fold 5 - Total Loss: 35.5717, Cross Entropy: 1.376496, Accuracy: 0.3592, Precision: 0.1442, Recall: 0.3592, F1 Score: 0.2058, AUC: 0.4090, R2 Score: -21.326427, MAE: 10.4938, MSE: 115.3604
Avg Latency (ms): 2.71, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3592

Epoch 3/10
Training: Fold 1 - Total Loss: 34.2085, Cross Entropy: 1.371555, Accuracy: 0.3363, Precision: 0.2536, Recall: 0.3363, F1 Score: 0.2371, AUC: 0.4943, R2 Score: -20.207131, MAE: 10.2748, MSE: 110.8282
Training: Fold 2 - Total Loss: 34.3407, Cross Entropy: 1.375451, Accuracy: 0.3345, Precision: 0.2353, Recall: 0.3345, F1 Score: 0.2297, AUC: 0.4843, R2 Score: -21.427123, MAE: 10.3102, MSE: 111.2597
Training: Fold 3 - Total Loss: 34.0971, Cross Entropy: 1.385458, Accuracy: 0.3275, Precision: 0.2857, Recall: 0.3275, F1 Score: 0.2239, AUC: 0.5038, R2 Score: -21.747735, MAE: 10.2739, MSE: 110.4241
Training: Fold 4 - Total Loss: 34.8493, Cross Entropy: 1.362679, Accuracy: 0.3574, Precision: 0.2764, Recall: 0.3574, F1 Score: 0.2584, AUC: 0.5207, R2 Score: -20.275433, MAE: 10.3754, MSE: 112.9848
Validation: Fold 5 - Total Loss: 35.5663, Cross Entropy: 1.376212, Accuracy: 0.3521, Precision: 0.1424, Recall: 0.3521, F1 Score: 0.2028, AUC: 0.4172, R2 Score: -21.324385, MAE: 10.4930, MSE: 115.3432
Avg Latency (ms): 2.27, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.3470, Cross Entropy: 1.367741, Accuracy: 0.3504, Precision: 0.2633, Recall: 0.3504, F1 Score: 0.2485, AUC: 0.5057, R2 Score: -20.252545, MAE: 10.2997, MSE: 111.2985
Training: Fold 2 - Total Loss: 34.3067, Cross Entropy: 1.374062, Accuracy: 0.3592, Precision: 0.3326, Recall: 0.3592, F1 Score: 0.2634, AUC: 0.5185, R2 Score: -21.416626, MAE: 10.3037, MSE: 111.1494
Training: Fold 3 - Total Loss: 34.1754, Cross Entropy: 1.379645, Accuracy: 0.3398, Precision: 0.2631, Recall: 0.3398, F1 Score: 0.2243, AUC: 0.5197, R2 Score: -21.775000, MAE: 10.2854, MSE: 110.6988
Training: Fold 4 - Total Loss: 34.7976, Cross Entropy: 1.373115, Accuracy: 0.3504, Precision: 0.2620, Recall: 0.3504, F1 Score: 0.2485, AUC: 0.4765, R2 Score: -20.235366, MAE: 10.3677, MSE: 112.7882
Validation: Fold 5 - Total Loss: 35.5707, Cross Entropy: 1.376334, Accuracy: 0.3521, Precision: 0.1435, Recall: 0.3521, F1 Score: 0.2039, AUC: 0.4195, R2 Score: -21.326442, MAE: 10.4937, MSE: 115.3574
Avg Latency (ms): 2.62, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.2824, Cross Entropy: 1.372116, Accuracy: 0.3433, Precision: 0.3515, Recall: 0.3433, F1 Score: 0.2541, AUC: 0.4894, R2 Score: -20.227616, MAE: 10.2880, MSE: 111.0731
Training: Fold 2 - Total Loss: 34.3318, Cross Entropy: 1.381664, Accuracy: 0.3292, Precision: 0.2585, Recall: 0.3292, F1 Score: 0.2305, AUC: 0.4757, R2 Score: -21.406395, MAE: 10.3089, MSE: 111.2153
Training: Fold 3 - Total Loss: 34.1138, Cross Entropy: 1.384157, Accuracy: 0.3451, Precision: 0.2724, Recall: 0.3451, F1 Score: 0.2266, AUC: 0.5067, R2 Score: -21.783963, MAE: 10.2738, MSE: 110.4828
Training: Fold 4 - Total Loss: 34.8658, Cross Entropy: 1.376545, Accuracy: 0.3592, Precision: 0.2434, Recall: 0.3592, F1 Score: 0.2468, AUC: 0.4730, R2 Score: -20.255764, MAE: 10.3783, MSE: 113.0073
Validation: Fold 5 - Total Loss: 35.5721, Cross Entropy: 1.376105, Accuracy: 0.3592, Precision: 0.1442, Recall: 0.3592, F1 Score: 0.2058, AUC: 0.4154, R2 Score: -21.327691, MAE: 10.4939, MSE: 115.3628
Avg Latency (ms): 2.52, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.2749, Cross Entropy: 1.377672, Accuracy: 0.3398, Precision: 0.2526, Recall: 0.3398, F1 Score: 0.2370, AUC: 0.4756, R2 Score: -20.267336, MAE: 10.2851, MSE: 111.0350
Training: Fold 2 - Total Loss: 34.3793, Cross Entropy: 1.374294, Accuracy: 0.3574, Precision: 0.3064, Recall: 0.3574, F1 Score: 0.2444, AUC: 0.4753, R2 Score: -21.441727, MAE: 10.3160, MSE: 111.3909
Training: Fold 3 - Total Loss: 34.2338, Cross Entropy: 1.388958, Accuracy: 0.3345, Precision: 0.2428, Recall: 0.3345, F1 Score: 0.2214, AUC: 0.4790, R2 Score: -21.783394, MAE: 10.2974, MSE: 110.8718
Training: Fold 4 - Total Loss: 34.8767, Cross Entropy: 1.365508, Accuracy: 0.3521, Precision: 0.3063, Recall: 0.3521, F1 Score: 0.2566, AUC: 0.5131, R2 Score: -20.278041, MAE: 10.3800, MSE: 113.0696
Validation: Fold 5 - Total Loss: 35.5704, Cross Entropy: 1.376311, Accuracy: 0.3592, Precision: 0.1463, Recall: 0.3592, F1 Score: 0.2079, AUC: 0.4085, R2 Score: -21.326090, MAE: 10.4936, MSE: 115.3565
Avg Latency (ms): 2.63, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.3985, Cross Entropy: 1.365949, Accuracy: 0.3609, Precision: 0.3109, Recall: 0.3609, F1 Score: 0.2484, AUC: 0.4821, R2 Score: -20.259065, MAE: 10.3061, MSE: 111.4744
Training: Fold 2 - Total Loss: 34.2786, Cross Entropy: 1.375827, Accuracy: 0.3609, Precision: 0.3900, Recall: 0.3609, F1 Score: 0.2603, AUC: 0.5018, R2 Score: -21.422031, MAE: 10.3006, MSE: 111.0518
Training: Fold 3 - Total Loss: 34.1437, Cross Entropy: 1.377731, Accuracy: 0.3327, Precision: 0.2170, Recall: 0.3327, F1 Score: 0.2207, AUC: 0.5312, R2 Score: -21.803865, MAE: 10.2822, MSE: 110.5975
Training: Fold 4 - Total Loss: 34.8127, Cross Entropy: 1.369928, Accuracy: 0.3556, Precision: 0.3291, Recall: 0.3556, F1 Score: 0.2458, AUC: 0.4890, R2 Score: -20.271378, MAE: 10.3689, MSE: 112.8460
Validation: Fold 5 - Total Loss: 35.5722, Cross Entropy: 1.376023, Accuracy: 0.3592, Precision: 0.1452, Recall: 0.3592, F1 Score: 0.2068, AUC: 0.4212, R2 Score: -21.327053, MAE: 10.4939, MSE: 115.3632
Avg Latency (ms): 2.49, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.2889, Cross Entropy: 1.375599, Accuracy: 0.3504, Precision: 0.2918, Recall: 0.3504, F1 Score: 0.2490, AUC: 0.4740, R2 Score: -20.267749, MAE: 10.2886, MSE: 111.0865
Training: Fold 2 - Total Loss: 34.2310, Cross Entropy: 1.373752, Accuracy: 0.3363, Precision: 0.2889, Recall: 0.3363, F1 Score: 0.2459, AUC: 0.5045, R2 Score: -21.390200, MAE: 10.2922, MSE: 110.8981
Training: Fold 3 - Total Loss: 34.0321, Cross Entropy: 1.381412, Accuracy: 0.3486, Precision: 0.2930, Recall: 0.3486, F1 Score: 0.2348, AUC: 0.4980, R2 Score: -21.731061, MAE: 10.2633, MSE: 110.2169
Training: Fold 4 - Total Loss: 34.7383, Cross Entropy: 1.372066, Accuracy: 0.3609, Precision: 0.2721, Recall: 0.3609, F1 Score: 0.2547, AUC: 0.5028, R2 Score: -20.247611, MAE: 10.3574, MSE: 112.5929
Validation: Fold 5 - Total Loss: 35.5713, Cross Entropy: 1.376521, Accuracy: 0.3521, Precision: 0.1424, Recall: 0.3521, F1 Score: 0.2028, AUC: 0.4105, R2 Score: -21.325957, MAE: 10.4938, MSE: 115.3590
Avg Latency (ms): 2.62, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.2808, Cross Entropy: 1.369187, Accuracy: 0.3486, Precision: 0.3342, Recall: 0.3486, F1 Score: 0.2483, AUC: 0.5050, R2 Score: -20.231963, MAE: 10.2885, MSE: 111.0747
Training: Fold 2 - Total Loss: 34.3095, Cross Entropy: 1.371910, Accuracy: 0.3433, Precision: 0.2329, Recall: 0.3433, F1 Score: 0.2295, AUC: 0.4977, R2 Score: -21.429541, MAE: 10.3022, MSE: 111.1639
Training: Fold 3 - Total Loss: 34.2013, Cross Entropy: 1.388294, Accuracy: 0.3099, Precision: 0.2629, Recall: 0.3099, F1 Score: 0.2059, AUC: 0.4982, R2 Score: -21.795943, MAE: 10.2918, MSE: 110.7650
Training: Fold 4 - Total Loss: 34.8443, Cross Entropy: 1.367613, Accuracy: 0.3609, Precision: 0.2611, Recall: 0.3609, F1 Score: 0.2538, AUC: 0.4999, R2 Score: -20.277691, MAE: 10.3745, MSE: 112.9564
Validation: Fold 5 - Total Loss: 35.5665, Cross Entropy: 1.376337, Accuracy: 0.3521, Precision: 0.1424, Recall: 0.3521, F1 Score: 0.2028, AUC: 0.4097, R2 Score: -21.322753, MAE: 10.4930, MSE: 115.3437
Avg Latency (ms): 2.27, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.3267, Cross Entropy: 1.374987, Accuracy: 0.3380, Precision: 0.1941, Recall: 0.3380, F1 Score: 0.2280, AUC: 0.4821, R2 Score: -20.278552, MAE: 10.2945, MSE: 111.2141
Training: Fold 2 - Total Loss: 34.3781, Cross Entropy: 1.377130, Accuracy: 0.3539, Precision: 0.2984, Recall: 0.3539, F1 Score: 0.2497, AUC: 0.4928, R2 Score: -21.450458, MAE: 10.3159, MSE: 111.3804
Training: Fold 3 - Total Loss: 34.2395, Cross Entropy: 1.384947, Accuracy: 0.3327, Precision: 0.2639, Recall: 0.3327, F1 Score: 0.2310, AUC: 0.5176, R2 Score: -21.782661, MAE: 10.2971, MSE: 110.9000
Training: Fold 4 - Total Loss: 34.7800, Cross Entropy: 1.368106, Accuracy: 0.3644, Precision: 0.3131, Recall: 0.3644, F1 Score: 0.2586, AUC: 0.4957, R2 Score: -20.230081, MAE: 10.3651, MSE: 112.7411
Validation: Fold 5 - Total Loss: 35.5691, Cross Entropy: 1.375917, Accuracy: 0.3521, Precision: 0.1435, Recall: 0.3521, F1 Score: 0.2039, AUC: 0.4269, R2 Score: -21.325244, MAE: 10.4935, MSE: 115.3533
Avg Latency (ms): 2.62, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 22.25 MB
====================================================================================================

In [108]:
main("efficientnet-b0", EPOCHS=10)

====================================================================================================
Training Model: efficientnet-b0
Initial Backbone Model Size: 21.43 MB
Modified Backbone Model Size: 16.96 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.2308, Cross Entropy: 1.403117, Accuracy: 0.1074, Precision: 0.3179, Recall: 0.1074, F1 Score: 0.0840, AUC: 0.5331, R2 Score: -20.234610, MAE: 10.2756, MSE: 110.8288
Training: Fold 2 - Total Loss: 34.3930, Cross Entropy: 1.408473, Accuracy: 0.1074, Precision: 0.2225, Recall: 0.1074, F1 Score: 0.0911, AUC: 0.4831, R2 Score: -21.424582, MAE: 10.3158, MSE: 111.3568
Training: Fold 3 - Total Loss: 34.1198, Cross Entropy: 1.407530, Accuracy: 0.1144, Precision: 0.1839, Recall: 0.1144, F1 Score: 0.0988, AUC: 0.4793, R2 Score: -21.763745, MAE: 10.2756, MSE: 110.4486
Training: Fold 4 - Total Loss: 34.8164, Cross Entropy: 1.404791, Accuracy: 0.1039, Precision: 0.1940, Recall: 0.1039, F1 Score: 0.0718, AUC: 0.5191, R2 Score: -20.239864, MAE: 10.3658, MSE: 112.7769
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 6.62, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.0704

Epoch 2/10
Training: Fold 1 - Total Loss: 34.2932, Cross Entropy: 1.404781, Accuracy: 0.1197, Precision: 0.3389, Recall: 0.1197, F1 Score: 0.1104, AUC: 0.4734, R2 Score: -20.234110, MAE: 10.2872, MSE: 111.0328
Training: Fold 2 - Total Loss: 34.4357, Cross Entropy: 1.405775, Accuracy: 0.1004, Precision: 0.2334, Recall: 0.1004, F1 Score: 0.0806, AUC: 0.4898, R2 Score: -21.423431, MAE: 10.3215, MSE: 111.5056
Training: Fold 3 - Total Loss: 34.1785, Cross Entropy: 1.409365, Accuracy: 0.0951, Precision: 0.1579, Recall: 0.0951, F1 Score: 0.0735, AUC: 0.4669, R2 Score: -21.765331, MAE: 10.2841, MSE: 110.6399
Training: Fold 4 - Total Loss: 34.8327, Cross Entropy: 1.404262, Accuracy: 0.1232, Precision: 0.3234, Recall: 0.1232, F1 Score: 0.1112, AUC: 0.5020, R2 Score: -20.230139, MAE: 10.3688, MSE: 112.8325
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 4.12, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 34.2550, Cross Entropy: 1.405849, Accuracy: 0.1144, Precision: 0.1836, Recall: 0.1144, F1 Score: 0.1058, AUC: 0.4903, R2 Score: -20.232629, MAE: 10.2778, MSE: 110.9030
Training: Fold 2 - Total Loss: 34.3364, Cross Entropy: 1.405533, Accuracy: 0.1092, Precision: 0.5426, Recall: 0.1092, F1 Score: 0.0994, AUC: 0.4750, R2 Score: -21.404245, MAE: 10.3060, MSE: 111.1752
Training: Fold 3 - Total Loss: 34.1049, Cross Entropy: 1.406249, Accuracy: 0.1039, Precision: 0.1917, Recall: 0.1039, F1 Score: 0.0767, AUC: 0.4943, R2 Score: -21.760131, MAE: 10.2726, MSE: 110.4016
Training: Fold 4 - Total Loss: 34.8896, Cross Entropy: 1.405361, Accuracy: 0.1180, Precision: 0.2044, Recall: 0.1180, F1 Score: 0.1044, AUC: 0.4868, R2 Score: -20.230825, MAE: 10.3788, MSE: 113.0196
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 4.21, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.2904, Cross Entropy: 1.407096, Accuracy: 0.1127, Precision: 0.2747, Recall: 0.1127, F1 Score: 0.0943, AUC: 0.4798, R2 Score: -20.239385, MAE: 10.2844, MSE: 111.0180
Training: Fold 2 - Total Loss: 34.2789, Cross Entropy: 1.409850, Accuracy: 0.0986, Precision: 0.1890, Recall: 0.0986, F1 Score: 0.0858, AUC: 0.4545, R2 Score: -21.410627, MAE: 10.2968, MSE: 110.9735
Training: Fold 3 - Total Loss: 34.1550, Cross Entropy: 1.405442, Accuracy: 0.1021, Precision: 0.1569, Recall: 0.1021, F1 Score: 0.0780, AUC: 0.5205, R2 Score: -21.761367, MAE: 10.2820, MSE: 110.5707
Training: Fold 4 - Total Loss: 34.8736, Cross Entropy: 1.408056, Accuracy: 0.1144, Precision: 0.2268, Recall: 0.1144, F1 Score: 0.0848, AUC: 0.4972, R2 Score: -20.237746, MAE: 10.3759, MSE: 112.9600
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 3.96, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.2135, Cross Entropy: 1.408366, Accuracy: 0.1092, Precision: 0.1699, Recall: 0.1092, F1 Score: 0.0810, AUC: 0.4825, R2 Score: -20.227123, MAE: 10.2722, MSE: 110.7587
Training: Fold 2 - Total Loss: 34.3263, Cross Entropy: 1.409702, Accuracy: 0.1021, Precision: 0.3430, Recall: 0.1021, F1 Score: 0.0855, AUC: 0.4972, R2 Score: -21.416074, MAE: 10.3051, MSE: 111.1316
Training: Fold 3 - Total Loss: 34.0883, Cross Entropy: 1.406801, Accuracy: 0.1250, Precision: 0.1950, Recall: 0.1250, F1 Score: 0.1049, AUC: 0.5047, R2 Score: -21.759512, MAE: 10.2685, MSE: 110.3451
Training: Fold 4 - Total Loss: 34.8484, Cross Entropy: 1.407871, Accuracy: 0.1074, Precision: 0.2073, Recall: 0.1074, F1 Score: 0.0895, AUC: 0.4909, R2 Score: -20.231169, MAE: 10.3725, MSE: 112.8763
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 3.78, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.2225, Cross Entropy: 1.410168, Accuracy: 0.1039, Precision: 0.1505, Recall: 0.1039, F1 Score: 0.0837, AUC: 0.4583, R2 Score: -20.227556, MAE: 10.2728, MSE: 110.7845
Training: Fold 2 - Total Loss: 34.3463, Cross Entropy: 1.409264, Accuracy: 0.1109, Precision: 0.1797, Recall: 0.1109, F1 Score: 0.0903, AUC: 0.4841, R2 Score: -21.411280, MAE: 10.3089, MSE: 111.1993
Training: Fold 3 - Total Loss: 34.1395, Cross Entropy: 1.405185, Accuracy: 0.1021, Precision: 0.3227, Recall: 0.1021, F1 Score: 0.0769, AUC: 0.5007, R2 Score: -21.763280, MAE: 10.2797, MSE: 110.5197
Training: Fold 4 - Total Loss: 34.8306, Cross Entropy: 1.404765, Accuracy: 0.1303, Precision: 0.2599, Recall: 0.1303, F1 Score: 0.1193, AUC: 0.4954, R2 Score: -20.252677, MAE: 10.3665, MSE: 112.8241
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 3.82, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.3223, Cross Entropy: 1.406048, Accuracy: 0.1127, Precision: 0.5252, Recall: 0.1127, F1 Score: 0.0857, AUC: 0.5042, R2 Score: -20.224132, MAE: 10.2906, MSE: 111.1267
Training: Fold 2 - Total Loss: 34.3534, Cross Entropy: 1.406269, Accuracy: 0.1109, Precision: 0.3649, Recall: 0.1109, F1 Score: 0.0974, AUC: 0.4958, R2 Score: -21.416061, MAE: 10.3085, MSE: 111.2301
Training: Fold 3 - Total Loss: 34.2104, Cross Entropy: 1.411129, Accuracy: 0.1056, Precision: 0.1668, Recall: 0.1056, F1 Score: 0.0733, AUC: 0.4713, R2 Score: -21.763164, MAE: 10.2897, MSE: 110.7420
Training: Fold 4 - Total Loss: 34.8160, Cross Entropy: 1.405031, Accuracy: 0.1074, Precision: 0.1948, Recall: 0.1074, F1 Score: 0.0737, AUC: 0.4919, R2 Score: -20.245792, MAE: 10.3663, MSE: 112.7748
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 3.85, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.2141, Cross Entropy: 1.405925, Accuracy: 0.1162, Precision: 0.2858, Recall: 0.1162, F1 Score: 0.1016, AUC: 0.4907, R2 Score: -20.231507, MAE: 10.2702, MSE: 110.7667
Training: Fold 2 - Total Loss: 34.3090, Cross Entropy: 1.408887, Accuracy: 0.1268, Precision: 0.5127, Recall: 0.1268, F1 Score: 0.1180, AUC: 0.4680, R2 Score: -21.419989, MAE: 10.3026, MSE: 111.0760
Training: Fold 3 - Total Loss: 34.1184, Cross Entropy: 1.404805, Accuracy: 0.1039, Precision: 0.1773, Recall: 0.1039, F1 Score: 0.0926, AUC: 0.5044, R2 Score: -21.757483, MAE: 10.2756, MSE: 110.4500
Training: Fold 4 - Total Loss: 34.8360, Cross Entropy: 1.407328, Accuracy: 0.1303, Precision: 0.5365, Recall: 0.1303, F1 Score: 0.1158, AUC: 0.4939, R2 Score: -20.235957, MAE: 10.3694, MSE: 112.8363
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 3.74, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.2319, Cross Entropy: 1.407062, Accuracy: 0.1056, Precision: 0.1966, Recall: 0.1056, F1 Score: 0.0957, AUC: 0.4666, R2 Score: -20.223677, MAE: 10.2750, MSE: 110.8233
Training: Fold 2 - Total Loss: 34.3109, Cross Entropy: 1.407344, Accuracy: 0.1127, Precision: 0.1673, Recall: 0.1127, F1 Score: 0.0952, AUC: 0.4846, R2 Score: -21.423596, MAE: 10.3027, MSE: 111.0858
Training: Fold 3 - Total Loss: 34.1414, Cross Entropy: 1.407804, Accuracy: 0.1056, Precision: 0.1690, Recall: 0.1056, F1 Score: 0.0859, AUC: 0.5038, R2 Score: -21.758704, MAE: 10.2796, MSE: 110.5197
Training: Fold 4 - Total Loss: 34.8066, Cross Entropy: 1.408423, Accuracy: 0.1056, Precision: 0.1780, Recall: 0.1056, F1 Score: 0.0875, AUC: 0.4649, R2 Score: -20.223694, MAE: 10.3630, MSE: 112.7357
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 3.82, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.2887, Cross Entropy: 1.405447, Accuracy: 0.1232, Precision: 0.2166, Recall: 0.1232, F1 Score: 0.1097, AUC: 0.4915, R2 Score: -20.236892, MAE: 10.2871, MSE: 111.0162
Training: Fold 2 - Total Loss: 34.2968, Cross Entropy: 1.410372, Accuracy: 0.0933, Precision: 0.3346, Recall: 0.0933, F1 Score: 0.0848, AUC: 0.4787, R2 Score: -21.412721, MAE: 10.2989, MSE: 111.0317
Training: Fold 3 - Total Loss: 34.1151, Cross Entropy: 1.411355, Accuracy: 0.1056, Precision: 0.5085, Recall: 0.1056, F1 Score: 0.0833, AUC: 0.4679, R2 Score: -21.754253, MAE: 10.2740, MSE: 110.4237
Training: Fold 4 - Total Loss: 34.7362, Cross Entropy: 1.406257, Accuracy: 0.1162, Precision: 0.1952, Recall: 0.1162, F1 Score: 0.0959, AUC: 0.4925, R2 Score: -20.227799, MAE: 10.3520, MSE: 112.5061
Validation: Fold 5 - Total Loss: 35.8699, Cross Entropy: 1.395128, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5000, R2 Score: -21.517996, MAE: 10.5396, MSE: 116.3110
Avg Latency (ms): 3.75, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 16.97 MB
====================================================================================================

In [109]:
main("shufflenetv2-0.5x", EPOCHS=10)

====================================================================================================
Training Model: shufflenetv2-0.5x
Initial Backbone Model Size: 5.59 MB
Modified Backbone Model Size: 2.02 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.5323, Cross Entropy: 1.381098, Accuracy: 0.3046, Precision: 0.2863, Recall: 0.3046, F1 Score: 0.2473, AUC: 0.4923, R2 Score: -20.359194, MAE: 10.3268, MSE: 111.8852
Training: Fold 2 - Total Loss: 34.5393, Cross Entropy: 1.377427, Accuracy: 0.3116, Precision: 0.3147, Recall: 0.3116, F1 Score: 0.2562, AUC: 0.5237, R2 Score: -21.571573, MAE: 10.3422, MSE: 111.9169
Training: Fold 3 - Total Loss: 34.3233, Cross Entropy: 1.378812, Accuracy: 0.3134, Precision: 0.3164, Recall: 0.3134, F1 Score: 0.2578, AUC: 0.5254, R2 Score: -21.895705, MAE: 10.3124, MSE: 111.1938
Training: Fold 4 - Total Loss: 34.9941, Cross Entropy: 1.380392, Accuracy: 0.3011, Precision: 0.3427, Recall: 0.3011, F1 Score: 0.2573, AUC: 0.5153, R2 Score: -20.354956, MAE: 10.3980, MSE: 113.4261
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5372, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 4.44, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3099

Epoch 2/10
Training: Fold 1 - Total Loss: 34.4708, Cross Entropy: 1.381661, Accuracy: 0.3011, Precision: 0.3088, Recall: 0.3011, F1 Score: 0.2455, AUC: 0.4835, R2 Score: -20.355555, MAE: 10.3176, MSE: 111.6789
Training: Fold 2 - Total Loss: 34.5692, Cross Entropy: 1.378455, Accuracy: 0.3187, Precision: 0.3188, Recall: 0.3187, F1 Score: 0.2691, AUC: 0.5072, R2 Score: -21.537455, MAE: 10.3465, MSE: 112.0142
Training: Fold 3 - Total Loss: 34.3115, Cross Entropy: 1.379739, Accuracy: 0.3292, Precision: 0.3399, Recall: 0.3292, F1 Score: 0.2704, AUC: 0.4939, R2 Score: -21.889367, MAE: 10.3108, MSE: 111.1521
Training: Fold 4 - Total Loss: 34.9645, Cross Entropy: 1.381598, Accuracy: 0.2887, Precision: 0.2993, Recall: 0.2887, F1 Score: 0.2388, AUC: 0.4955, R2 Score: -20.358776, MAE: 10.3932, MSE: 113.3247
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.4917, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.47, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 34.4185, Cross Entropy: 1.375412, Accuracy: 0.3451, Precision: 0.3666, Recall: 0.3451, F1 Score: 0.2886, AUC: 0.5302, R2 Score: -20.354085, MAE: 10.3068, MSE: 111.5191
Training: Fold 2 - Total Loss: 34.5150, Cross Entropy: 1.379445, Accuracy: 0.3169, Precision: 0.3338, Recall: 0.3169, F1 Score: 0.2643, AUC: 0.5082, R2 Score: -21.558248, MAE: 10.3378, MSE: 111.8313
Training: Fold 3 - Total Loss: 34.3528, Cross Entropy: 1.380616, Accuracy: 0.3204, Precision: 0.3292, Recall: 0.3204, F1 Score: 0.2741, AUC: 0.5039, R2 Score: -21.885794, MAE: 10.3156, MSE: 111.2879
Training: Fold 4 - Total Loss: 34.9527, Cross Entropy: 1.379834, Accuracy: 0.3292, Precision: 0.3533, Recall: 0.3292, F1 Score: 0.2737, AUC: 0.5013, R2 Score: -20.364476, MAE: 10.3906, MSE: 113.2895
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.4867, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.34, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.4348, Cross Entropy: 1.378825, Accuracy: 0.3151, Precision: 0.3106, Recall: 0.3151, F1 Score: 0.2565, AUC: 0.5006, R2 Score: -20.370628, MAE: 10.3123, MSE: 111.5656
Training: Fold 2 - Total Loss: 34.4769, Cross Entropy: 1.379389, Accuracy: 0.3099, Precision: 0.3103, Recall: 0.3099, F1 Score: 0.2491, AUC: 0.5285, R2 Score: -21.549828, MAE: 10.3309, MSE: 111.7045
Training: Fold 3 - Total Loss: 34.3162, Cross Entropy: 1.378744, Accuracy: 0.3222, Precision: 0.2937, Recall: 0.3222, F1 Score: 0.2480, AUC: 0.5096, R2 Score: -21.886586, MAE: 10.3095, MSE: 111.1702
Training: Fold 4 - Total Loss: 34.9906, Cross Entropy: 1.379643, Accuracy: 0.3134, Precision: 0.3147, Recall: 0.3134, F1 Score: 0.2504, AUC: 0.5145, R2 Score: -20.364639, MAE: 10.3949, MSE: 113.4162
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.4662, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.37, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.4846, Cross Entropy: 1.378536, Accuracy: 0.3151, Precision: 0.3164, Recall: 0.3151, F1 Score: 0.2555, AUC: 0.5237, R2 Score: -20.374954, MAE: 10.3194, MSE: 111.7321
Training: Fold 2 - Total Loss: 34.5145, Cross Entropy: 1.378475, Accuracy: 0.3081, Precision: 0.3186, Recall: 0.3081, F1 Score: 0.2567, AUC: 0.5081, R2 Score: -21.535920, MAE: 10.3373, MSE: 111.8318
Training: Fold 3 - Total Loss: 34.3588, Cross Entropy: 1.381444, Accuracy: 0.2905, Precision: 0.2751, Recall: 0.2905, F1 Score: 0.2441, AUC: 0.4778, R2 Score: -21.902528, MAE: 10.3175, MSE: 111.3061
Training: Fold 4 - Total Loss: 35.0127, Cross Entropy: 1.382838, Accuracy: 0.2905, Precision: 0.3020, Recall: 0.2905, F1 Score: 0.2467, AUC: 0.4748, R2 Score: -20.366100, MAE: 10.3990, MSE: 113.4825
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5237, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.59, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.4502, Cross Entropy: 1.382473, Accuracy: 0.2958, Precision: 0.2792, Recall: 0.2958, F1 Score: 0.2442, AUC: 0.4695, R2 Score: -20.360152, MAE: 10.3132, MSE: 111.6082
Training: Fold 2 - Total Loss: 34.5699, Cross Entropy: 1.379138, Accuracy: 0.3046, Precision: 0.3094, Recall: 0.3046, F1 Score: 0.2432, AUC: 0.5174, R2 Score: -21.551385, MAE: 10.3472, MSE: 112.0149
Training: Fold 3 - Total Loss: 34.3397, Cross Entropy: 1.379408, Accuracy: 0.3345, Precision: 0.3145, Recall: 0.3345, F1 Score: 0.2759, AUC: 0.5054, R2 Score: -21.910544, MAE: 10.3123, MSE: 111.2471
Training: Fold 4 - Total Loss: 35.0432, Cross Entropy: 1.379959, Accuracy: 0.3011, Precision: 0.3005, Recall: 0.3011, F1 Score: 0.2468, AUC: 0.5104, R2 Score: -20.350891, MAE: 10.4042, MSE: 113.5908
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5132, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.43, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.5414, Cross Entropy: 1.377418, Accuracy: 0.3327, Precision: 0.3250, Recall: 0.3327, F1 Score: 0.2797, AUC: 0.5392, R2 Score: -20.361489, MAE: 10.3294, MSE: 111.9239
Training: Fold 2 - Total Loss: 34.5029, Cross Entropy: 1.378848, Accuracy: 0.3380, Precision: 0.3747, Recall: 0.3380, F1 Score: 0.2942, AUC: 0.5174, R2 Score: -21.537341, MAE: 10.3365, MSE: 111.7924
Training: Fold 3 - Total Loss: 34.3741, Cross Entropy: 1.381131, Accuracy: 0.3134, Precision: 0.3081, Recall: 0.3134, F1 Score: 0.2610, AUC: 0.4911, R2 Score: -21.916013, MAE: 10.3214, MSE: 111.3575
Training: Fold 4 - Total Loss: 34.9815, Cross Entropy: 1.381106, Accuracy: 0.2782, Precision: 0.2804, Recall: 0.2782, F1 Score: 0.2217, AUC: 0.5081, R2 Score: -20.350057, MAE: 10.3954, MSE: 113.3823
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.4706, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.44, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.4801, Cross Entropy: 1.377659, Accuracy: 0.3275, Precision: 0.3338, Recall: 0.3275, F1 Score: 0.2738, AUC: 0.5281, R2 Score: -20.378565, MAE: 10.3190, MSE: 111.7190
Training: Fold 2 - Total Loss: 34.4668, Cross Entropy: 1.380486, Accuracy: 0.3151, Precision: 0.3287, Recall: 0.3151, F1 Score: 0.2625, AUC: 0.4909, R2 Score: -21.530935, MAE: 10.3284, MSE: 111.6681
Training: Fold 3 - Total Loss: 34.2913, Cross Entropy: 1.380137, Accuracy: 0.3275, Precision: 0.3276, Recall: 0.3275, F1 Score: 0.2724, AUC: 0.5118, R2 Score: -21.882466, MAE: 10.3068, MSE: 111.0840
Training: Fold 4 - Total Loss: 35.0249, Cross Entropy: 1.382241, Accuracy: 0.2870, Precision: 0.2740, Recall: 0.2870, F1 Score: 0.2261, AUC: 0.4938, R2 Score: -20.378421, MAE: 10.3985, MSE: 113.5246
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.4768, R2 Score: -21.589801, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.38, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.4406, Cross Entropy: 1.379338, Accuracy: 0.3099, Precision: 0.3194, Recall: 0.3099, F1 Score: 0.2570, AUC: 0.5114, R2 Score: -20.361286, MAE: 10.3138, MSE: 111.5836
Training: Fold 2 - Total Loss: 34.5399, Cross Entropy: 1.380653, Accuracy: 0.3204, Precision: 0.3424, Recall: 0.3204, F1 Score: 0.2747, AUC: 0.5046, R2 Score: -21.536164, MAE: 10.3427, MSE: 111.9115
Training: Fold 3 - Total Loss: 34.3673, Cross Entropy: 1.382680, Accuracy: 0.2905, Precision: 0.2817, Recall: 0.2905, F1 Score: 0.2346, AUC: 0.4810, R2 Score: -21.905555, MAE: 10.3194, MSE: 111.3313
Training: Fold 4 - Total Loss: 35.0004, Cross Entropy: 1.380647, Accuracy: 0.3046, Precision: 0.3173, Recall: 0.3046, F1 Score: 0.2497, AUC: 0.5102, R2 Score: -20.350390, MAE: 10.3986, MSE: 113.4466
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5040, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.33, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.4365, Cross Entropy: 1.380301, Accuracy: 0.3099, Precision: 0.3535, Recall: 0.3099, F1 Score: 0.2707, AUC: 0.4972, R2 Score: -20.353535, MAE: 10.3122, MSE: 111.5678
Training: Fold 2 - Total Loss: 34.4528, Cross Entropy: 1.378205, Accuracy: 0.3187, Precision: 0.3548, Recall: 0.3187, F1 Score: 0.2757, AUC: 0.5152, R2 Score: -21.551463, MAE: 10.3290, MSE: 111.6268
Training: Fold 3 - Total Loss: 34.3389, Cross Entropy: 1.378692, Accuracy: 0.3222, Precision: 0.3246, Recall: 0.3222, F1 Score: 0.2697, AUC: 0.5086, R2 Score: -21.885668, MAE: 10.3130, MSE: 111.2462
Training: Fold 4 - Total Loss: 35.0002, Cross Entropy: 1.379456, Accuracy: 0.3151, Precision: 0.3476, Recall: 0.3151, F1 Score: 0.2652, AUC: 0.5257, R2 Score: -20.357152, MAE: 10.3995, MSE: 113.4487
Validation: Fold 5 - Total Loss: 35.9724, Cross Entropy: 1.385146, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5161, R2 Score: -21.589800, MAE: 10.5569, MSE: 116.6760
Avg Latency (ms): 3.12, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 2.03 MB
====================================================================================================

In [110]:
main("regnety-400mf", EPOCHS=10)

====================================================================================================
Training Model: regnety-400mf
Initial Backbone Model Size: 17.61 MB
Modified Backbone Model Size: 16.07 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.4724, Cross Entropy: 1.485133, Accuracy: 0.1479, Precision: 0.5638, Recall: 0.1479, F1 Score: 0.1346, AUC: 0.4943, R2 Score: -20.289174, MAE: 10.3056, MSE: 111.4427
Training: Fold 2 - Total Loss: 34.3571, Cross Entropy: 1.484697, Accuracy: 0.1426, Precision: 0.3519, Recall: 0.1426, F1 Score: 0.1315, AUC: 0.4818, R2 Score: -21.420976, MAE: 10.2977, MSE: 111.0592
Training: Fold 3 - Total Loss: 34.2484, Cross Entropy: 1.477733, Accuracy: 0.1532, Precision: 0.2818, Recall: 0.1532, F1 Score: 0.1561, AUC: 0.4783, R2 Score: -21.813968, MAE: 10.2873, MSE: 110.7133
Training: Fold 4 - Total Loss: 34.8961, Cross Entropy: 1.478225, Accuracy: 0.1391, Precision: 0.4052, Recall: 0.1391, F1 Score: 0.1275, AUC: 0.5089, R2 Score: -20.257329, MAE: 10.3692, MSE: 112.8711
Validation: Fold 5 - Total Loss: 36.2003, Cross Entropy: 1.415249, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5192, R2 Score: -21.725782, MAE: 10.5896, MSE: 117.3655
Avg Latency (ms): 8.56, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.0704

Epoch 2/10
Training: Fold 1 - Total Loss: 34.3811, Cross Entropy: 1.484741, Accuracy: 0.1373, Precision: 0.2905, Recall: 0.1373, F1 Score: 0.1255, AUC: 0.4876, R2 Score: -20.231315, MAE: 10.2883, MSE: 111.1391
Training: Fold 2 - Total Loss: 34.4517, Cross Entropy: 1.479593, Accuracy: 0.1461, Precision: 0.3299, Recall: 0.1461, F1 Score: 0.1333, AUC: 0.4999, R2 Score: -21.446644, MAE: 10.3155, MSE: 111.3868
Training: Fold 3 - Total Loss: 34.1859, Cross Entropy: 1.476488, Accuracy: 0.1303, Precision: 0.1606, Recall: 0.1303, F1 Score: 0.1177, AUC: 0.4970, R2 Score: -21.755838, MAE: 10.2768, MSE: 110.5077
Training: Fold 4 - Total Loss: 34.8849, Cross Entropy: 1.477147, Accuracy: 0.1391, Precision: 0.2818, Recall: 0.1391, F1 Score: 0.1213, AUC: 0.5113, R2 Score: -20.228718, MAE: 10.3682, MSE: 112.8363
Validation: Fold 5 - Total Loss: 36.2005, Cross Entropy: 1.415258, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5257, R2 Score: -21.725830, MAE: 10.5896, MSE: 117.3661
Avg Latency (ms): 5.11, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 34.4626, Cross Entropy: 1.479521, Accuracy: 0.1408, Precision: 0.2969, Recall: 0.1408, F1 Score: 0.1263, AUC: 0.5087, R2 Score: -20.257047, MAE: 10.3041, MSE: 111.4233
Training: Fold 2 - Total Loss: 34.4068, Cross Entropy: 1.480543, Accuracy: 0.1514, Precision: 0.4308, Recall: 0.1514, F1 Score: 0.1411, AUC: 0.4924, R2 Score: -21.429187, MAE: 10.3083, MSE: 111.2348
Training: Fold 3 - Total Loss: 34.1750, Cross Entropy: 1.471883, Accuracy: 0.1637, Precision: 0.1905, Recall: 0.1637, F1 Score: 0.1506, AUC: 0.5149, R2 Score: -21.757855, MAE: 10.2769, MSE: 110.4821
Training: Fold 4 - Total Loss: 35.0085, Cross Entropy: 1.486493, Accuracy: 0.1320, Precision: 0.3034, Recall: 0.1320, F1 Score: 0.1151, AUC: 0.5037, R2 Score: -20.275979, MAE: 10.3858, MSE: 113.2265
Validation: Fold 5 - Total Loss: 36.2011, Cross Entropy: 1.415223, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5132, R2 Score: -21.726130, MAE: 10.5897, MSE: 117.3681
Avg Latency (ms): 4.96, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.3708, Cross Entropy: 1.476536, Accuracy: 0.1391, Precision: 0.2256, Recall: 0.1391, F1 Score: 0.1159, AUC: 0.5179, R2 Score: -20.239930, MAE: 10.2891, MSE: 111.1242
Training: Fold 2 - Total Loss: 34.4186, Cross Entropy: 1.483228, Accuracy: 0.1250, Precision: 0.2266, Recall: 0.1250, F1 Score: 0.1150, AUC: 0.4846, R2 Score: -21.446013, MAE: 10.3093, MSE: 111.2679
Training: Fold 3 - Total Loss: 34.2193, Cross Entropy: 1.478161, Accuracy: 0.1320, Precision: 0.2313, Recall: 0.1320, F1 Score: 0.1212, AUC: 0.4854, R2 Score: -21.798079, MAE: 10.2849, MSE: 110.6152
Training: Fold 4 - Total Loss: 34.8826, Cross Entropy: 1.485617, Accuracy: 0.1391, Precision: 0.4540, Recall: 0.1391, F1 Score: 0.1285, AUC: 0.4862, R2 Score: -20.283779, MAE: 10.3648, MSE: 112.8090
Validation: Fold 5 - Total Loss: 36.2009, Cross Entropy: 1.415283, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5037, R2 Score: -21.726085, MAE: 10.5897, MSE: 117.3672
Avg Latency (ms): 4.82, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.3412, Cross Entropy: 1.479359, Accuracy: 0.1408, Precision: 0.3740, Recall: 0.1408, F1 Score: 0.1281, AUC: 0.4902, R2 Score: -20.235554, MAE: 10.2834, MSE: 111.0188
Training: Fold 2 - Total Loss: 34.5102, Cross Entropy: 1.487048, Accuracy: 0.1338, Precision: 0.2706, Recall: 0.1338, F1 Score: 0.1199, AUC: 0.4748, R2 Score: -21.486497, MAE: 10.3250, MSE: 111.5642
Training: Fold 3 - Total Loss: 34.3363, Cross Entropy: 1.464911, Accuracy: 0.1567, Precision: 0.2930, Recall: 0.1567, F1 Score: 0.1505, AUC: 0.5097, R2 Score: -21.846404, MAE: 10.3039, MSE: 111.0363
Training: Fold 4 - Total Loss: 34.8864, Cross Entropy: 1.495483, Accuracy: 0.1303, Precision: 0.2800, Recall: 0.1303, F1 Score: 0.1148, AUC: 0.4659, R2 Score: -20.216475, MAE: 10.3653, MSE: 112.7984
Validation: Fold 5 - Total Loss: 36.2006, Cross Entropy: 1.415288, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5188, R2 Score: -21.726065, MAE: 10.5896, MSE: 117.3664
Avg Latency (ms): 5.01, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.3372, Cross Entropy: 1.476269, Accuracy: 0.1514, Precision: 0.3372, Recall: 0.1514, F1 Score: 0.1383, AUC: 0.5120, R2 Score: -20.240113, MAE: 10.2839, MSE: 111.0128
Training: Fold 2 - Total Loss: 34.3977, Cross Entropy: 1.487370, Accuracy: 0.1285, Precision: 0.1389, Recall: 0.1285, F1 Score: 0.1126, AUC: 0.4665, R2 Score: -21.426343, MAE: 10.3031, MSE: 111.1885
Training: Fold 3 - Total Loss: 34.2728, Cross Entropy: 1.482282, Accuracy: 0.1479, Precision: 0.2738, Recall: 0.1479, F1 Score: 0.1410, AUC: 0.4872, R2 Score: -21.767575, MAE: 10.2897, MSE: 110.7840
Training: Fold 4 - Total Loss: 34.8833, Cross Entropy: 1.494323, Accuracy: 0.1356, Precision: 0.3492, Recall: 0.1356, F1 Score: 0.1180, AUC: 0.4718, R2 Score: -20.219879, MAE: 10.3669, MSE: 112.7910
Validation: Fold 5 - Total Loss: 36.2007, Cross Entropy: 1.415277, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5089, R2 Score: -21.726061, MAE: 10.5896, MSE: 117.3666
Avg Latency (ms): 4.80, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.3758, Cross Entropy: 1.490882, Accuracy: 0.1444, Precision: 0.2850, Recall: 0.1444, F1 Score: 0.1223, AUC: 0.4850, R2 Score: -20.175253, MAE: 10.2891, MSE: 111.1074
Training: Fold 2 - Total Loss: 34.3328, Cross Entropy: 1.479258, Accuracy: 0.1232, Precision: 0.2278, Recall: 0.1232, F1 Score: 0.1068, AUC: 0.4985, R2 Score: -21.409281, MAE: 10.2951, MSE: 110.9910
Training: Fold 3 - Total Loss: 34.3225, Cross Entropy: 1.473851, Accuracy: 0.1408, Precision: 0.4081, Recall: 0.1408, F1 Score: 0.1314, AUC: 0.5000, R2 Score: -21.825569, MAE: 10.3010, MSE: 110.9695
Training: Fold 4 - Total Loss: 34.8690, Cross Entropy: 1.486731, Accuracy: 0.1356, Precision: 0.2786, Recall: 0.1356, F1 Score: 0.1209, AUC: 0.4815, R2 Score: -20.253519, MAE: 10.3652, MSE: 112.7610
Validation: Fold 5 - Total Loss: 36.2000, Cross Entropy: 1.415285, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5160, R2 Score: -21.725497, MAE: 10.5895, MSE: 117.3643
Avg Latency (ms): 5.01, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.4074, Cross Entropy: 1.471403, Accuracy: 0.1567, Precision: 0.4199, Recall: 0.1567, F1 Score: 0.1551, AUC: 0.5198, R2 Score: -20.227101, MAE: 10.2960, MSE: 111.2580
Training: Fold 2 - Total Loss: 34.3304, Cross Entropy: 1.487464, Accuracy: 0.1408, Precision: 0.3789, Recall: 0.1408, F1 Score: 0.1246, AUC: 0.4930, R2 Score: -21.412560, MAE: 10.2931, MSE: 110.9639
Training: Fold 3 - Total Loss: 34.1918, Cross Entropy: 1.472810, Accuracy: 0.1197, Precision: 0.2435, Recall: 0.1197, F1 Score: 0.0953, AUC: 0.5268, R2 Score: -21.743596, MAE: 10.2777, MSE: 110.5361
Training: Fold 4 - Total Loss: 34.9274, Cross Entropy: 1.486339, Accuracy: 0.1338, Precision: 0.3554, Recall: 0.1338, F1 Score: 0.1232, AUC: 0.4847, R2 Score: -20.287728, MAE: 10.3737, MSE: 112.9565
Validation: Fold 5 - Total Loss: 36.2010, Cross Entropy: 1.415244, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5113, R2 Score: -21.726207, MAE: 10.5897, MSE: 117.3676
Avg Latency (ms): 4.62, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.2946, Cross Entropy: 1.482001, Accuracy: 0.1461, Precision: 0.4149, Recall: 0.1461, F1 Score: 0.1374, AUC: 0.5001, R2 Score: -20.238094, MAE: 10.2753, MSE: 110.8574
Training: Fold 2 - Total Loss: 34.4122, Cross Entropy: 1.477705, Accuracy: 0.1479, Precision: 0.1764, Recall: 0.1479, F1 Score: 0.1383, AUC: 0.4943, R2 Score: -21.458101, MAE: 10.3092, MSE: 111.2593
Training: Fold 3 - Total Loss: 34.2687, Cross Entropy: 1.472879, Accuracy: 0.1514, Precision: 0.3613, Recall: 0.1514, F1 Score: 0.1386, AUC: 0.5112, R2 Score: -21.799429, MAE: 10.2917, MSE: 110.7921
Training: Fold 4 - Total Loss: 34.8309, Cross Entropy: 1.480461, Accuracy: 0.1532, Precision: 0.3012, Recall: 0.1532, F1 Score: 0.1394, AUC: 0.4993, R2 Score: -20.187080, MAE: 10.3583, MSE: 112.6487
Validation: Fold 5 - Total Loss: 36.2012, Cross Entropy: 1.415113, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5348, R2 Score: -21.726274, MAE: 10.5897, MSE: 117.3688
Avg Latency (ms): 4.63, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.4549, Cross Entropy: 1.484313, Accuracy: 0.1514, Precision: 0.3218, Recall: 0.1514, F1 Score: 0.1326, AUC: 0.5035, R2 Score: -20.306356, MAE: 10.3013, MSE: 111.3864
Training: Fold 2 - Total Loss: 34.4669, Cross Entropy: 1.487718, Accuracy: 0.1144, Precision: 0.1317, Recall: 0.1144, F1 Score: 0.1040, AUC: 0.4961, R2 Score: -21.476120, MAE: 10.3179, MSE: 111.4182
Training: Fold 3 - Total Loss: 34.1529, Cross Entropy: 1.474869, Accuracy: 0.1426, Precision: 0.2738, Recall: 0.1426, F1 Score: 0.1302, AUC: 0.4872, R2 Score: -21.691783, MAE: 10.2714, MSE: 110.4015
Training: Fold 4 - Total Loss: 34.8901, Cross Entropy: 1.490091, Accuracy: 0.1373, Precision: 0.1449, Recall: 0.1373, F1 Score: 0.1175, AUC: 0.4824, R2 Score: -20.234571, MAE: 10.3669, MSE: 112.8236
Validation: Fold 5 - Total Loss: 36.2006, Cross Entropy: 1.415154, Accuracy: 0.0704, Precision: 0.0050, Recall: 0.0704, F1 Score: 0.0093, AUC: 0.5299, R2 Score: -21.725996, MAE: 10.5896, MSE: 117.3665
Avg Latency (ms): 4.52, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 16.08 MB
====================================================================================================

In [111]:
main("mnasnet0_5", EPOCHS=10)

====================================================================================================
Training Model: mnasnet0_5
Initial Backbone Model Size: 9.04 MB
Modified Backbone Model Size: 4.58 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.3416, Cross Entropy: 1.405684, Accuracy: 0.1320, Precision: 0.4211, Recall: 0.1320, F1 Score: 0.1184, AUC: 0.5106, R2 Score: -20.308167, MAE: 10.2919, MSE: 111.1921
Training: Fold 2 - Total Loss: 34.4809, Cross Entropy: 1.409796, Accuracy: 0.1215, Precision: 0.3710, Recall: 0.1215, F1 Score: 0.1111, AUC: 0.4766, R2 Score: -21.486518, MAE: 10.3294, MSE: 111.6467
Training: Fold 3 - Total Loss: 34.3768, Cross Entropy: 1.402607, Accuracy: 0.1250, Precision: 0.3304, Recall: 0.1250, F1 Score: 0.1175, AUC: 0.5284, R2 Score: -21.830960, MAE: 10.3174, MSE: 111.3167
Training: Fold 4 - Total Loss: 35.0252, Cross Entropy: 1.409397, Accuracy: 0.1162, Precision: 0.2982, Recall: 0.1162, F1 Score: 0.0979, AUC: 0.4915, R2 Score: -20.316938, MAE: 10.3994, MSE: 113.4619
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5000, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 4.46, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3099

Epoch 2/10
Training: Fold 1 - Total Loss: 34.4091, Cross Entropy: 1.410513, Accuracy: 0.1144, Precision: 0.2760, Recall: 0.1144, F1 Score: 0.1038, AUC: 0.4461, R2 Score: -20.306635, MAE: 10.3037, MSE: 111.4059
Training: Fold 2 - Total Loss: 34.4705, Cross Entropy: 1.409005, Accuracy: 0.1197, Precision: 0.2591, Recall: 0.1197, F1 Score: 0.1036, AUC: 0.5126, R2 Score: -21.481976, MAE: 10.3277, MSE: 111.6140
Training: Fold 3 - Total Loss: 34.2968, Cross Entropy: 1.409813, Accuracy: 0.1479, Precision: 0.3712, Recall: 0.1479, F1 Score: 0.1415, AUC: 0.4598, R2 Score: -21.851166, MAE: 10.3044, MSE: 111.0329
Training: Fold 4 - Total Loss: 34.9094, Cross Entropy: 1.408088, Accuracy: 0.1268, Precision: 0.1854, Recall: 0.1268, F1 Score: 0.1068, AUC: 0.5105, R2 Score: -20.297063, MAE: 10.3805, MSE: 113.0790
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5000, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.47, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 34.3785, Cross Entropy: 1.406225, Accuracy: 0.1250, Precision: 0.2945, Recall: 0.1250, F1 Score: 0.1209, AUC: 0.5003, R2 Score: -20.321378, MAE: 10.2971, MSE: 111.3140
Training: Fold 2 - Total Loss: 34.4230, Cross Entropy: 1.405762, Accuracy: 0.1356, Precision: 0.4282, Recall: 0.1356, F1 Score: 0.1338, AUC: 0.5181, R2 Score: -21.491185, MAE: 10.3201, MSE: 111.4632
Training: Fold 3 - Total Loss: 34.2335, Cross Entropy: 1.410958, Accuracy: 0.1250, Precision: 0.2135, Recall: 0.1250, F1 Score: 0.1021, AUC: 0.4574, R2 Score: -21.850268, MAE: 10.2935, MSE: 110.8195
Training: Fold 4 - Total Loss: 34.8521, Cross Entropy: 1.408870, Accuracy: 0.1144, Precision: 0.2579, Recall: 0.1144, F1 Score: 0.0882, AUC: 0.5057, R2 Score: -20.316190, MAE: 10.3712, MSE: 112.8865
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5023, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.40, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.3408, Cross Entropy: 1.408710, Accuracy: 0.1268, Precision: 0.2772, Recall: 0.1268, F1 Score: 0.1104, AUC: 0.4899, R2 Score: -20.309786, MAE: 10.2928, MSE: 111.1823
Training: Fold 2 - Total Loss: 34.4799, Cross Entropy: 1.407950, Accuracy: 0.1127, Precision: 0.2826, Recall: 0.1127, F1 Score: 0.1039, AUC: 0.5010, R2 Score: -21.504705, MAE: 10.3279, MSE: 111.6479
Training: Fold 3 - Total Loss: 34.3337, Cross Entropy: 1.410347, Accuracy: 0.1162, Precision: 0.2770, Recall: 0.1162, F1 Score: 0.1096, AUC: 0.4854, R2 Score: -21.851586, MAE: 10.3111, MSE: 111.1549
Training: Fold 4 - Total Loss: 34.8710, Cross Entropy: 1.410564, Accuracy: 0.1250, Precision: 0.3649, Recall: 0.1250, F1 Score: 0.1141, AUC: 0.4934, R2 Score: -20.315412, MAE: 10.3737, MSE: 112.9454
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5000, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.47, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.4193, Cross Entropy: 1.407147, Accuracy: 0.1232, Precision: 0.3125, Recall: 0.1232, F1 Score: 0.1080, AUC: 0.5100, R2 Score: -20.304116, MAE: 10.3068, MSE: 111.4477
Training: Fold 2 - Total Loss: 34.4811, Cross Entropy: 1.407878, Accuracy: 0.1426, Precision: 0.2975, Recall: 0.1426, F1 Score: 0.1395, AUC: 0.4812, R2 Score: -21.502456, MAE: 10.3295, MSE: 111.6518
Training: Fold 3 - Total Loss: 34.2333, Cross Entropy: 1.405199, Accuracy: 0.1338, Precision: 0.2330, Recall: 0.1338, F1 Score: 0.1150, AUC: 0.5083, R2 Score: -21.848717, MAE: 10.2948, MSE: 110.8320
Training: Fold 4 - Total Loss: 34.9188, Cross Entropy: 1.409558, Accuracy: 0.1180, Precision: 0.2818, Recall: 0.1180, F1 Score: 0.1019, AUC: 0.4871, R2 Score: -20.316543, MAE: 10.3838, MSE: 113.1069
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.4986, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.52, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.3906, Cross Entropy: 1.406664, Accuracy: 0.1373, Precision: 0.4330, Recall: 0.1373, F1 Score: 0.1253, AUC: 0.5089, R2 Score: -20.299960, MAE: 10.3025, MSE: 111.3531
Training: Fold 2 - Total Loss: 34.3725, Cross Entropy: 1.406917, Accuracy: 0.1268, Precision: 0.3220, Recall: 0.1268, F1 Score: 0.1150, AUC: 0.5006, R2 Score: -21.485465, MAE: 10.3117, MSE: 111.2922
Training: Fold 3 - Total Loss: 34.2837, Cross Entropy: 1.404568, Accuracy: 0.1303, Precision: 0.2469, Recall: 0.1303, F1 Score: 0.1079, AUC: 0.5371, R2 Score: -21.843659, MAE: 10.3032, MSE: 111.0017
Training: Fold 4 - Total Loss: 34.9174, Cross Entropy: 1.407105, Accuracy: 0.1268, Precision: 0.3688, Recall: 0.1268, F1 Score: 0.1208, AUC: 0.5083, R2 Score: -20.306856, MAE: 10.3836, MSE: 113.1080
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5000, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.41, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.4290, Cross Entropy: 1.408517, Accuracy: 0.1268, Precision: 0.2418, Recall: 0.1268, F1 Score: 0.1044, AUC: 0.4942, R2 Score: -20.306854, MAE: 10.3078, MSE: 111.4768
Training: Fold 2 - Total Loss: 34.4803, Cross Entropy: 1.408638, Accuracy: 0.1232, Precision: 0.3501, Recall: 0.1232, F1 Score: 0.1137, AUC: 0.4846, R2 Score: -21.490016, MAE: 10.3291, MSE: 111.6474
Training: Fold 3 - Total Loss: 34.2580, Cross Entropy: 1.410636, Accuracy: 0.1109, Precision: 0.1849, Recall: 0.1109, F1 Score: 0.0923, AUC: 0.4712, R2 Score: -21.846280, MAE: 10.2990, MSE: 110.9018
Training: Fold 4 - Total Loss: 34.9218, Cross Entropy: 1.409237, Accuracy: 0.1127, Precision: 0.3520, Recall: 0.1127, F1 Score: 0.0983, AUC: 0.4904, R2 Score: -20.296605, MAE: 10.3850, MSE: 113.1177
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5000, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.41, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.5157, Cross Entropy: 1.406457, Accuracy: 0.1426, Precision: 0.3690, Recall: 0.1426, F1 Score: 0.1315, AUC: 0.5133, R2 Score: -20.309061, MAE: 10.3224, MSE: 111.7705
Training: Fold 2 - Total Loss: 34.5036, Cross Entropy: 1.408429, Accuracy: 0.1162, Precision: 0.3245, Recall: 0.1162, F1 Score: 0.0891, AUC: 0.5162, R2 Score: -21.504082, MAE: 10.3319, MSE: 111.7256
Training: Fold 3 - Total Loss: 34.2148, Cross Entropy: 1.406364, Accuracy: 0.1391, Precision: 0.5046, Recall: 0.1391, F1 Score: 0.1361, AUC: 0.5124, R2 Score: -21.827866, MAE: 10.2915, MSE: 110.7679
Training: Fold 4 - Total Loss: 34.9671, Cross Entropy: 1.408205, Accuracy: 0.1197, Precision: 0.2144, Recall: 0.1197, F1 Score: 0.1054, AUC: 0.5090, R2 Score: -20.306450, MAE: 10.3915, MSE: 113.2712
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5023, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.47, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.3702, Cross Entropy: 1.410074, Accuracy: 0.1232, Precision: 0.1943, Recall: 0.1232, F1 Score: 0.0980, AUC: 0.4848, R2 Score: -20.314645, MAE: 10.2984, MSE: 111.2773
Training: Fold 2 - Total Loss: 34.4434, Cross Entropy: 1.408968, Accuracy: 0.1268, Precision: 0.2233, Recall: 0.1268, F1 Score: 0.1103, AUC: 0.4886, R2 Score: -21.489935, MAE: 10.3231, MSE: 111.5236
Training: Fold 3 - Total Loss: 34.2712, Cross Entropy: 1.408456, Accuracy: 0.1144, Precision: 0.2749, Recall: 0.1144, F1 Score: 0.1090, AUC: 0.4733, R2 Score: -21.834858, MAE: 10.2987, MSE: 110.9508
Training: Fold 4 - Total Loss: 34.9622, Cross Entropy: 1.408748, Accuracy: 0.1268, Precision: 0.3610, Recall: 0.1268, F1 Score: 0.1121, AUC: 0.4905, R2 Score: -20.302721, MAE: 10.3899, MSE: 113.2537
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5000, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.53, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.4259, Cross Entropy: 1.405674, Accuracy: 0.1444, Precision: 0.3961, Recall: 0.1444, F1 Score: 0.1315, AUC: 0.5197, R2 Score: -20.323300, MAE: 10.3068, MSE: 111.4729
Training: Fold 2 - Total Loss: 34.4578, Cross Entropy: 1.408938, Accuracy: 0.1092, Precision: 0.2764, Recall: 0.1092, F1 Score: 0.0968, AUC: 0.4884, R2 Score: -21.493687, MAE: 10.3236, MSE: 111.5718
Training: Fold 3 - Total Loss: 34.2346, Cross Entropy: 1.406511, Accuracy: 0.1320, Precision: 0.4148, Recall: 0.1320, F1 Score: 0.1277, AUC: 0.4949, R2 Score: -21.833018, MAE: 10.2960, MSE: 110.8333
Training: Fold 4 - Total Loss: 34.9668, Cross Entropy: 1.408638, Accuracy: 0.1268, Precision: 0.4137, Recall: 0.1268, F1 Score: 0.1124, AUC: 0.4997, R2 Score: -20.319677, MAE: 10.3900, MSE: 113.2691
Validation: Fold 5 - Total Loss: 35.9507, Cross Entropy: 1.383586, Accuracy: 0.3099, Precision: 0.0960, Recall: 0.3099, F1 Score: 0.1466, AUC: 0.5000, R2 Score: -21.576259, MAE: 10.5537, MSE: 116.6071
Avg Latency (ms): 2.24, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 4.59 MB
====================================================================================================

In [112]:
main("convnext-tiny", EPOCHS=10)

====================================================================================================
Training Model: convnext-tiny
Initial Backbone Model Size: 114.41 MB
Modified Backbone Model Size: 111.72 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.7542, Cross Entropy: 1.386022, Accuracy: 0.2570, Precision: 0.2882, Recall: 0.2570, F1 Score: 0.2318, AUC: 0.5189, R2 Score: -20.516698, MAE: 10.3645, MSE: 112.6132
Training: Fold 2 - Total Loss: 34.7799, Cross Entropy: 1.384147, Accuracy: 0.2588, Precision: 0.4719, Recall: 0.2588, F1 Score: 0.2297, AUC: 0.5431, R2 Score: -21.722571, MAE: 10.3815, MSE: 112.7032
Training: Fold 3 - Total Loss: 34.6044, Cross Entropy: 1.394068, Accuracy: 0.2676, Precision: 0.3130, Recall: 0.2676, F1 Score: 0.2408, AUC: 0.5006, R2 Score: -22.086385, MAE: 10.3558, MSE: 112.0951
Training: Fold 4 - Total Loss: 35.2687, Cross Entropy: 1.385615, Accuracy: 0.2782, Precision: 0.2823, Recall: 0.2782, F1 Score: 0.2445, AUC: 0.5109, R2 Score: -20.548263, MAE: 10.4423, MSE: 114.3293
Validation: Fold 5 - Total Loss: 35.8978, Cross Entropy: 1.387232, Accuracy: 0.3451, Precision: 0.1630, Recall: 0.3451, F1 Score: 0.2214, AUC: 0.4889, R2 Score: -21.539526, MAE: 10.5450, MSE: 116.4225
Avg Latency (ms): 4.07, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3451

Epoch 2/10
Training: Fold 1 - Total Loss: 34.7707, Cross Entropy: 1.388837, Accuracy: 0.2447, Precision: 0.2816, Recall: 0.2447, F1 Score: 0.2209, AUC: 0.4858, R2 Score: -20.550921, MAE: 10.3654, MSE: 112.6616
Training: Fold 2 - Total Loss: 34.7476, Cross Entropy: 1.387499, Accuracy: 0.2711, Precision: 0.3130, Recall: 0.2711, F1 Score: 0.2469, AUC: 0.5096, R2 Score: -21.736065, MAE: 10.3742, MSE: 112.5880
Training: Fold 3 - Total Loss: 34.5656, Cross Entropy: 1.395493, Accuracy: 0.2465, Precision: 0.2579, Recall: 0.2465, F1 Score: 0.2080, AUC: 0.4953, R2 Score: -22.074541, MAE: 10.3479, MSE: 111.9626
Training: Fold 4 - Total Loss: 35.3634, Cross Entropy: 1.386590, Accuracy: 0.2746, Precision: 0.3187, Recall: 0.2746, F1 Score: 0.2508, AUC: 0.5109, R2 Score: -20.531047, MAE: 10.4545, MSE: 114.6425
Validation: Fold 5 - Total Loss: 35.9091, Cross Entropy: 1.388420, Accuracy: 0.3592, Precision: 0.1671, Recall: 0.3592, F1 Score: 0.2280, AUC: 0.4735, R2 Score: -21.548687, MAE: 10.5468, MSE: 116.4574
Avg Latency (ms): 2.70, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3592

Epoch 3/10
Training: Fold 1 - Total Loss: 34.7412, Cross Entropy: 1.385711, Accuracy: 0.2394, Precision: 0.2870, Recall: 0.2394, F1 Score: 0.2233, AUC: 0.5182, R2 Score: -20.522191, MAE: 10.3613, MSE: 112.5707
Training: Fold 2 - Total Loss: 34.7815, Cross Entropy: 1.390947, Accuracy: 0.2359, Precision: 0.2479, Recall: 0.2359, F1 Score: 0.2120, AUC: 0.4997, R2 Score: -21.726795, MAE: 10.3804, MSE: 112.6929
Training: Fold 3 - Total Loss: 34.6257, Cross Entropy: 1.390150, Accuracy: 0.2553, Precision: 0.2824, Recall: 0.2553, F1 Score: 0.2227, AUC: 0.5228, R2 Score: -22.087746, MAE: 10.3600, MSE: 112.1754
Training: Fold 4 - Total Loss: 35.2198, Cross Entropy: 1.386831, Accuracy: 0.2746, Precision: 0.3279, Recall: 0.2746, F1 Score: 0.2575, AUC: 0.4811, R2 Score: -20.531457, MAE: 10.4313, MSE: 114.1633
Validation: Fold 5 - Total Loss: 35.9135, Cross Entropy: 1.386913, Accuracy: 0.3592, Precision: 0.1646, Recall: 0.3592, F1 Score: 0.2257, AUC: 0.4885, R2 Score: -21.550322, MAE: 10.5474, MSE: 116.4754
Avg Latency (ms): 2.64, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.7750, Cross Entropy: 1.381434, Accuracy: 0.2817, Precision: 0.2914, Recall: 0.2817, F1 Score: 0.2456, AUC: 0.5458, R2 Score: -20.538729, MAE: 10.3646, MSE: 112.6935
Training: Fold 2 - Total Loss: 34.7850, Cross Entropy: 1.386971, Accuracy: 0.2359, Precision: 0.2258, Recall: 0.2359, F1 Score: 0.1991, AUC: 0.5074, R2 Score: -21.761656, MAE: 10.3802, MSE: 112.7136
Training: Fold 3 - Total Loss: 34.5250, Cross Entropy: 1.392882, Accuracy: 0.2359, Precision: 0.4895, Recall: 0.2359, F1 Score: 0.2029, AUC: 0.5253, R2 Score: -22.071611, MAE: 10.3412, MSE: 111.8334
Training: Fold 4 - Total Loss: 35.2200, Cross Entropy: 1.391430, Accuracy: 0.2553, Precision: 0.2522, Recall: 0.2553, F1 Score: 0.2228, AUC: 0.4703, R2 Score: -20.540366, MAE: 10.4309, MSE: 114.1532
Validation: Fold 5 - Total Loss: 35.9032, Cross Entropy: 1.388517, Accuracy: 0.3592, Precision: 0.1671, Recall: 0.3592, F1 Score: 0.2280, AUC: 0.4708, R2 Score: -21.546428, MAE: 10.5460, MSE: 116.4375
Avg Latency (ms): 2.64, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.7604, Cross Entropy: 1.385311, Accuracy: 0.2694, Precision: 0.2974, Recall: 0.2694, F1 Score: 0.2408, AUC: 0.5030, R2 Score: -20.530821, MAE: 10.3639, MSE: 112.6357
Training: Fold 2 - Total Loss: 34.8408, Cross Entropy: 1.386062, Accuracy: 0.2535, Precision: 0.2836, Recall: 0.2535, F1 Score: 0.2200, AUC: 0.5316, R2 Score: -21.741385, MAE: 10.3908, MSE: 112.9019
Training: Fold 3 - Total Loss: 34.6548, Cross Entropy: 1.396033, Accuracy: 0.2342, Precision: 0.2475, Recall: 0.2342, F1 Score: 0.2041, AUC: 0.4781, R2 Score: -22.078066, MAE: 10.3624, MSE: 112.2586
Training: Fold 4 - Total Loss: 35.3328, Cross Entropy: 1.387270, Accuracy: 0.2764, Precision: 0.3233, Recall: 0.2764, F1 Score: 0.2490, AUC: 0.5082, R2 Score: -20.538390, MAE: 10.4527, MSE: 114.5391
Validation: Fold 5 - Total Loss: 35.9133, Cross Entropy: 1.387687, Accuracy: 0.3592, Precision: 0.1646, Recall: 0.3592, F1 Score: 0.2257, AUC: 0.4697, R2 Score: -21.554296, MAE: 10.5476, MSE: 116.4731
Avg Latency (ms): 2.67, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.7411, Cross Entropy: 1.385280, Accuracy: 0.2729, Precision: 0.3061, Recall: 0.2729, F1 Score: 0.2468, AUC: 0.5015, R2 Score: -20.535769, MAE: 10.3611, MSE: 112.5714
Training: Fold 2 - Total Loss: 34.7488, Cross Entropy: 1.391468, Accuracy: 0.2077, Precision: 0.2222, Recall: 0.2077, F1 Score: 0.1855, AUC: 0.4674, R2 Score: -21.723083, MAE: 10.3725, MSE: 112.5824
Training: Fold 3 - Total Loss: 34.5313, Cross Entropy: 1.394819, Accuracy: 0.2324, Precision: 0.2463, Recall: 0.2324, F1 Score: 0.2042, AUC: 0.4845, R2 Score: -22.076292, MAE: 10.3430, MSE: 111.8498
Training: Fold 4 - Total Loss: 35.2278, Cross Entropy: 1.388391, Accuracy: 0.2606, Precision: 0.2928, Recall: 0.2606, F1 Score: 0.2336, AUC: 0.5035, R2 Score: -20.510352, MAE: 10.4331, MSE: 114.1866
Validation: Fold 5 - Total Loss: 35.9150, Cross Entropy: 1.387153, Accuracy: 0.3521, Precision: 0.1614, Recall: 0.3521, F1 Score: 0.2213, AUC: 0.4811, R2 Score: -21.550230, MAE: 10.5476, MSE: 116.4801
Avg Latency (ms): 2.66, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.7302, Cross Entropy: 1.386334, Accuracy: 0.2711, Precision: 0.2999, Recall: 0.2711, F1 Score: 0.2318, AUC: 0.5180, R2 Score: -20.530542, MAE: 10.3582, MSE: 112.5324
Training: Fold 2 - Total Loss: 34.7937, Cross Entropy: 1.389510, Accuracy: 0.2289, Precision: 0.2359, Recall: 0.2289, F1 Score: 0.2023, AUC: 0.4808, R2 Score: -21.740784, MAE: 10.3791, MSE: 112.7368
Training: Fold 3 - Total Loss: 34.5821, Cross Entropy: 1.392205, Accuracy: 0.2394, Precision: 0.2315, Recall: 0.2394, F1 Score: 0.1980, AUC: 0.4985, R2 Score: -22.082977, MAE: 10.3514, MSE: 112.0252
Training: Fold 4 - Total Loss: 35.2100, Cross Entropy: 1.386486, Accuracy: 0.2623, Precision: 0.3383, Recall: 0.2623, F1 Score: 0.2294, AUC: 0.5016, R2 Score: -20.492495, MAE: 10.4321, MSE: 114.1316
Validation: Fold 5 - Total Loss: 35.9051, Cross Entropy: 1.387540, Accuracy: 0.3662, Precision: 0.1689, Recall: 0.3662, F1 Score: 0.2311, AUC: 0.4935, R2 Score: -21.548612, MAE: 10.5463, MSE: 116.4459
Avg Latency (ms): 2.60, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3662

Epoch 8/10
Training: Fold 1 - Total Loss: 34.7337, Cross Entropy: 1.389253, Accuracy: 0.2342, Precision: 0.2946, Recall: 0.2342, F1 Score: 0.2165, AUC: 0.5048, R2 Score: -20.511117, MAE: 10.3592, MSE: 112.5373
Training: Fold 2 - Total Loss: 34.7900, Cross Entropy: 1.387276, Accuracy: 0.2606, Precision: 0.3160, Recall: 0.2606, F1 Score: 0.2325, AUC: 0.5259, R2 Score: -21.722870, MAE: 10.3820, MSE: 112.7298
Training: Fold 3 - Total Loss: 34.5320, Cross Entropy: 1.390224, Accuracy: 0.2606, Precision: 0.2970, Recall: 0.2606, F1 Score: 0.2113, AUC: 0.5192, R2 Score: -22.058078, MAE: 10.3448, MSE: 111.8629
Training: Fold 4 - Total Loss: 35.2988, Cross Entropy: 1.388655, Accuracy: 0.2694, Precision: 0.2763, Recall: 0.2694, F1 Score: 0.2423, AUC: 0.4892, R2 Score: -20.546021, MAE: 10.4466, MSE: 114.4226
Validation: Fold 5 - Total Loss: 35.9002, Cross Entropy: 1.388007, Accuracy: 0.3592, Precision: 0.1646, Recall: 0.3592, F1 Score: 0.2257, AUC: 0.4687, R2 Score: -21.546309, MAE: 10.5456, MSE: 116.4287
Avg Latency (ms): 2.55, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.7469, Cross Entropy: 1.389332, Accuracy: 0.2394, Precision: 0.2555, Recall: 0.2394, F1 Score: 0.2167, AUC: 0.4931, R2 Score: -20.527676, MAE: 10.3620, MSE: 112.5814
Training: Fold 2 - Total Loss: 34.7688, Cross Entropy: 1.384201, Accuracy: 0.2535, Precision: 0.2683, Recall: 0.2535, F1 Score: 0.2226, AUC: 0.5476, R2 Score: -21.733909, MAE: 10.3782, MSE: 112.6661
Training: Fold 3 - Total Loss: 34.5795, Cross Entropy: 1.394086, Accuracy: 0.2271, Precision: 0.1850, Recall: 0.2271, F1 Score: 0.1820, AUC: 0.5022, R2 Score: -22.091497, MAE: 10.3524, MSE: 112.0121
Training: Fold 4 - Total Loss: 35.1615, Cross Entropy: 1.391212, Accuracy: 0.2377, Precision: 0.2419, Recall: 0.2377, F1 Score: 0.2147, AUC: 0.4738, R2 Score: -20.508935, MAE: 10.4222, MSE: 113.9590
Validation: Fold 5 - Total Loss: 35.9091, Cross Entropy: 1.387045, Accuracy: 0.3732, Precision: 0.1740, Recall: 0.3732, F1 Score: 0.2373, AUC: 0.4956, R2 Score: -21.547835, MAE: 10.5469, MSE: 116.4606
Avg Latency (ms): 2.42, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3732

Epoch 10/10
Training: Fold 1 - Total Loss: 34.7989, Cross Entropy: 1.383571, Accuracy: 0.2729, Precision: 0.3028, Recall: 0.2729, F1 Score: 0.2437, AUC: 0.5270, R2 Score: -20.547547, MAE: 10.3691, MSE: 112.7681
Training: Fold 2 - Total Loss: 34.8035, Cross Entropy: 1.389151, Accuracy: 0.2676, Precision: 0.3192, Recall: 0.2676, F1 Score: 0.2458, AUC: 0.4953, R2 Score: -21.746568, MAE: 10.3835, MSE: 112.7704
Training: Fold 3 - Total Loss: 34.5069, Cross Entropy: 1.396923, Accuracy: 0.2430, Precision: 0.2747, Recall: 0.2430, F1 Score: 0.2182, AUC: 0.4779, R2 Score: -22.075356, MAE: 10.3371, MSE: 111.7636
Training: Fold 4 - Total Loss: 35.2433, Cross Entropy: 1.384976, Accuracy: 0.2711, Precision: 0.2917, Recall: 0.2711, F1 Score: 0.2452, AUC: 0.5169, R2 Score: -20.520284, MAE: 10.4376, MSE: 114.2460
Validation: Fold 5 - Total Loss: 35.9133, Cross Entropy: 1.388130, Accuracy: 0.3662, Precision: 0.1730, Recall: 0.3662, F1 Score: 0.2349, AUC: 0.4852, R2 Score: -21.551199, MAE: 10.5474, MSE: 116.4722
Avg Latency (ms): 2.52, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 111.73 MB
====================================================================================================

In [113]:
main("ghostnetv2", EPOCHS=10)

====================================================================================================
Training Model: ghostnetv2
Initial Backbone Model Size: 25.11 MB
Modified Backbone Model Size: 20.64 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.8078, Cross Entropy: 1.380410, Accuracy: 0.3539, Precision: 0.3358, Recall: 0.3539, F1 Score: 0.3089, AUC: 0.4988, R2 Score: -20.622445, MAE: 10.3726, MSE: 112.8051
Training: Fold 2 - Total Loss: 34.9232, Cross Entropy: 1.378916, Accuracy: 0.3539, Precision: 0.3436, Recall: 0.3539, F1 Score: 0.3193, AUC: 0.5571, R2 Score: -21.816727, MAE: 10.4039, MSE: 113.1931
Training: Fold 3 - Total Loss: 34.7265, Cross Entropy: 1.383468, Accuracy: 0.3187, Precision: 0.3056, Recall: 0.3187, F1 Score: 0.2806, AUC: 0.4903, R2 Score: -22.174370, MAE: 10.3748, MSE: 112.5269
Training: Fold 4 - Total Loss: 35.3803, Cross Entropy: 1.379614, Accuracy: 0.3415, Precision: 0.3484, Recall: 0.3415, F1 Score: 0.3214, AUC: 0.5099, R2 Score: -20.606051, MAE: 10.4612, MSE: 114.7152
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385955, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4475, R2 Score: -21.320244, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 11.78, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.2324

Epoch 2/10
Training: Fold 1 - Total Loss: 34.8321, Cross Entropy: 1.382119, Accuracy: 0.3239, Precision: 0.2905, Recall: 0.3239, F1 Score: 0.2804, AUC: 0.4958, R2 Score: -20.618682, MAE: 10.3759, MSE: 112.8820
Training: Fold 2 - Total Loss: 34.9092, Cross Entropy: 1.380368, Accuracy: 0.3222, Precision: 0.3082, Recall: 0.3222, F1 Score: 0.2770, AUC: 0.4964, R2 Score: -21.824126, MAE: 10.4019, MSE: 113.1431
Training: Fold 3 - Total Loss: 34.7426, Cross Entropy: 1.381758, Accuracy: 0.3275, Precision: 0.3193, Recall: 0.3275, F1 Score: 0.2885, AUC: 0.5226, R2 Score: -22.176969, MAE: 10.3774, MSE: 112.5846
Training: Fold 4 - Total Loss: 35.3906, Cross Entropy: 1.380015, Accuracy: 0.3257, Precision: 0.3111, Recall: 0.3257, F1 Score: 0.2925, AUC: 0.5077, R2 Score: -20.611768, MAE: 10.4618, MSE: 114.7486
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385954, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4767, R2 Score: -21.320247, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.75, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 34.8934, Cross Entropy: 1.379464, Accuracy: 0.3415, Precision: 0.3328, Recall: 0.3415, F1 Score: 0.2986, AUC: 0.5314, R2 Score: -20.617381, MAE: 10.3872, MSE: 113.0926
Training: Fold 2 - Total Loss: 34.9345, Cross Entropy: 1.379980, Accuracy: 0.3468, Precision: 0.3289, Recall: 0.3468, F1 Score: 0.2967, AUC: 0.5123, R2 Score: -21.830414, MAE: 10.4043, MSE: 113.2284
Training: Fold 3 - Total Loss: 34.7169, Cross Entropy: 1.384514, Accuracy: 0.2764, Precision: 0.2746, Recall: 0.2764, F1 Score: 0.2475, AUC: 0.4740, R2 Score: -22.178081, MAE: 10.3755, MSE: 112.4925
Training: Fold 4 - Total Loss: 35.3909, Cross Entropy: 1.380575, Accuracy: 0.3662, Precision: 0.3716, Recall: 0.3662, F1 Score: 0.3324, AUC: 0.4901, R2 Score: -20.612784, MAE: 10.4611, MSE: 114.7483
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385954, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.5033, R2 Score: -21.320246, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.19, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.8567, Cross Entropy: 1.381693, Accuracy: 0.2993, Precision: 0.2840, Recall: 0.2993, F1 Score: 0.2612, AUC: 0.4835, R2 Score: -20.623872, MAE: 10.3793, MSE: 112.9651
Training: Fold 2 - Total Loss: 34.8637, Cross Entropy: 1.380974, Accuracy: 0.3521, Precision: 0.3523, Recall: 0.3521, F1 Score: 0.3193, AUC: 0.5062, R2 Score: -21.820411, MAE: 10.3936, MSE: 112.9901
Training: Fold 3 - Total Loss: 34.7480, Cross Entropy: 1.381326, Accuracy: 0.3239, Precision: 0.3203, Recall: 0.3239, F1 Score: 0.2825, AUC: 0.5162, R2 Score: -22.174605, MAE: 10.3797, MSE: 112.6035
Training: Fold 4 - Total Loss: 35.3919, Cross Entropy: 1.380872, Accuracy: 0.3363, Precision: 0.3092, Recall: 0.3363, F1 Score: 0.2980, AUC: 0.4818, R2 Score: -20.610392, MAE: 10.4616, MSE: 114.7510
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385954, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.5224, R2 Score: -21.320244, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.21, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.9122, Cross Entropy: 1.381200, Accuracy: 0.3187, Precision: 0.3105, Recall: 0.3187, F1 Score: 0.2878, AUC: 0.4892, R2 Score: -20.626000, MAE: 10.3891, MSE: 113.1513
Training: Fold 2 - Total Loss: 34.8932, Cross Entropy: 1.381380, Accuracy: 0.3345, Precision: 0.3151, Recall: 0.3345, F1 Score: 0.2945, AUC: 0.5113, R2 Score: -21.826488, MAE: 10.3979, MSE: 113.0875
Training: Fold 3 - Total Loss: 34.7339, Cross Entropy: 1.383270, Accuracy: 0.3099, Precision: 0.2941, Recall: 0.3099, F1 Score: 0.2725, AUC: 0.4969, R2 Score: -22.183930, MAE: 10.3785, MSE: 112.5521
Training: Fold 4 - Total Loss: 35.3925, Cross Entropy: 1.381337, Accuracy: 0.3151, Precision: 0.2855, Recall: 0.3151, F1 Score: 0.2773, AUC: 0.5171, R2 Score: -20.611620, MAE: 10.4630, MSE: 114.7520
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385954, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4377, R2 Score: -21.320245, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.87, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.9038, Cross Entropy: 1.380551, Accuracy: 0.3257, Precision: 0.2948, Recall: 0.3257, F1 Score: 0.2821, AUC: 0.4944, R2 Score: -20.616743, MAE: 10.3884, MSE: 113.1248
Training: Fold 2 - Total Loss: 34.8906, Cross Entropy: 1.382895, Accuracy: 0.3151, Precision: 0.2927, Recall: 0.3151, F1 Score: 0.2768, AUC: 0.4787, R2 Score: -21.828326, MAE: 10.3971, MSE: 113.0754
Training: Fold 3 - Total Loss: 34.6843, Cross Entropy: 1.381234, Accuracy: 0.3292, Precision: 0.3141, Recall: 0.3292, F1 Score: 0.2866, AUC: 0.5217, R2 Score: -22.182590, MAE: 10.3705, MSE: 112.3915
Training: Fold 4 - Total Loss: 35.4352, Cross Entropy: 1.380475, Accuracy: 0.3116, Precision: 0.2895, Recall: 0.3116, F1 Score: 0.2767, AUC: 0.4960, R2 Score: -20.609002, MAE: 10.4670, MSE: 114.8961
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385954, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.5353, R2 Score: -21.320246, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.50, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.8282, Cross Entropy: 1.379929, Accuracy: 0.3750, Precision: 0.3684, Recall: 0.3750, F1 Score: 0.3354, AUC: 0.4977, R2 Score: -20.615966, MAE: 10.3755, MSE: 112.8742
Training: Fold 2 - Total Loss: 34.8566, Cross Entropy: 1.380851, Accuracy: 0.3222, Precision: 0.3048, Recall: 0.3222, F1 Score: 0.2856, AUC: 0.5109, R2 Score: -21.823681, MAE: 10.3917, MSE: 112.9665
Training: Fold 3 - Total Loss: 34.7362, Cross Entropy: 1.381170, Accuracy: 0.3257, Precision: 0.3072, Recall: 0.3257, F1 Score: 0.2827, AUC: 0.5227, R2 Score: -22.174688, MAE: 10.3768, MSE: 112.5647
Training: Fold 4 - Total Loss: 35.3825, Cross Entropy: 1.380900, Accuracy: 0.3275, Precision: 0.3122, Recall: 0.3275, F1 Score: 0.2948, AUC: 0.5050, R2 Score: -20.618688, MAE: 10.4615, MSE: 114.7197
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385954, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4655, R2 Score: -21.320245, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.36, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.8460, Cross Entropy: 1.380794, Accuracy: 0.3380, Precision: 0.3303, Recall: 0.3380, F1 Score: 0.3062, AUC: 0.5217, R2 Score: -20.630480, MAE: 10.3771, MSE: 112.9316
Training: Fold 2 - Total Loss: 34.8495, Cross Entropy: 1.382500, Accuracy: 0.3116, Precision: 0.3267, Recall: 0.3116, F1 Score: 0.2782, AUC: 0.4667, R2 Score: -21.826318, MAE: 10.3898, MSE: 112.9391
Training: Fold 3 - Total Loss: 34.7953, Cross Entropy: 1.381990, Accuracy: 0.3063, Precision: 0.2751, Recall: 0.3063, F1 Score: 0.2569, AUC: 0.5075, R2 Score: -22.179634, MAE: 10.3874, MSE: 112.7595
Training: Fold 4 - Total Loss: 35.3597, Cross Entropy: 1.381638, Accuracy: 0.3363, Precision: 0.3116, Recall: 0.3363, F1 Score: 0.2966, AUC: 0.4885, R2 Score: -20.620378, MAE: 10.4558, MSE: 114.6418
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385954, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.5228, R2 Score: -21.320245, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.50, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.8460, Cross Entropy: 1.380158, Accuracy: 0.3327, Precision: 0.3184, Recall: 0.3327, F1 Score: 0.2988, AUC: 0.5083, R2 Score: -20.620431, MAE: 10.3788, MSE: 112.9330
Training: Fold 2 - Total Loss: 34.8849, Cross Entropy: 1.382251, Accuracy: 0.3116, Precision: 0.2695, Recall: 0.3116, F1 Score: 0.2652, AUC: 0.4926, R2 Score: -21.816098, MAE: 10.3971, MSE: 113.0576
Training: Fold 3 - Total Loss: 34.6922, Cross Entropy: 1.381509, Accuracy: 0.3151, Precision: 0.3171, Recall: 0.3151, F1 Score: 0.2754, AUC: 0.5120, R2 Score: -22.176878, MAE: 10.3711, MSE: 112.4172
Training: Fold 4 - Total Loss: 35.3160, Cross Entropy: 1.380566, Accuracy: 0.3327, Precision: 0.3188, Recall: 0.3327, F1 Score: 0.2986, AUC: 0.5106, R2 Score: -20.616894, MAE: 10.4489, MSE: 114.4988
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385955, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.4427, R2 Score: -21.320247, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.71, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.8372, Cross Entropy: 1.379895, Accuracy: 0.3451, Precision: 0.3539, Recall: 0.3451, F1 Score: 0.3184, AUC: 0.5312, R2 Score: -20.626354, MAE: 10.3755, MSE: 112.9044
Training: Fold 2 - Total Loss: 34.9123, Cross Entropy: 1.382196, Accuracy: 0.3451, Precision: 0.3280, Recall: 0.3451, F1 Score: 0.3040, AUC: 0.4734, R2 Score: -21.823450, MAE: 10.4012, MSE: 113.1493
Training: Fold 3 - Total Loss: 34.8788, Cross Entropy: 1.381328, Accuracy: 0.3275, Precision: 0.2837, Recall: 0.3275, F1 Score: 0.2704, AUC: 0.5178, R2 Score: -22.178773, MAE: 10.4006, MSE: 113.0396
Training: Fold 4 - Total Loss: 35.3894, Cross Entropy: 1.379654, Accuracy: 0.3521, Precision: 0.3243, Recall: 0.3521, F1 Score: 0.3149, AUC: 0.5314, R2 Score: -20.613837, MAE: 10.4626, MSE: 114.7455
Validation: Fold 5 - Total Loss: 35.5619, Cross Entropy: 1.385954, Accuracy: 0.2324, Precision: 0.0540, Recall: 0.2324, F1 Score: 0.0876, AUC: 0.5102, R2 Score: -21.320245, MAE: 10.4918, MSE: 115.3058
Avg Latency (ms): 6.33, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 20.66 MB
====================================================================================================

In [114]:
main("tinynet-a", EPOCHS=10)

====================================================================================================
Training Model: tinynet-a
Initial Backbone Model Size: 25.08 MB
Modified Backbone Model Size: 20.62 MB


Epoch 1/10
Training: Fold 1 - Total Loss: 34.2180, Cross Entropy: 1.376339, Accuracy: 0.3257, Precision: 0.2952, Recall: 0.3257, F1 Score: 0.3058, AUC: 0.5414, R2 Score: -20.146265, MAE: 10.2775, MSE: 110.8484
Training: Fold 2 - Total Loss: 34.1973, Cross Entropy: 1.382716, Accuracy: 0.2746, Precision: 0.2767, Recall: 0.2746, F1 Score: 0.2727, AUC: 0.4932, R2 Score: -21.312716, MAE: 10.2875, MSE: 110.7646
Training: Fold 3 - Total Loss: 34.0297, Cross Entropy: 1.384983, Accuracy: 0.2852, Precision: 0.2517, Recall: 0.2852, F1 Score: 0.2630, AUC: 0.5067, R2 Score: -21.660836, MAE: 10.2639, MSE: 110.2008
Training: Fold 4 - Total Loss: 34.7113, Cross Entropy: 1.382419, Accuracy: 0.3099, Precision: 0.2525, Recall: 0.3099, F1 Score: 0.2717, AUC: 0.4858, R2 Score: -20.144008, MAE: 10.3532, MSE: 112.4786
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4734, R2 Score: -21.396422, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.54, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Best model saved with Accuracy: 0.3873

Epoch 2/10
Training: Fold 1 - Total Loss: 34.0794, Cross Entropy: 1.378216, Accuracy: 0.3556, Precision: 0.3127, Recall: 0.3556, F1 Score: 0.3283, AUC: 0.5293, R2 Score: -20.146910, MAE: 10.2545, MSE: 110.3820
Training: Fold 2 - Total Loss: 34.1408, Cross Entropy: 1.379316, Accuracy: 0.3134, Precision: 0.2906, Recall: 0.3134, F1 Score: 0.2968, AUC: 0.5494, R2 Score: -21.297981, MAE: 10.2774, MSE: 110.5842
Training: Fold 3 - Total Loss: 33.9655, Cross Entropy: 1.386452, Accuracy: 0.2905, Precision: 0.2534, Recall: 0.2905, F1 Score: 0.2658, AUC: 0.5142, R2 Score: -21.652718, MAE: 10.2523, MSE: 109.9831
Training: Fold 4 - Total Loss: 34.6251, Cross Entropy: 1.380969, Accuracy: 0.3134, Precision: 0.2842, Recall: 0.3134, F1 Score: 0.2957, AUC: 0.5101, R2 Score: -20.147294, MAE: 10.3376, MSE: 112.1948
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4794, R2 Score: -21.396423, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.76, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 3/10
Training: Fold 1 - Total Loss: 34.1387, Cross Entropy: 1.378005, Accuracy: 0.3187, Precision: 0.2958, Recall: 0.3187, F1 Score: 0.3038, AUC: 0.5361, R2 Score: -20.129754, MAE: 10.2642, MSE: 110.5803
Training: Fold 2 - Total Loss: 34.1350, Cross Entropy: 1.381920, Accuracy: 0.2905, Precision: 0.2719, Recall: 0.2905, F1 Score: 0.2749, AUC: 0.5245, R2 Score: -21.305672, MAE: 10.2759, MSE: 110.5590
Training: Fold 3 - Total Loss: 33.9884, Cross Entropy: 1.386129, Accuracy: 0.2782, Precision: 0.2578, Recall: 0.2782, F1 Score: 0.2650, AUC: 0.5005, R2 Score: -21.652757, MAE: 10.2583, MSE: 110.0603
Training: Fold 4 - Total Loss: 34.6050, Cross Entropy: 1.379776, Accuracy: 0.3292, Precision: 0.2992, Recall: 0.3292, F1 Score: 0.3091, AUC: 0.5413, R2 Score: -20.132684, MAE: 10.3346, MSE: 112.1305
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4346, R2 Score: -21.396421, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.84, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 4/10
Training: Fold 1 - Total Loss: 34.1614, Cross Entropy: 1.378772, Accuracy: 0.2923, Precision: 0.2617, Recall: 0.2923, F1 Score: 0.2714, AUC: 0.4952, R2 Score: -20.144160, MAE: 10.2692, MSE: 110.6543
Training: Fold 2 - Total Loss: 34.2411, Cross Entropy: 1.381677, Accuracy: 0.3433, Precision: 0.2936, Recall: 0.3433, F1 Score: 0.3120, AUC: 0.5409, R2 Score: -21.312215, MAE: 10.2938, MSE: 110.9131
Training: Fold 3 - Total Loss: 33.9919, Cross Entropy: 1.384047, Accuracy: 0.3028, Precision: 0.2638, Recall: 0.3028, F1 Score: 0.2764, AUC: 0.5194, R2 Score: -21.652622, MAE: 10.2580, MSE: 110.0770
Training: Fold 4 - Total Loss: 34.7001, Cross Entropy: 1.383262, Accuracy: 0.3169, Precision: 0.2874, Recall: 0.3169, F1 Score: 0.2997, AUC: 0.5016, R2 Score: -20.140927, MAE: 10.3511, MSE: 112.4394
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4340, R2 Score: -21.396422, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.34, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 5/10
Training: Fold 1 - Total Loss: 34.2058, Cross Entropy: 1.376551, Accuracy: 0.3046, Precision: 0.2907, Recall: 0.3046, F1 Score: 0.2929, AUC: 0.5512, R2 Score: -20.154326, MAE: 10.2754, MSE: 110.8072
Training: Fold 2 - Total Loss: 34.1936, Cross Entropy: 1.381297, Accuracy: 0.3081, Precision: 0.2739, Recall: 0.3081, F1 Score: 0.2856, AUC: 0.5122, R2 Score: -21.313075, MAE: 10.2862, MSE: 110.7555
Training: Fold 3 - Total Loss: 33.9553, Cross Entropy: 1.382183, Accuracy: 0.3011, Precision: 0.2655, Recall: 0.3011, F1 Score: 0.2773, AUC: 0.5417, R2 Score: -21.660739, MAE: 10.2524, MSE: 109.9591
Training: Fold 4 - Total Loss: 34.6606, Cross Entropy: 1.381534, Accuracy: 0.3151, Precision: 0.2692, Recall: 0.3151, F1 Score: 0.2848, AUC: 0.5078, R2 Score: -20.156607, MAE: 10.3434, MSE: 112.3118
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4611, R2 Score: -21.396423, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.57, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 6/10
Training: Fold 1 - Total Loss: 34.1125, Cross Entropy: 1.381894, Accuracy: 0.3046, Precision: 0.2796, Recall: 0.3046, F1 Score: 0.2886, AUC: 0.5136, R2 Score: -20.136995, MAE: 10.2600, MSE: 110.4839
Training: Fold 2 - Total Loss: 34.1897, Cross Entropy: 1.379327, Accuracy: 0.3028, Precision: 0.2924, Recall: 0.3028, F1 Score: 0.2951, AUC: 0.5407, R2 Score: -21.297972, MAE: 10.2847, MSE: 110.7473
Training: Fold 3 - Total Loss: 33.9603, Cross Entropy: 1.386712, Accuracy: 0.3134, Precision: 0.2862, Recall: 0.3134, F1 Score: 0.2962, AUC: 0.5114, R2 Score: -21.658308, MAE: 10.2517, MSE: 109.9652
Training: Fold 4 - Total Loss: 34.6601, Cross Entropy: 1.379701, Accuracy: 0.3046, Precision: 0.2753, Recall: 0.3046, F1 Score: 0.2859, AUC: 0.5212, R2 Score: -20.138373, MAE: 10.3445, MSE: 112.3143
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4068, R2 Score: -21.396421, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.15, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 7/10
Training: Fold 1 - Total Loss: 34.1658, Cross Entropy: 1.377621, Accuracy: 0.3151, Precision: 0.2879, Recall: 0.3151, F1 Score: 0.2960, AUC: 0.5570, R2 Score: -20.149039, MAE: 10.2696, MSE: 110.6716
Training: Fold 2 - Total Loss: 34.1801, Cross Entropy: 1.379643, Accuracy: 0.2940, Precision: 0.2734, Recall: 0.2940, F1 Score: 0.2812, AUC: 0.5147, R2 Score: -21.313364, MAE: 10.2830, MSE: 110.7144
Training: Fold 3 - Total Loss: 34.0123, Cross Entropy: 1.386263, Accuracy: 0.3081, Precision: 0.2759, Recall: 0.3081, F1 Score: 0.2804, AUC: 0.5201, R2 Score: -21.683754, MAE: 10.2607, MSE: 110.1397
Training: Fold 4 - Total Loss: 34.6990, Cross Entropy: 1.380852, Accuracy: 0.3134, Precision: 0.2945, Recall: 0.3134, F1 Score: 0.2987, AUC: 0.5298, R2 Score: -20.144247, MAE: 10.3506, MSE: 112.4413
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.3460, R2 Score: -21.396422, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.73, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 8/10
Training: Fold 1 - Total Loss: 34.1694, Cross Entropy: 1.378826, Accuracy: 0.3116, Precision: 0.2960, Recall: 0.3116, F1 Score: 0.3014, AUC: 0.5210, R2 Score: -20.132942, MAE: 10.2697, MSE: 110.6806
Training: Fold 2 - Total Loss: 34.2544, Cross Entropy: 1.379634, Accuracy: 0.2975, Precision: 0.2773, Recall: 0.2975, F1 Score: 0.2827, AUC: 0.5380, R2 Score: -21.307094, MAE: 10.2949, MSE: 110.9620
Training: Fold 3 - Total Loss: 34.0257, Cross Entropy: 1.387416, Accuracy: 0.2729, Precision: 0.2615, Recall: 0.2729, F1 Score: 0.2628, AUC: 0.4980, R2 Score: -21.662470, MAE: 10.2626, MSE: 110.1818
Training: Fold 4 - Total Loss: 34.6155, Cross Entropy: 1.379190, Accuracy: 0.3310, Precision: 0.2912, Recall: 0.3310, F1 Score: 0.3039, AUC: 0.5356, R2 Score: -20.147169, MAE: 10.3379, MSE: 112.1667
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4455, R2 Score: -21.396421, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.09, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 9/10
Training: Fold 1 - Total Loss: 34.0840, Cross Entropy: 1.380466, Accuracy: 0.2905, Precision: 0.2775, Recall: 0.2905, F1 Score: 0.2797, AUC: 0.5231, R2 Score: -20.129711, MAE: 10.2531, MSE: 110.3924
Training: Fold 2 - Total Loss: 34.1947, Cross Entropy: 1.383151, Accuracy: 0.2870, Precision: 0.2584, Recall: 0.2870, F1 Score: 0.2679, AUC: 0.5143, R2 Score: -21.324262, MAE: 10.2863, MSE: 110.7550
Training: Fold 3 - Total Loss: 34.0186, Cross Entropy: 1.387505, Accuracy: 0.2887, Precision: 0.2549, Recall: 0.2887, F1 Score: 0.2658, AUC: 0.5043, R2 Score: -21.669553, MAE: 10.2630, MSE: 110.1577
Training: Fold 4 - Total Loss: 34.6462, Cross Entropy: 1.378073, Accuracy: 0.2923, Precision: 0.2655, Recall: 0.2923, F1 Score: 0.2758, AUC: 0.5395, R2 Score: -20.130108, MAE: 10.3391, MSE: 112.2718
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.3755, R2 Score: -21.396422, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.49, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Epoch 10/10
Training: Fold 1 - Total Loss: 34.1088, Cross Entropy: 1.380447, Accuracy: 0.3116, Precision: 0.2864, Recall: 0.3116, F1 Score: 0.2938, AUC: 0.5327, R2 Score: -20.137792, MAE: 10.2593, MSE: 110.4750
Training: Fold 2 - Total Loss: 34.1497, Cross Entropy: 1.382063, Accuracy: 0.3292, Precision: 0.2943, Recall: 0.3292, F1 Score: 0.3066, AUC: 0.5132, R2 Score: -21.309321, MAE: 10.2788, MSE: 110.6076
Training: Fold 3 - Total Loss: 34.0189, Cross Entropy: 1.384676, Accuracy: 0.2923, Precision: 0.2630, Recall: 0.2923, F1 Score: 0.2707, AUC: 0.5015, R2 Score: -21.658549, MAE: 10.2607, MSE: 110.1656
Training: Fold 4 - Total Loss: 34.7244, Cross Entropy: 1.379657, Accuracy: 0.2887, Precision: 0.2657, Recall: 0.2887, F1 Score: 0.2744, AUC: 0.5197, R2 Score: -20.146724, MAE: 10.3545, MSE: 112.5289
Validation: Fold 5 - Total Loss: 35.6661, Cross Entropy: 1.368784, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.4301, R2 Score: -21.396422, MAE: 10.5103, MSE: 115.6930
Avg Latency (ms): 4.38, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

Fine-tuned Model Size: 20.63 MB
====================================================================================================

In [19]:
for arch in models_list:
    infer(arch, "QUANTIZATION")

====================================================================================================
mobilenetv2
Initial Backbone Model Size: 14.24 MB
Modified Backbone Model Size: 9.78 MB

Testing: Total Loss: 33.5098, Cross Entropy: 1.362259, Accuracy: 0.3662, Precision: 0.1341, Recall: 0.3662, F1 Score: 0.1963, AUC: 0.5000, R2 Score: -20.658460, MAE: 10.1787, MSE: 108.5206
Avg Latency (ms): 3.41, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
resnet18
Initial Backbone Model Size: 46.83 MB
Modified Backbone Model Size: 45.04 MB

Testing: Total Loss: 32.7224, Cross Entropy: 1.352546, Accuracy: 0.3662, Precision: 0.1341, Recall: 0.3662, F1 Score: 0.1963, AUC: 0.4795, R2 Score: -20.137611, MAE: 10.0501, MSE: 105.9186
Avg Latency (ms): 2.08, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
densenet121
Initial Backbone Model Size: 32.47 MB
Modified Backbone Model Size: 28.90 MB

Testing: Total Loss: 33.3912, Cross Entropy: 1.462638, Accuracy: 0.2042, Precision: 0.0417, Recall: 0.2042, F1 Score: 0.0693, AUC: 0.4248, R2 Score: -20.530558, MAE: 10.1476, MSE: 107.8910
Avg Latency (ms): 8.48, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
vgg16
Initial Backbone Model Size: 553.44 MB
Modified Backbone Model Size: 71.72 MB

Testing: Total Loss: 33.9995, Cross Entropy: 1.405085, Accuracy: 0.0915, Precision: 0.1444, Recall: 0.0915, F1 Score: 0.0630, AUC: 0.5747, R2 Score: -20.964778, MAE: 10.2536, MSE: 110.0531
Avg Latency (ms): 1.98, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
vit-tiny
Initial Backbone Model Size: 22.92 MB
Modified Backbone Model Size: 22.25 MB

Testing: Total Loss: 33.9231, Cross Entropy: 1.375772, Accuracy: 0.3662, Precision: 0.1476, Recall: 0.3662, F1 Score: 0.2063, AUC: 0.4840, R2 Score: -20.930421, MAE: 10.2444, MSE: 109.8667
Avg Latency (ms): 2.34, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
efficientnet-b0
Initial Backbone Model Size: 21.43 MB
Modified Backbone Model Size: 16.96 MB

Testing: Total Loss: 34.1783, Cross Entropy: 1.398230, Accuracy: 0.0563, Precision: 0.0032, Recall: 0.0563, F1 Score: 0.0060, AUC: 0.5000, R2 Score: -21.087472, MAE: 10.2835, MSE: 110.6651
Avg Latency (ms): 4.34, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
shufflenetv2-0.5x
Initial Backbone Model Size: 5.59 MB
Modified Backbone Model Size: 2.02 MB

Testing: Total Loss: 34.2739, Cross Entropy: 1.382254, Accuracy: 0.3732, Precision: 0.1393, Recall: 0.3732, F1 Score: 0.2029, AUC: 0.5755, R2 Score: -21.158716, MAE: 10.3008, MSE: 111.0212
Avg Latency (ms): 3.63, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
regnety-400mf
Initial Backbone Model Size: 17.61 MB
Modified Backbone Model Size: 16.07 MB

Testing: Total Loss: 34.4958, Cross Entropy: 1.412491, Accuracy: 0.0563, Precision: 0.0032, Recall: 0.0563, F1 Score: 0.0060, AUC: 0.5787, R2 Score: -21.292109, MAE: 10.3332, MSE: 111.6902
Avg Latency (ms): 6.15, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
mnasnet0_5
Initial Backbone Model Size: 9.04 MB
Modified Backbone Model Size: 4.58 MB

Testing: Total Loss: 34.2529, Cross Entropy: 1.381014, Accuracy: 0.3732, Precision: 0.1393, Recall: 0.3732, F1 Score: 0.2029, AUC: 0.5000, R2 Score: -21.145280, MAE: 10.2975, MSE: 110.9540
Avg Latency (ms): 2.55, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
convnext-tiny
Initial Backbone Model Size: 114.41 MB
Modified Backbone Model Size: 111.72 MB

Testing: Total Loss: 34.1986, Cross Entropy: 1.381170, Accuracy: 0.3169, Precision: 0.1391, Recall: 0.3169, F1 Score: 0.1932, AUC: 0.5396, R2 Score: -21.106799, MAE: 10.2887, MSE: 110.7726
Avg Latency (ms): 2.87, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
ghostnetv2
Initial Backbone Model Size: 25.11 MB
Modified Backbone Model Size: 20.64 MB

Testing: Total Loss: 33.8750, Cross Entropy: 1.385313, Accuracy: 0.2042, Precision: 0.0417, Recall: 0.2042, F1 Score: 0.0693, AUC: 0.4035, R2 Score: -20.891273, MAE: 10.2357, MSE: 109.6843
Avg Latency (ms): 7.85, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
tinynet-a
Initial Backbone Model Size: 25.08 MB
Modified Backbone Model Size: 20.62 MB

Testing: Total Loss: 33.9772, Cross Entropy: 1.369315, Accuracy: 0.3662, Precision: 0.1341, Recall: 0.3662, F1 Score: 0.1963, AUC: 0.4633, R2 Score: -20.966853, MAE: 10.2541, MSE: 110.0621
Avg Latency (ms): 5.04, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00

In [53]:
import onnxruntime as ort

for arch in models_list:
    for mode in ["pytorch", "onnx"]:
        infer(arch, "QUANTIZATION", mode)

====================================================================================================
mobilenetv2
Initial Backbone Model Size: 14.24 MB
Modified Backbone Model Size: 9.78 MB

Testing mobilenetv2 in pytorch mode
Running inference for fp32
None
Testing: Total Loss: 34.8684, Cross Entropy: 1.362514, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -23.814954, MAE: 10.4203, MSE: 113.0487
Avg Latency (ms): 3.75, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Running inference for fp16
None
Testing: Total Loss: 34.8684, Cross Entropy: 1.362514, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -23.814954, MAE: 10.4203, MSE: 113.0487
Avg Latency (ms): 3.07, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
Running inference for int8
None
Testing: Total Loss: 34.8684, Cross Entropy: 1.362514, Accuracy: 0.3873, Precision: 0.1500, Recall: 0.3873, F1 Score: 0.2163, AUC: 0.5000, R2 Score: -23.814954, MAE: 10.4203, MSE: 113.0487
Avg Latency (ms): 3.05, Avg Memory Before (MB): 0.00, Avg Memory After (MB): 0.00, Avg Max Memory (MB): 0.00
====================================================================================================
mobilenetv2
Initial Backbone Model Size: 14.24 MB
Modified Backbone Model Size: 9.78 MB

Testing mobilenetv2 in onnx mode
Running inference for fp32
✅ Successfully exported ONNX model: /home/sebastian-cruz6/cp-anemia-detection/notebooks/weights/onnx/model_best_accuracy_mobilenetv2_QUANTIZATION.onnx
<onnxruntime.capi.onnxruntime_inference_collection.InferenceSession object at 0x75ed61c5c260>

AttributeError: 'NoneType' object has no attribute 'get_inputs'

In [58]:
!pip install onnxruntime-tools
!python -m onnxruntime.tools.check_model /home/sebastian-cruz6/cp-anemia-detection/notebooks/weights/onnx/model_best_accuracy_mobilenetv2_QUANTIZATION.onnx

Requirement already satisfied: onnxruntime-tools in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (1.7.0)
Requirement already satisfied: onnx in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from onnxruntime-tools) (1.17.0)
Requirement already satisfied: numpy in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from onnxruntime-tools) (2.0.0)
Requirement already satisfied: coloredlogs in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from onnxruntime-tools) (15.0.1)
Requirement already satisfied: psutil in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from onnxruntime-tools) (6.1.1)
Requirement already satisfied: py-cpuinfo in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from onnxruntime-tools) (9.0.0)
Requirement already satisfied: py3nvml in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from onnxruntime-tools) (0.2.7)
Requirement already satisfied: packaging in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from onnxruntime-tools) (24.2)
Requirement already satisfied: humanfriendly>=9.1 in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from coloredlogs->onnxruntime-tools) (10.0)
Requirement already satisfied: protobuf>=3.20.2 in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from onnx->onnxruntime-tools) (6.30.1)
Requirement already satisfied: xmltodict in /home/sebastian-cruz6/cp-anemia-detection/cawt/lib/python3.12/site-packages (from py3nvml->onnxruntime-tools) (0.14.2)
/home/sebastian-cruz6/cp-anemia-detection/cawt/bin/python: No module named onnxruntime.tools.check_model

In [64]:
import onnx

# Load ONNX model
try:
    onnx_model = onnx.load("/home/sebastian-cruz6/cp-anemia-detection/notebooks/weights/onnx/model_best_accuracy_mobilenetv2_QUANTIZATION.onnx")
    onnx.checker.check_model(onnx_model)
    print("✅ ONNX model is valid!")
except onnx.checker.ValidationError as e:
    print(f"❌ ONNX model validation failed: {e}")

✅ ONNX model is valid!